### ISSUE TITLE
请求作者增加一些功能与修复一个BUG

### ISSUE THREAD

**Issue by StarryVoid** [seatonjiang/kratos#1]
你好，作者。
我想问一下能否增加以下功能
1、Login to view all 隐藏内容登录用户可见
2、小工具中，能否增加文章目录功能？
3、首页不显示某些文章/分类
4、登陆后跳转到首页（开关）

提出几个BUG
1、顶部菜单子自定义模式下，重影
![image](https://cloud.githubusercontent.com/assets/20756365/17795603/7b057458-65ec-11e6-9a06-f53631744abd.png)

作者的主题非常棒，fontawesome.io的图标库也很好看

**Comment by ghost** [comment]
@StarryVoid 首先感谢你对这个项目的支持！
1、Login to view all 隐藏内容登录用户可见
->这个可以实现，主要是这款模板没有写用户前端页面，所以就没有这个功能。
2、小工具中，能否增加文章目录功能？
->文章目录是有的啊，叫分类目录。
3、首页不显示某些文章/分类
->这个功能预计在下一个版本中加入到主题中
4、登陆后跳转到首页（开关）
 @->这个没有用户的前端界面犯懒一下，就先不搞了
最后一个问题，顶部的重影，可以把网址发出来嘛，我单独给你看一下，之前没有这个问题的。

**Comment by StarryVoid** [comment]
2、分类目录？的确有两个，但是我两个都添加上后，显示的都是站点目录，而不是当前文章的目录（h1,h2,h3,h4,h5之类）

最后一个BUG，顶部的重影在自定义站点内。平时站点显示是没有问题的。
刚刚重置了一下主题，莫名奇妙没错误了，，不知道怎么回事

对了，我使用的是2.0.0版本主题，，2.0.2主题代码高亮感觉没2.0.0好。
