### ISSUE TITLE
希望能增加IE8兼容

### ISSUE THREAD

**Issue by kkkgo** [seatonjiang/kratos#10]
虽然IE8的用户不算多不过要是能够兼容就完美了 锦上添花的事情
又漂亮又兼容IE8的主题不多....

**Comment by kkkgo** [comment]
实在很喜欢这个主题....纠结IE兼容没有换....

**Comment by Vtrois** [comment]
这个问题还在评估，可能会在下一个大版本更新的时候有所优化

**Comment by Heluwe** [comment]
@lixuy 你现在用的啥主题呢

**Comment by ghost** [comment]
IE只兼容IE11，还是使用现代浏览器吧 😃
