### ISSUE TITLE
顶部如何添加分类或者外链,

### ISSUE THREAD

**Issue by logdns** [seatonjiang/kratos#100]
**问题描述**
顶部如何添加分类或者外链

![](https://ws1.sinaimg.cn/large/5d821655gy1g24icv7a5gj20wz02kwea.jpg)

**Comment by 907739769** [comment]
外观自定义里面的菜单选项

**Comment by logdns** [comment]
感谢大佬的提点,
 模版有搜索模块吗?>
还是要自己去小工具 添加
