### ISSUE TITLE
于WP-User-Avatar插件的兼容问题

### ISSUE THREAD

**Issue by Nineteen-Hundred** [seatonjiang/kratos#105]
**问题描述**

主题与WP-User-Avatar插件的http协议有冲突，修改后可用

**复现步奏**

1. 使用WP User Avatar插件设置头像
2. 安装Kratos主题
3. 发现几乎所有页面头像均无法加载

**解决方案**

经检查，Kratos主题默认头像地址前缀为https，而实际头像前缀为http，因此修改主题模版函数中kratos_get_https_avatar函数，将https统一改为http即可。

**Comment by seatonjiang** [comment]
这个问题已经在 3.0.0 版本中修复，还请升级测试
