### ISSUE TITLE
建议增加存档页面及修改logo设置

### ISSUE THREAD

**Issue by nicky1605** [seatonjiang/kratos#106]
首先感谢作者大佬辛苦的劳动，我想说作者的这个作品完全就是我想要的作品。

不过关于使用中有两个想法，暂时拿出来跟作者分享下：

1、建议页面模板中增加存档的模板，不仅仅是我省了一个插件的问题，而且是很多插件显示的存档效果跟这个主题不搭，显示出来很丑。有基础代码能力的也可以自己增加模块，但是可能就不会跟这个主题页面契合，所以如果大佬有时间可以考虑增加一个页面模板。

2、这个建议其实多少也是因为我强迫症的原因。主题的设置里面对logo的设置是需要上传，对广告的设置是有固定的文件夹。我反而觉得应该反过来，至少logo的设置应该是固定的一个文件夹链接（/wp-content/themes/Kratos/images），因为毕竟一般用户的logo是不会经常更换的，倒是广告有可能会有固定更新

谢谢~

**Comment by ccinoo** [comment]
作者好像有段时间没出现了。

**Comment by seatonjiang** [comment]
存档页面将在后续版本中更新，logo的问题在 3.0.0 版本中已经修复了，欢迎测试
