### ISSUE TITLE
与wp Editor.md存在兼容性问题

### ISSUE THREAD

**Issue by TKXZH** [seatonjiang/kratos#107]
**问题描述**

使用WP Editor.md插件编辑代码时，在本主题下，代码块显示会出现border

- 设备：（手机、平板等移动设备时填写此项）所有平台
- 浏览器及版本：chrome
- 演示地址：

**复现步奏**

1. 安装本主题
2. 安装wp Editor.md，新建文章，添加代码快

通过移除本主题style.css中code的border可以修复这个现象

**Comment by seatonjiang** [comment]
这个问题已经在 3.0.0 版本中修复，还请升级测试
