### ISSUE TITLE
初学者的困惑

### ISSUE THREAD

**Issue by matrix-1992** [seatonjiang/kratos#108]
**问题描述**

我想利用版主的模板制作多页面的个人网站，平时分享自己的心情动态，但是不知怎么得无法制作多页面，多菜单等，看着版主的页面好炫酷呀，能否对于初学者有一个入门指导文档或者视频

个人网站（比较丑，希望楼主莫见笑）
mingmin.vip

**Comment by ghost** [comment]
可以参考 https://developer.wordpress.org/ ，谷歌搜索 WordPress 开发指南也可以找到相关教程。
