### ISSUE TITLE
评论功能显示bug

### ISSUE THREAD

**Issue by wintertee** [seatonjiang/kratos#109]
在WordPress仪表盘-设置-讨论- 评论作者必须填入姓名和电子邮件地址 这一项取消后，页面的评论处 “邮箱”后仍有强制标识“*”。

**Comment by seatonjiang** [comment]
这个问题在 3.0 稳定版进行优化

**Comment by seatonjiang** [comment]
3.0.0 版本中，该问题已修复，请升级测试。
