### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function get_header() in D:\xampp\htdocs\demo2\index.php:8 Stack trace: #0 {main} thrown in D:\xampp\htdocs\demo2\index.php on line 8

### ISSUE THREAD

**Issue by 9yues** [seatonjiang/kratos#110]
**问题描述**
不管用哪个wordpress都会报这个错误
（简明扼要的描述一下问题）
代码是完全在github下载下来的，然后启动，就报这个错误了
**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2.

**Comment by ghost** [comment]
这个报错说不好是哪里问题，默认安装 WordPress 会出这个问题吗？

**Comment by seatonjiang** [comment]
这个问题应该是你的主题放错了位置，目前 3.0.0 版本已经更新，还请升级测试。
