### ISSUE TITLE
更换社交网络共享按钮

### ISSUE THREAD

**Issue by hoainamgo** [seatonjiang/kratos#114]
你好,

谢谢分享好主题
我用这个主题感觉很好。
如果我想放弃微博，微信，加上twitter和linkedin 怎么做?

非常感谢。

**Comment by seatonjiang** [comment]
近期会更新 3.0 的稳定版本，这个功能会进行优化

**Comment by ccinoo** [comment]
> 近期会更新 3.0 的稳定版本，这个功能会进行优化

(⊙o⊙)哇。。。期待新版本

**Comment by hoainamgo** [comment]
你好,
我用主题

我有一些问题:
1. 字体溢出
https://drive.google.com/file/d/11xEXI42ip10ayICKJNjV49L4hkNjvwtk/view
2. 文章标题字符太少
https://drive.google.com/file/d/15LoH7R_xJjiuM2Oct1GsuRlg49VCPLj_/view
3. 在手机上使用wiget未出现

**Comment by seatonjiang** [comment]
@hoainamgo  收到问题，你这个是越越南语吗？

**Comment by hoainamgo** [comment]
> @hoainamgo 收到问题，你这个是越越南语吗？

没错

Demo: hostwp.us  ^^我请朋友修理

**Comment by seatonjiang** [comment]
@hoainamgo 
3.x 版本新增修改了一些，linkedin 目前没做图
![image](https://user-images.githubusercontent.com/57834639/73516742-60213a80-4434-11ea-9374-469742de750f.png)

**Comment by seatonjiang** [comment]
@hoainamgo 
字体溢出的问题也在3.x版本解决了，等推送即可
![image](https://user-images.githubusercontent.com/57834639/73516787-89da6180-4434-11ea-85c3-f607e91d740d.png)
![image](https://user-images.githubusercontent.com/57834639/73516792-8e9f1580-4434-11ea-87b8-ea76fa4e7098.png)

**Comment by seatonjiang** [comment]
3.0.0 版本已推送，还请升级测试
