### ISSUE TITLE
建议：添加首页的鼠标悬停到文章后的动态元素

### ISSUE THREAD

**Issue by zop-debug** [seatonjiang/kratos#115]
**建议**
在网站首页当鼠标悬停到某篇文章的标题或者某篇文章占用的整个方框的时候，该文章的方框能产生动态元素，例如稍微放大一点点或者震动一下。
我个人觉得目前首页很干净整洁但是就是缺少一点点动态元素，希望dalao能够考虑下，不需要太多动态元素，就这个就行了。

**Comment by seatonjiang** [comment]
这样感觉整体有点不搭，我试试效果

**Comment by seatonjiang** [comment]
在 3.0.0 版本中，鼠标到文章标题或者阅读详情时，会改变其颜色，欢迎升级测试
