### ISSUE TITLE
关于字体较浅的问题

### ISSUE THREAD

**Issue by yuhengTech** [seatonjiang/kratos#116]
**问题描述**

您好，感觉网页端的字体的显示比较浅，进行网页打印的时候效果不太好，算是BUG么？有没有什么方法可以修改一下？十分感谢！

**产生环境**

- 设备：PC浏览器感觉会比较浅，手机一切正常
- 浏览器及版本：360极速浏览器，谷歌浏览器
- 演示地址：
比如贵站发布页这里的使用须知，感觉有些浅。
![image](https://user-images.githubusercontent.com/47713961/69804448-8ef31880-1219-11ea-9fd1-4cdb6862146f.png)

**Comment by chengzhangzuji** [comment]
[在有字体对比的时候，字体颜色的确很浅，看的非常的不舒服。

**Comment by seatonjiang** [comment]
收到问题，感谢反馈，近期更新

**Comment by seatonjiang** [comment]
3.x 版本修复了这个问题，等推送
![image](https://user-images.githubusercontent.com/57834639/73516638-0e78b000-4434-11ea-9b5b-dc058631c916.png)

**Comment by seatonjiang** [comment]
3.0.0 版本中，该问题已修复，请升级测试。
