### ISSUE TITLE
盼望作者能加个目录的功能。

### ISSUE THREAD

**Issue by swjsky** [seatonjiang/kratos#120]
**问题描述**
1、最好能加个目录功能。
2、能不能加个自动翻译的标签哈。例如<translate></translate>自动翻译成英文或者中文哈。
（简明扼要的描述一下问题）

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2.

**Comment by swjsky** [comment]
我用的插件实现了目录功能，但是好像效果不太好哈。
https://blog.shikey.com/
最好能有个简单说明哈，例如H1标签预览，H2标签预览等等，可能是我没有仔细看，但是实践好久才发现H2标签自带system。

**Comment by seatonjiang** [comment]
收到需求，与#121 的一样，3.x 我找个地方放这个东西

**Comment by xuwenbin** [comment]
同求目录功能，按照分类自动生成就很好。

**Comment by seatonjiang** [comment]
目录需求统一在 #121 处理
