### ISSUE TITLE
希望增加滚动目录树和github表情支持

### ISSUE THREAD

**Issue by Eriky-git** [seatonjiang/kratos#121]
**问题描述**

希望增加滚动目录树和github表情支持

**Comment by seatonjiang** [comment]
收到反馈，这里 Github 表情是指的 emoji 吗？

**Comment by Eriky-git** [comment]
> 收到反馈，这里 Github 表情是指的 emoji 吗？

是滴~感谢！

**Comment by seatonjiang** [comment]
emoji 表情支持与否在于你的数据库排序规则，建议用 utf8mb4

**Comment by wei** [comment]
可能是指 [Gitmoji](https://gitmoji.carloscuesta.me/)

**Comment by wangyongjie2017** [comment]
**希望作者加入文章目录树功能及代码高亮显示功能，辛苦，感谢。**

**Comment by Maple-pro** [comment]
文章目录树有插件可以实现的

**Comment by seatonjiang** [comment]
文章编辑器添加了『添加表情』的按钮，可以选择那里的表情加到文章中，也可以在数据库排序规则是 utf8mb4 的时候，直接写入 emoji 表情。

![image](https://user-images.githubusercontent.com/57834639/102018599-2dacd180-3da9-11eb-9671-21fe285c222a.png)

**Comment by seatonjiang** [comment]
新版本中添加了这个功能，等推送即可。
@Eriky-git @wei @wangyongjie2017 @Maple-pro @ rzfyu @xuwenbin @swjsky
![image](https://user-images.githubusercontent.com/57834639/119221669-fb0ac000-bb22-11eb-842b-80d07ad43fa8.png)
