### ISSUE TITLE
外观自定义

### ISSUE THREAD

**Issue by rorizhang** [seatonjiang/kratos#123]
**问题描述**

外观自定义无法使用。
页面第一行文本显示：您计划的修改刚才发布了
页面第二行链接显示：定制器全新变化（点击链接无反映）

**产生环境**

- 设备：Mac OS X 10.15.2
- 浏览器及版本：Chrome 79.0.3945.130
- 演示地址：

**复现步奏**

1. 正常登陆
2. 点击外观-自定义

**Comment by seatonjiang** [comment]
出现这个问题，可能是wordpress的问题，尝试刷清空缓存，重试一下是否正常。
