### ISSUE TITLE
社交按钮加入Bilibili和码云

### ISSUE THREAD

**Issue by ghost** [seatonjiang/kratos#124]
不是可否在社交按钮加入Bilibili和码云
毕竟使用这两个平台的人挺多的
现在只能手动改PHP代码

**Comment by seatonjiang** [comment]
目前 3.x 版本在做修改，你可以填写一下统计表，后期将在这些里面选择6-7个展示
https://docs.qq.com/form/fill/DV2VzZUNiSE9zZEls?_w_tencentdocx_form=1

![image](https://user-images.githubusercontent.com/57834639/73181322-f6faa800-4151-11ea-947c-e0b563f67731.png)

**Comment by seatonjiang** [comment]
统计结束了，最终的社交平台图标是这样的
![image](https://user-images.githubusercontent.com/57834639/73544118-726e9900-4473-11ea-8812-f61ab671e5e1.png)
