### ISSUE TITLE
与“闪电博”提供的“博客社交分享组件”插件不兼容

### ISSUE THREAD

**Issue by DefiedParty** [seatonjiang/kratos#125]
**问题描述**

使用最新版kratos测试，启用“闪电博”提供的“博客社交分享组件”插件不生效，文章结尾未加载此插件，使用默认主题即可使用。

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 浏览器及版本：Chrome79
- 演示地址：暂无

**复现步奏**

1. 安装“闪电博”提供的“博客社交分享组件”插件
2. 启用并配置插件
3.查看文章结尾

**Comment by seatonjiang** [comment]
3.x版本正在修改，等 Alpha 版的时候，我测试一下这个兼容性

**Comment by seatonjiang** [comment]
3.0.0 版本已经推送了，还请升级测试 @DefiedParty

**Comment by DefiedParty** [comment]
已经可以使用
![image](https://user-images.githubusercontent.com/44311872/75020710-38227580-54ce-11ea-85fe-4ad0b3e8dd77.png)
