### ISSUE TITLE
Blog的评论无法进行回复

### ISSUE THREAD

**Issue by zhaoke92** [seatonjiang/kratos#128]
**问题描述**

（简明扼要的描述一下问题）

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2.

**Comment by zhaoke92** [comment]
![image](https://user-images.githubusercontent.com/7760203/74932116-018c2280-541c-11ea-986e-af09a7c14403.png)
I can not click it

**Comment by seatonjiang** [comment]
升级 3.0.0 版本试一下，是不是还会出现这个问题
