### ISSUE TITLE
全文搜索搜索中文关键字得不到正确的搜索结果

### ISSUE THREAD

**Issue by zhaoke92** [seatonjiang/kratos#129]
**问题描述**

（简明扼要的描述一下问题）

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2.

**Comment by seatonjiang** [comment]
尝试升级 3.0.0 版本试一下，这个问题是否还存在
