### ISSUE TITLE
希望能够添加小工具,友情链接呀

### ISSUE THREAD

**Issue by logdns** [seatonjiang/kratos#130]
**问题描述**

希望能够添加小工具,友情链接呀

**环境信息**

PHP 版本：7.3.11
Kratos 版本：3.0.0
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36

**复现步奏**

没有友情链接感觉少点啥

**Comment by Clouder0** [comment]
可以在后台的链接功能中添加链接分类目录，即可在小工具中添加 链接 来实现友情链接。

**Comment by logdns** [comment]
> 可以在后台的链接功能中添加链接分类目录，即可在小工具中添加 链接 来实现友情链接。

求教  我之前就有链接分类目录 友情链接   这么添加到小工具

**Comment by ccinoo** [comment]
最新版只发现两个问题，其他蛮好：
1、可用小工具少了很多，之前用的HTML工具就没有了。
2、首页目录只有一级，不支持多级了。

**Comment by seatonjiang** [comment]
@logdns @ccinoo 小工具已经新增了友情链接以及自定义 HTML，等推送新版本吧

![image](https://user-images.githubusercontent.com/57834639/75086877-272c3f80-5574-11ea-9203-220614ceed7b.png)
