### ISSUE TITLE
 顶部图片的动态效果怎么没了，2.8的时候还有的

### ISSUE THREAD

**Issue by zhaoke92** [seatonjiang/kratos#131]
**问题描述**

 顶部图片的动态效果怎么没了，2.8的时候还有的

**环境信息**

PHP 版本：7.0.8
Kratos 版本：3.0.0
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36

**Comment by seatonjiang** [comment]
新增了效果，并且新增了一个开关，等新版本推送吧

![image](https://user-images.githubusercontent.com/57834639/75088180-d709a900-5584-11ea-8bc7-0cd0dd82a561.png)

**Comment by ccinoo** [comment]
哦？这具体是什么效果？以前版本一直没用过。。。
