### ISSUE TITLE
文章评论的回复问题

### ISSUE THREAD

**Issue by zhaoke92** [seatonjiang/kratos#132]
**问题描述**

Blog的回复功能依旧有bug，无法回复不到我选中的评论上面，有时新增了一条评论有时回复到其他评论下面了

**环境信息**

PHP 版本：7.0.8
Kratos 版本：3.0.0
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36

**Comment by seatonjiang** [comment]
我这里暂时还没有复现你反馈的这个问题，希望提供一个动图复现一下
