### ISSUE TITLE
版本升级时该如何操作

### ISSUE THREAD

**Issue by zhaoke92** [seatonjiang/kratos#133]
**问题描述**

版本升级时该如何操作，我直接上传主题的文件夹覆盖旧的版本上会导致之前的一些主题设置丢失掉

**Comment by ccinoo** [comment]
我是覆盖升级有报错。然后选择了删除后重新git clone后重新配置，反正后台配置的地方也不多。

**Comment by seatonjiang** [comment]
因为主题配置做了变更，有些变量名字做了调整，所以在升级之后，配置信息会有消失。
