### ISSUE TITLE
新版小工具及首页目录不支持多级问题

### ISSUE THREAD

**Issue by ccinoo** [seatonjiang/kratos#134]
**问题描述**

最新版只发现两个问题，其他蛮好：
1. 可用小工具少了很多，之前用的HTML工具就没有了。
2. 首页目录只有一级，不支持多级了。

**环境信息**

PHP 版本：7.3.0
Kratos 版本：3.0.0
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36

**复现步奏**

![image](https://user-images.githubusercontent.com/30647119/75085954-7751d480-5569-11ea-9839-79a320998edf.png)

**Comment by seatonjiang** [comment]
第一个问题已经在新的推送中进行了新增 8617a21b6f73787cced986f8ec9888a3d8afa0a4，关于主题二级目录的问题，新版本不准备再做二级链接了。

**Comment by ccinoo** [comment]
> 第一个问题已经在新的推送中进行了新增 [8617a21](https://github.com/Vtrois/Kratos/commit/8617a21b6f73787cced986f8ec9888a3d8afa0a4)，关于主题二级目录的问题，新版本不准备再做二级链接了。

谢谢，更新后小工具问题确实解决了。请问为什么不支持多级目录了？
