### ISSUE TITLE
希望能加回纯色导航背景

### ISSUE THREAD

**Issue by bcblog** [seatonjiang/kratos#136]
**问题描述**

（请图文并茂的描述一下具体问题，截图可以直接 Ctrl + V 进行粘贴）

**环境信息**

（将主题设置—>关于主题中的「基础信息」内容粘贴到这里）

**复现步奏**

（请分步描述复现这个问题的步骤）

**Comment by swjsky** [comment]
非常赞同

**Comment by xuwenbin** [comment]
不能更赞同

**Comment by seatonjiang** [comment]
新增了顶部导航菜单样式，等下个版本推送

![image](https://user-images.githubusercontent.com/57834639/75113349-284e9100-5688-11ea-85ac-aff12496a0f9.png)
![image](https://user-images.githubusercontent.com/57834639/75113353-2f759f00-5688-11ea-83a4-765ea1a7757d.png)
![image](https://user-images.githubusercontent.com/57834639/75113359-3ef4e800-5688-11ea-8fca-ec84fcd8e6a3.png)
![image](https://user-images.githubusercontent.com/57834639/75113361-487e5000-5688-11ea-832f-91d95edd8580.png)
