### ISSUE TITLE
更新到3.0之后图片不是居中的

### ISSUE THREAD

**Issue by alpha87** [seatonjiang/kratos#137]
整体感觉不错，感觉整个网站对比度更高，看的更清楚了。

但是文章中的图片都不是居中的

**Comment by seatonjiang** [comment]
图片居中的问题需要在插入图片的时候，点击图片进行设置的，在之前 2.8 版本中这个功能不起作用所有的图片都默认设置为居中。

![image](https://user-images.githubusercontent.com/57834639/75102643-e8f15780-5629-11ea-8c6a-a92201338a52.png)

**Comment by alpha87** [comment]
您好，如果使用 markdown 编辑该如何居中？因为我是使用 MWeb 直接发布的，不能这样设置，有其他解决办法吗？
