### ISSUE TITLE
给主人的建议

### ISSUE THREAD

**Issue by swjsky** [seatonjiang/kratos#138]
**问题描述**

2.8升级到3.0之后，原先的设置都会消失，并且小工具也消失了很多无法添加。没有办法重新换到了2.8.

在这里也给大家一个建议就是把3.0单独放一个文件夹内单独安装调试尝鲜，不要在原风格基础上安装。

**Comment by seatonjiang** [comment]
因为 3.0 版本主题设置都做了变更，所以在升级之前一定要自行备份配置，小工具还在新增之前已经新增了两个 8617a21b6f73787cced986f8ec9888a3d8afa0a4 ，2.8 版本可以到这里下载 https://github.com/Vtrois/Kratos/releases/tag/v2.8.0

**Comment by seatonjiang** [comment]
新增了一些小工具，等下个版本推送即可。

![image](https://user-images.githubusercontent.com/57834639/75103227-c6b00780-5632-11ea-9ded-b80a61b75a47.png)
![image](https://user-images.githubusercontent.com/57834639/75103234-e6dfc680-5632-11ea-94aa-bdebc99a4cef.png)
