### ISSUE TITLE
3.0.0创建页面无法使用模板

### ISSUE THREAD

**Issue by zjf2610** [seatonjiang/kratos#139]
**问题描述**
![image](https://user-images.githubusercontent.com/40761556/75096825-60999500-55de-11ea-8f22-da6f04723452.png)

**环境信息**

PHP 版本：7.3.14
Kratos 版本：3.0.0
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

**复现步奏**

新建页面→页面属性栏→没有页面模板选项

**Comment by seatonjiang** [comment]
3.0 目前没有页面模板，后期会新增
