### ISSUE TITLE
3.0 版本移动端表格会超出范围

### ISSUE THREAD

**Issue by alpha87** [seatonjiang/kratos#142]
**问题描述**

![](https://i.loli.net/2020/02/23/vpNjzWloVKLsYAU.jpg)

移动端表格会超出边框范围，Safari 和 Chrome 都会超出。

**Comment by seatonjiang** [comment]
收到反馈，你这里的表格是怎么添加到编辑器中的呢？

**Comment by alpha87** [comment]
> 收到反馈，你这里的表格是怎么添加到编辑器中的呢？

使用 markdown 编辑的

**Comment by ziyooren** [comment]
用 TablePress 添加的表格也有同样的问题

**Comment by jiahao-shen** [comment]
不光是移动端……web端也有这个问题

**Comment by seatonjiang** [comment]
这个问题已经修复，等待新版本推送即可。

![image](https://user-images.githubusercontent.com/57834639/76720746-a1697180-6778-11ea-9597-090ca023f993.png)

![image](https://user-images.githubusercontent.com/57834639/76720765-adedca00-6778-11ea-8ec6-e3f6f8dbc7e6.png)
