### ISSUE TITLE
Widget_Link 显示框 padding 有误

### ISSUE THREAD

**Issue by xuwenbin** [seatonjiang/kratos#143]
**问题描述**
widget_links 显示的时候，内部的padding好像被置0了，导致里面内容和外框贴在了一起。

![image](https://user-images.githubusercontent.com/19218275/75111025-32649580-5670-11ea-9ea7-aa77ba236225.png)

**环境信息**

PHP 版本：7.3.14
Kratos 版本：3.0.0
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36

**复现步奏**

1、安装wordpress 5.3.2
2、安装本主题（从github main trunk下载的zip文件）
3、在wordpress管理界面设置《链接》，然后保存，查看页面效果
4、出现 padding 问题

**Comment by seatonjiang** [comment]
今天上午推送了这个问题，只是还没有发版 ad7cd532e85e7102323ff72e066484e54498dad7

**Comment by xuwenbin** [comment]
太好了。新版发布后，是不是直接下载zip文件，重新上传wordpress里就自动更新了？

另外，你这个主题确实是极简，好用。弱弱滴问一句，wordpress系统自带的菜单功能好像不起作用了。我试着添加菜单，但都没有在界面上显示出来。

**Comment by seatonjiang** [comment]
新版本已经推送了，可以在 WordPress 后台升级，也可以 Github 下载升级。菜单配置的时候，注意勾选显示位置。

![image](https://user-images.githubusercontent.com/57834639/75113747-4bc70b00-568b-11ea-9057-92066286dd47.png)

![image](https://user-images.githubusercontent.com/57834639/75113761-60a39e80-568b-11ea-8cd2-8ec21efbe4f1.png)
