### ISSUE TITLE
您好，3.0使用中的问题反馈

### ISSUE THREAD

**Issue by hahaleyile** [seatonjiang/kratos#144]
1、有序列表不显示数字，只显示圆圈
![image](https://user-images.githubusercontent.com/38727644/75115989-f09f1380-569e-11ea-9f0d-2aad30b5bd9d.png)

2、网易云音乐无法播放
![image](https://user-images.githubusercontent.com/38727644/75116011-14faf000-569f-11ea-9773-f27feb5b7b73.png)
![image](https://user-images.githubusercontent.com/38727644/75116019-1e845800-569f-11ea-906d-d824a18c82eb.png)
![image](https://user-images.githubusercontent.com/38727644/75116026-2a701a00-569f-11ea-92d9-a764d7ae2c7d.png)

3、多行代码从2.8版本到现在一直存在一个问题，第一行和后面几行不对齐
![image](https://user-images.githubusercontent.com/38727644/75116078-8c308400-569f-11ea-905f-ecbe489bb76e.png)

**Comment by seatonjiang** [comment]
第一个问题已经修复了，等版本推送。
第二个问题你引用的是有版权的音乐，所以不能播放。
第三个问题直接使用 pre 标签圈代码即可。

![image](https://user-images.githubusercontent.com/57834639/75155044-19c8ae00-574a-11ea-8ddf-4000856208eb.png)

![image](https://user-images.githubusercontent.com/57834639/75155211-7e840880-574a-11ea-958a-28e06b9c4a9d.png)

![image](https://user-images.githubusercontent.com/57834639/75155234-8b086100-574a-11ea-8a88-68d7d098da65.png)
