### ISSUE TITLE
widget_links 内容显示宽度问题

### ISSUE THREAD

**Issue by xuwenbin** [seatonjiang/kratos#145]
**问题描述**

widget_links 内容显示宽度太窄，导致不必要的换行。影响显示的美观性。

![image](https://user-images.githubusercontent.com/19218275/75122124-67ef9a00-56d5-11ea-84d9-835a5b0f0bf2.png)

**环境信息**

PHP 版本：7.3.14
Kratos 版本：3.0.1
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36

**复现步奏**

1、升级主题最新版：3.0.1
2、刷新页面
3、发现widget_links的padding的bug已经修复，但内容显示宽度过窄，导致了不必要的换行。

**Comment by seatonjiang** [comment]
可能你对 links 功能有误解，这里是按照友情链接的需求做的，实现的效果像下面这样

![image](https://user-images.githubusercontent.com/57834639/75137867-ba57a780-5723-11ea-9e90-5b275d6a94dd.png)

**Comment by xuwenbin** [comment]
哦，这样啊。知道了，是别的人的博客的连接。

**Comment by seatonjiang** [comment]
书签的话，可以自定义html来实现

**Comment by xuwenbin** [comment]
明白了，多谢。
