### ISSUE TITLE
标签聚合 widget 功能增强需求

### ISSUE THREAD

**Issue by xuwenbin** [seatonjiang/kratos#146]
**问题描述**

1、允许多选
2、选中的标签要跟没有选中的标签有所区别，比如高亮
3、Toggle功能：即点击标签选中，再点击一个已选中的标签则去除选择

![image](https://user-images.githubusercontent.com/19218275/75159709-9f9d2700-5753-11ea-9529-982dbfc6dc27.png)

**环境信息**

PHP 版本：7.3.14
Kratos 版本：3.0.1
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36

**Comment by seatonjiang** [comment]
这里鼠标滑过有高亮功能，标签是做的点击跳转，不是复选的功能，不可能实现多选。

![demo](https://i.loli.net/2020/02/26/dBQoUlP1jeyZNVJ.gif)

**Comment by xuwenbin** [comment]
看到hover的效果了。还是建议对选中的标签增加静态的高亮底色。当鼠标hover上去后，对于已经高亮的标签，可以保持颜色不变。对于未选中的标签，则继续使用现在hover效果。

至于多选，其实也可以参照上述思路：即所有被选中的标签，都有静态高亮。当鼠标hover上去时，保持不变。对于未选中的，则沿用现在的高亮效果。

**Comment by seatonjiang** [comment]
这个标签是跳转的链接啊，多选干什么？

**Comment by xuwenbin** [comment]
可以定位是“跳转”用，也可以定位是“过滤”用。多选可以是P2的需求吧，但"静态高亮+反选"（无论是服务于跳转还是过滤），应该都是一个不错的用户体验的提升。

1、我自己使用了一段时间后就发现，一旦选了一个标签，拉动屏幕看后面的帖子，我自己都忘记选的是哪个标签了。
2、而且，有时候我会点选不同的标签，看不同的文章。但一旦我想要回到首页就很讨厌。非要回退很多次。所以我才提意应该支持“高亮+反选”。

**Comment by seatonjiang** [comment]
这里标签功能与官方给出的功能保持一致，不决定修改。
