### ISSUE TITLE
分类提示没有跟着 "主要分类" 设定走

### ISSUE THREAD

**Issue by xuwenbin** [seatonjiang/kratos#147]
**问题描述**

一篇文章可以有多个分类，但系统允许文章作者指定一个主要分类。比如，编程、人工智能。这是两个分类，文章发布的时候指定“人工智能”作为主要分类。但由于“编程”排序的时候在“人工智能”前面，所以首页显示文章的时候就按照“编程”来显示分类。

希望可以修改程序，当一篇文章包含多个分类的时候，应该取 “主要分类” 显示出来。

![image](https://user-images.githubusercontent.com/19218275/75356457-f426da80-58ea-11ea-8653-d4b51a9ddaf6.png)

**环境信息**

PHP 版本：7.3.14
Kratos 版本：3.0.1
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36

**复现步奏**

1、撰写一篇文章
2、指定多个分类
3、设定一个主要分类
4、发现，主要分类并未显示在页面上；相反，页面上永远显示按照拼音字母排序的第一个分类。

**Comment by seatonjiang** [comment]
这个地方不是标签啊，这里是分类目录，如果是勾选了多个分类目录，会根据分类目录的名称首字母展示第一个，WordPress 没有主分类目录一说啊。

**Comment by xuwenbin** [comment]
我发issue的时候写错了，应该是“主要分类”，而不是标签。

在WordPresss最新版本里，可以指定“主要分类”（见下图）。

![image](https://user-images.githubusercontent.com/19218275/75356040-592e0080-58ea-11ea-85db-b08cafd3f933.png)

**Comment by seatonjiang** [comment]
这个主要分类我实在是弄不出来，你那是不是装了什么插件才出现。把插件都关了看看还有没有这个功能了？

**Comment by xuwenbin** [comment]
我是新装的wordpress，基本都是自带的插件。额外装了2个插件，一个是Yoast SEO，另外一个是蜜蜂采集。见下图。wordpress的版本是最新版：5.3.2。**会不会是因为你的测试环境没有升级到最新版的缘故？**

![image](https://user-images.githubusercontent.com/19218275/75406012-5105ad80-594a-11ea-8796-b75567d67902.png)

**Comment by seatonjiang** [comment]
@xuwenbin  我装 Yoast 测试了一下，也没有出现这个功能，我这里实在无法复现。

**Comment by xuwenbin** [comment]
要不我把我的网站开放给你debug？你告诉我需要什么？

**Comment by seatonjiang** [comment]
新建一个站点，一个插件一个插件的装，看具体是哪个插件出现的这个选项，告诉我这个插件我自己测试就可以了。

**Comment by seatonjiang** [comment]
这个问题确认是插件的问题，我这里更新到了5.7-alpha-49797 版本也没有找到这个配置，无法复现，后期出现问题，请再次打开此问题。

![image](https://user-images.githubusercontent.com/57834639/102018554-e7577280-3da8-11eb-838e-b28385600934.png)
