### ISSUE TITLE
首页文章特色图片能否增加开关选项？

### ISSUE THREAD

**Issue by Robotxm** [seatonjiang/kratos#148]
**问题描述**

因为平时写博客不太喜欢配特色图片，所以希望能有个选项关掉首页文章列表的特色图片显示。

**Comment by seatonjiang** [comment]
已更新，等正式版本推送

![image](https://user-images.githubusercontent.com/57834639/75350290-321f0100-58e1-11ea-8cdf-4edef2851b30.png)
![image](https://user-images.githubusercontent.com/57834639/75350304-3a773c00-58e1-11ea-978e-e9016e71e6a0.png)
![image](https://user-images.githubusercontent.com/57834639/75350311-3f3bf000-58e1-11ea-9f66-0162669b2591.png)
