### ISSUE TITLE
部分 CSS 会影响到 Enlighter 代码高亮插件的样式

### ISSUE THREAD

**Issue by Robotxm** [seatonjiang/kratos#149]
**问题描述**

如图所示，这个地方的`line-height`会造成 Enlighter 插件高亮的代码行高变大。
![image](https://user-images.githubusercontent.com/5405331/75244075-0844dc00-5806-11ea-8229-64ba2848ada7.png)

**环境信息**

PHP 版本：7.3.2
Kratos 版本：3.0.1
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36

**复现步骤**

启用 Enlighter 插件并启用 Kratos 主题。

**Comment by Robotxm** [comment]
补充一下，还会添加一个多余的`padding-left`。
![image](https://user-images.githubusercontent.com/5405331/75247319-9ae87980-580c-11ea-88be-a5c1fbc4b220.png)

**Comment by swjsky** [comment]
非常感谢提供如此漂亮的主题，我也遇到类似情况，就是与tablepress插件存在一点不兼容的地方，不会随body页面自动适应大小，但是2.8版本中不存此问题

**Comment by seatonjiang** [comment]
问题修复了，等版本推送即可

![image](https://user-images.githubusercontent.com/57834639/75356561-14ef3000-58eb-11ea-908c-842e4e780f60.png)
