### ISSUE TITLE
希望能增加一个设置文章摘要字数的选项

### ISSUE THREAD

**Issue by TechCiel** [seatonjiang/kratos#15]
RT

----------
Reported by A via QQ

**Comment by kkkgo** [comment]
大哥你有话能不能一次性说完

**Comment by TechCiel** [comment]
@lixuy 不是我一个反馈，是帮Vtrois整理的反馈，他本人表示要分开发的，谢谢

**Comment by ghost** [comment]
新增了功能  主题设置->站点配置->简介缩略 可自行调控缩略字数
