### ISSUE TITLE
标题不自动换行

### ISSUE THREAD

**Issue by ziyooren** [seatonjiang/kratos#150]
**问题描述**
稍微比较长一点的标题会被隐藏后半部分，对技术博客来说不是很友好，因为访客看不到完整的问题。希望能够调整样式，让标题自动折行完整显示

![image](https://user-images.githubusercontent.com/37561090/75319762-3975e880-58a8-11ea-8842-c392986e0c3b.png)

**环境信息**

PHP 版本：7.2.23
Kratos 版本：3.0.1
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

**复现步奏**

1. 撰写新文章
2. 设置一个长标题并发布
3. 在桌面环境和移动设备上查看文章列表

**Comment by xuwenbin** [comment]
+1，自动换行比较好。特别是对于手机用户来说。垂直滚动比点击打开一篇文章再回到首页来的方便。

**Comment by seatonjiang** [comment]
不换行是为了考虑整体的样式去做的，标题 16 个汉字理论上就能概况全了啊，标题要简短概况主旨啊

**Comment by xuwenbin** [comment]
主要是现在很多微信公众号的文章，标题很长。拉取过来后，发现显示不全。

**Comment by ziyooren** [comment]
> 不换行是为了考虑整体的样式去做的，标题 16 个汉字理论上就能概况全了啊，标题要简短概况主旨啊

限制行数确实可以提高整体性，不过其实折行标题也不会显得突兀，可以参考以本主题为基础二次开发的项目：https://github.com/xb2016/kratos-pjax 无论是单行还是多行标题都可以适应，主题的适用群体肯定会更广

**Comment by seatonjiang** [comment]
目前版本更新之后，PC 大屏可以显示 21 个汉字

**Comment by seatonjiang** [comment]
目前版本更新之后，PC 大屏可以显示 21 个汉字，可以满足大部分场景了，这里换行的样式暂时不添加。
