### ISSUE TITLE
默认特色图变形问题

### ISSUE THREAD

**Issue by ohotto** [seatonjiang/kratos#151]
**问题描述**

3.0.1版本，后台修改了默认特色图，尺寸和默认特色图尺寸保持了一致，但提交更改后发现播客主页特色图是变形的。（手机端不变形）

**环境信息**

PHP 版本：7.2.18
Kratos 版本：3.0.1
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**复现步奏**

①更改默认特色图
![image](https://user-images.githubusercontent.com/47439228/75400345-fcf2cd00-5939-11ea-87e8-16fa0849ee86.png)
②尺寸变形
![image](https://user-images.githubusercontent.com/47439228/75400369-0c721600-593a-11ea-8e64-0212709baee8.png)
③使用的特色图原图（不知道github有没有压缩）
![image](https://user-images.githubusercontent.com/47439228/75400377-1431ba80-593a-11ea-8229-d5f6bd285d00.png)

**P.S.**

顺便请教一下主题更新怎么操作比较好？

谢谢大佬！

**Comment by seatonjiang** [comment]
3.0.0 更新记录里写了，按照这个比例去调你的图即可

![image](https://user-images.githubusercontent.com/57834639/75407585-536a0680-594e-11ea-8b60-4c51f9ce94b3.png)

**Comment by ohotto** [comment]
谢谢，抱歉
