### ISSUE TITLE
文章图片无法居中

### ISSUE THREAD

**Issue by ziyooren** [seatonjiang/kratos#152]
**问题描述**

更换主题后发现图片全部都无法居中了，不论编辑的时候是否选择居中，发布后都是左边对齐。而且如果选择居中，图片说明有一定几率会变成竖排。

这是编辑状态，图片和说明都是居中：

![image](https://user-images.githubusercontent.com/37561090/75413726-4efb1900-5961-11ea-9c90-084daaa2fe7c.png)

这是发布后的状态，图片左侧对齐，图片说明变成竖排：

![image](https://user-images.githubusercontent.com/37561090/75414070-3f300480-5962-11ea-9f34-e79deec781e6.png)

**环境信息**

PHP 版本：7.2.23
Kratos 版本：3.0.2
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

**复现步奏**

1. 新建文章，插入尺寸不大于容器宽度的图片，输入图片说明
2. 选择居中对齐
3. 发布文章

**Comment by seatonjiang** [comment]
问题已修复，等推送新版本

![image](https://user-images.githubusercontent.com/57834639/75547911-f31ab800-5a66-11ea-95d2-f9577373522a.png)
