### ISSUE TITLE
v3.0.2 侧边栏导航菜单等小工具消失 

### ISSUE THREAD

**Issue by I-Nd** [seatonjiang/kratos#154]
**问题描述**

从 v2.8.0 更新到 v3.0.2，站点设置、SMTP等主题配置全部丢失，不是什么大问题，重配即可。
但是配置过程中发现 外观 - 自定义 - 小工具中只有下图所示的这些，其中导航菜单小工具也没有了。这是一个非常有用的小工具，请问这是 Bug 还是 Feature？
![图片](https://user-images.githubusercontent.com/28750098/75430962-1b32ea00-5987-11ea-9539-0df0aea149a4.png)

**环境信息**

    PHP 版本：7.3.4
    Kratos 版本：3.0.2
    WordPress 版本：5.3.2
    User Agent 信息：Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

**复现步奏**

WP后台 - 外观 - 自定义 - 小工具

**Comment by ccinoo** [comment]
导航菜单小工具?是指分类目录小工具吧？

![image](https://user-images.githubusercontent.com/30647119/75438227-8cc46580-5992-11ea-8436-fa72db73e96b.png)

**Comment by I-Nd** [comment]
> 
> 
> 导航菜单小工具?是指分类目录小工具吧？
> 
> ![image](https://user-images.githubusercontent.com/30647119/75438227-8cc46580-5992-11ea-8436-fa72db73e96b.png)

是啊，但是我这没有。问题描述中截图所示的小工具都是全部了。

**Comment by ccinoo** [comment]
> > 导航菜单小工具?是指分类目录小工具吧？
> > ![image](https://user-images.githubusercontent.com/30647119/75438227-8cc46580-5992-11ea-8436-fa72db73e96b.png)
> 
> 是啊，但是我这没有。问题描述中截图所示的小工具都是全部了。

哦，新版本是没有这个工具了。我是两个版本并存，方便随时切换。

**Comment by seatonjiang** [comment]
分类目录已经更新了，目前小工具已经有这些工具。

![image](https://user-images.githubusercontent.com/57834639/78466980-74d2c500-773a-11ea-9817-fb049a7b9e72.png)

![image](https://user-images.githubusercontent.com/57834639/78466970-5a98e700-773a-11ea-86d1-452ad4afdab4.png)
