### ISSUE TITLE
在移动端显示页面时，应引入Compact精简模式

### ISSUE THREAD

**Issue by xuwenbin** [seatonjiang/kratos#157]
**问题描述**

现在文章列表展示的方式，非常适合PC端，但对手机阅读不是很友好。手机屏幕小，每屏应该尽量显示更多的文章信息。请参考下面的对比图：右侧是其他主题在手机端的展示效果，左侧是本主题在手机端的展示效果。

右侧的精简模式可以在一屏上显示更多内容。

![image](https://user-images.githubusercontent.com/19218275/75512907-e62da280-5a2d-11ea-9fac-386668b10b37.png)

**环境信息**

PHP 版本：7.3.14
Kratos 版本：3.0.2
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

**复现步奏**

直接在手机浏览器中打开使用了本主题的wordpress站点。

**Comment by xuwenbin** [comment]
建议：移动端显示的时候，显示48x48大小的缩略图+文章的Title即可。如果title太长，最多显示2行，第二行显示不下的时候，就用 ... 结尾。

**Comment by xuwenbin** [comment]
此需求优先级较高，因为现在大家都习惯在手机上阅读。在首页显示文章列表的时候，绝大部分读者都希望看到更多的咨询。

**Comment by seatonjiang** [comment]
在移动端有右上角的导航按钮，可以替代下面的这个导航，暂时不考虑新增这个效果。
