### ISSUE TITLE
顶部菜单的二级分类不显示

### ISSUE THREAD

**Issue by chankenjio** [seatonjiang/kratos#159]
**问题描述**
更新完新版本之后，顶部菜单的二级分类显示不出来

**Comment by seatonjiang** [comment]
嗯，3.0 版本去掉了二级菜单的支持，目前没有考虑新增

**Comment by yujitai** [comment]
> 嗯，3.0 版本去掉了二级菜单的支持，目前没有考虑新增

为啥去掉呢？二级菜单不显示，折腾了半天，醉了。

**Comment by hughdj** [comment]
好吧，我也搞了好久  原来确实不支持

**Comment by seatonjiang** [comment]
https://github.com/Vtrois/Kratos/releases/tag/v3.0.0  这一点在版本变更记录中都有写啊

![image](https://user-images.githubusercontent.com/57834639/75605604-35073500-5b1f-11ea-9d0e-19b483e5b5a6.png)

**Comment by sunqqq1987** [comment]
二级菜单还是有用的。。。

**Comment by ccinoo** [comment]
> 二级菜单还是有用的。。。

加 1

**Comment by wkingnet** [comment]
> 二级菜单还是有用的。。。

+2

**Comment by Jomixedyu** [comment]
> 
> 
> 二级菜单还是有用的。。。

+3

**Comment by kevin-zhu-ca** [comment]
您好，我有两点建议：
1. 希望可以保留二级菜单，确实还是挺有需求的
2. 希望可以支持设置是否在顶部菜单中显示搜索功能，右下角不是常见的视觉热区，访客不一定留意的到。
感谢作者~

**Comment by seatonjiang** [comment]
@chankenjio @yujitai @hughdj @sunqqq1987 @ccinoo @wkingnet @Jayshonyves @njZhuMin 二级菜单问题在 #196 中同一解决

**Comment by seatonjiang** [comment]
@njZhuMin 搜索框小工具已经添加，等下个版本推送即可。

![image](https://user-images.githubusercontent.com/57834639/78450086-9a19f180-76ae-11ea-87e4-d5016d281046.png)
