### ISSUE TITLE
希望修复与热门插件JetPack的兼容性问题

### ISSUE THREAD

**Issue by TechCiel** [seatonjiang/kratos#16]
JetPack提示：

> WordPress REST API is disabled
Enable WordPress REST API to unlock Jetpack's full potential!

----------
Reported by hayeen via QQ

**Comment by ghost** [comment]
这个插件貌似国内的站点根本无法使用，而且还会导致网站特别慢！

**Comment by ghost** [comment]
修复了WordPress REST API调用
