### ISSUE TITLE
个人简介小工具会暴露WordPress后台登录地址

### ISSUE THREAD

**Issue by cuitz** [seatonjiang/kratos#160]
**问题描述**

个人简介小工具会暴露WordPress后台登录地址

希望在站长配置中增加一项“不链接到后台登录地址”之类的功能。

**Comment by seatonjiang** [comment]
因为去掉了 WordPress 自带的 Admin bar，所以新增了一个后台的快捷入口，如果没有登录态，自动跳转 wp_login_url() ，如果有登录态，则跳转 admin_url()，如果你没有修改入口地址，那么这两个地址是默认的，所有的 WordPress 都会跳转这些地址，不存在暴露不暴露一说，如果不希望这样，那么可以通过以下步骤进行修改：

1. 删除  `/inc/theme-widgets.php` 文件中 163 - 167 行的内容

https://github.com/Vtrois/Kratos/blob/6aa7ecaf7274b3e8c8ff2310fc2617aa9b8a24cf/inc/theme-widgets.php#L163-L167

2. 删除  `/inc/theme-widgets.php` 文件中 168 行的 ` </a>`

https://github.com/Vtrois/Kratos/blob/6aa7ecaf7274b3e8c8ff2310fc2617aa9b8a24cf/inc/theme-widgets.php#L168

**Comment by cuitzh** [comment]
非常感谢作者提出解决方案，上文中我所说的暴露指的安装了WP Hide Login等插件的条件下，WP Hide Login可以更改默认后台地址，头像链接到后台会使其失效。

**Comment by cuitz** [comment]
> 因为去掉了 WordPress 自带的 Admin bar，所以新增了一个后台的快捷入口，如果没有登录态，自动跳转 wp_login_url() ，如果有登录态，则跳转 admin_url()，如果你没有修改入口地址，那么这两个地址是默认的，所有的 WordPress 都会跳转这些地址，不存在暴露不暴露一说，如果不希望这样，那么可以通过以下步骤进行修改：
> 
> 1. 删除  `/inc/theme-widgets.php` 文件中 163 - 167 行的内容
> 
> https://github.com/Vtrois/Kratos/blob/6aa7ecaf7274b3e8c8ff2310fc2617aa9b8a24cf/inc/theme-widgets.php#L163-L167
> 
> 1. 删除  `/inc/theme-widgets.php` 文件中 168 行的 ` </a>`
> 
> https://github.com/Vtrois/Kratos/blob/6aa7ecaf7274b3e8c8ff2310fc2617aa9b8a24cf/inc/theme-widgets.php#L168
非常感谢作者提出解决方案，上文中我所说的暴露指的安装了WP Hide Login等插件的条件下，WP Hide Login可以更改默认后台地址，头像链接到后台会使其失效。
