### ISSUE TITLE
菜单项图标不显示，是不支持了么？

### ISSUE THREAD

**Issue by yujitai** [seatonjiang/kratos#161]
使用 fontawesome 插件设置菜单项图标，不能显示，是不支持了么？
![image](https://user-images.githubusercontent.com/25192944/75604896-7f38e800-5b18-11ea-8bda-8fd64c066d34.png)

**Comment by seatonjiang** [comment]
新版本中没有引入 fontawesome 项目，新版本使用的是 iconfont 做图标库，根据自己需要去新增图标，默认图标库仅配有主题需要的图标文件，图标库地址 https://www.iconfont.cn/collections/detail?cid=20676
