### ISSUE TITLE
建议 container 的宽度用百分比

### ISSUE THREAD

**Issue by wkingnet** [seatonjiang/kratos#163]
container有一个max-width，目前是像素1140px，建议改成百分比的显示我感觉更适应各种分辨率显示器一些，我自己调成70%效果不错

固定像素在1920*1080分辨率表现不错，但分辨率更高的话，两边白框会很多，而这款风格又是专注于写作的。即使1920分辨率下，详细文章页面，文章部分占整个屏幕比例也略小。

**Comment by xuwenbin** [comment]
+1，在我的2K屏上，两侧留白确实过多了些，希望能够改成百分比。

此致！

**Comment by chao-sun01io** [comment]
同感

**Comment by seatonjiang** [comment]
针对文章内页，新增了页面布局功能，等更新即可

![image](https://user-images.githubusercontent.com/57834639/83988922-545ffa80-a977-11ea-8440-4f30335c7366.png)

![image](https://user-images.githubusercontent.com/57834639/83988915-50cc7380-a977-11ea-86d4-80385aa5a207.png)

![image](https://user-images.githubusercontent.com/57834639/83988928-57f38180-a977-11ea-8747-40780073d566.png)
