### ISSUE TITLE
为啥我安装以后右侧没有信息栏的，求解答

### ISSUE THREAD

**Issue by gimgoo** [seatonjiang/kratos#164]
![image](https://user-images.githubusercontent.com/31849284/75792985-ac4ff980-5da9-11ea-93ef-aeff233b6d6d.png)

**Comment by xuwenbin** [comment]
安装完后，需要去后台配置右侧栏。

![image](https://user-images.githubusercontent.com/19218275/75878375-7582ed80-5e54-11ea-96b3-c320cec2b5a6.png)

**Comment by gimgoo** [comment]
> 安装完后，需要去后台配置右侧栏。
> 
> ![image](https://user-images.githubusercontent.com/19218275/75878375-7582ed80-5e54-11ea-96b3-c320cec2b5a6.png)

非常感谢，兄弟
