### ISSUE TITLE
建议将界面宽度修改为百分比

### ISSUE THREAD

**Issue by SheXinK** [seatonjiang/kratos#165]
**问题描述**
建议将界面宽度修改为百分比，屏幕过大时，两边空白出太宽！
（请图文并茂的描述一下具体问题，截图可以直接 Ctrl + V 进行粘贴）

**环境信息**

（将主题设置—>关于主题中的「基础信息」内容粘贴到这里）

**复现步奏**

（请分步描述复现这个问题的步骤）

**Comment by xuwenbin** [comment]
163描述了同样的需求，可以去那里+1，顶上去。

**Comment by seatonjiang** [comment]
问题统一在 #163 中处理
