### ISSUE TITLE
评论框不支持插件修改了

### ISSUE THREAD

**Issue by Hill-98** [seatonjiang/kratos#166]
3.0 之前的评论框是支持插件修改的，比如说我要安装一个给评论框加验证码的插件能显示出来，现在显示不出来了，

测试插件：https://wordpress.org/plugins/wp-captcha-booster/

**Comment by seatonjiang** [comment]
我这里测试复现一下

**Comment by seatonjiang** [comment]
3.0 版本之前的都是调用默认的评论，3.0 版本之后自定义了一个评论所以出现不兼容的现象，插件仅提供了选择评论块，并没有给出调用方法，这个暂时兼容不了。

![image](https://user-images.githubusercontent.com/57834639/83989799-29c37100-a97a-11ea-813d-4babb6cd2bb3.png)
![image](https://user-images.githubusercontent.com/57834639/83989873-5f685a00-a97a-11ea-96be-a2429e645af0.png)
