### ISSUE TITLE
段落内的换行导致行距异常

### ISSUE THREAD

**Issue by leeooii** [seatonjiang/kratos#167]
文章使用文本模式编辑
```
1111111
2222222
3333333

4444444
5555555
6666666
```
预览查看网页源码，产生了两个段落
```
<p>1111111<br />
2222222<br />
3333333</p>
<p>4444444<br />
5555555<br />
6666666</p>
```
但Kratos主题实际显示时，12和23之间的行距比34还大。使用wordpress官方主题时显示是正常的。

**Comment by seatonjiang** [comment]
问题已经定位修复，等新版推送即可。

![image](https://user-images.githubusercontent.com/57834639/76214506-d856f900-6247-11ea-9993-697371581dc3.png)
