### ISSUE TITLE
文章缩略图

### ISSUE THREAD

**Issue by jiahao-shen** [seatonjiang/kratos#168]
现在貌似只能全局开启文章缩略图或者关闭？
希望能在下一个版本中能支持多种样式，有设置feature image的就显示，没有的就不显示图只显示文字？🤔
还有就是第一次用这个主题🤗请问一下首页图片轮播在哪里呀？在设置里没找到🥺

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by seatonjiang** [comment]
轮播功能暂时没有，特色图显示的话有一个开关，可以选择开启或关闭，如果有的有有的没的话，主页会看起来很乱
