### ISSUE TITLE
页脚邮件

### ISSUE THREAD

**Issue by jiahao-shen** [seatonjiang/kratos#171]
页脚的电子邮件地址点开后会跳转到博客的子路径，然后显示404

**Comment by seatonjiang** [comment]
添加电子邮件地址，请按照提示进行填写，不要直接填邮箱，前面需要写协议头 mailto:

**注：提交 issues 请按照问题模板进行提交。**

![image](https://user-images.githubusercontent.com/57834639/76305240-c042b080-62ff-11ea-85c2-a0af681f2c0b.png)
