### ISSUE TITLE
还是居中的问题

### ISSUE THREAD

**Issue by jiahao-shen** [seatonjiang/kratos#173]
**问题描述**

在编辑器中设置图片居中后，偶尔会居中偶尔不居中，用Chrome查看网页元素发现，居中的都是p标签设置了text-align: center；但是在其他主题中，即便不设置该属性也能居中。
- 使用Kratos
<img width="1301" alt="Screen Shot 2020-03-11 at 19 52 52" src="https://user-images.githubusercontent.com/29255648/76414724-db322500-63d2-11ea-9537-31947c063fc0.png">
<img width="1530" alt="Screen Shot 2020-03-11 at 19 53 17" src="https://user-images.githubusercontent.com/29255648/76414739-e1280600-63d2-11ea-9005-60342167656a.png">

- 使用其他主题
<img width="1394" alt="Screen Shot 2020-03-11 at 19 53 59" src="https://user-images.githubusercontent.com/29255648/76415050-73c8a500-63d3-11ea-9f00-a9d32587065b.png">

**环境信息**

PHP 版本：7.1.33-12+ubuntu16.04.1+deb.sury.org+1
Kratos 版本：3.0.3
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

**复现步奏**

（请分步描述复现这个问题的步骤）

**Comment by seatonjiang** [comment]
#170 修复了这个问题，只是现在还没有推送版本，等 3.0.4 推送即可
