### ISSUE TITLE
B站视频无法正常播放？

### ISSUE THREAD

**Issue by jiahao-shen** [seatonjiang/kratos#177]
**问题描述**

插入B站视频无法正常播放，貌似是liteplayer报错？
<img width="1186" alt="Screen Shot 2020-03-14 at 02 24 41" src="https://user-images.githubusercontent.com/29255648/76649253-3d3d8680-659b-11ea-8884-4a2ea32035ca.png">

**环境信息**

PHP 版本：7.1.33-12+ubuntu16.04.1+deb.sury.org+1
Kratos 版本：3.0.4
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

**复现步奏**

插入cid，打开网页报错。

**Comment by seatonjiang** [comment]
CID 是否正确？试一下这个 [bilibili cid="144784399"]84655281[/bilibili] ，CID 通过这个 api 获取 https://www.bilibili.com/widget/getPageList?aid=84655281

**Comment by jiahao-shen** [comment]
试了……还是同样的问题，貌似是第三方包的问题？

**Comment by jiahao-shen** [comment]
看来是我插入的姿势不对。。。对不起打扰了
