### ISSUE TITLE
建议增强编辑器功能

### ISSUE THREAD

**Issue by DreamFerry** [seatonjiang/kratos#179]
建议为编辑器增加代码高亮，展开收缩，回复可见以及更改字体颜色的功能。图标及效果图已准备好，打赏已安排，坐等功能实现

![highlight](https://user-images.githubusercontent.com/41297263/76673867-5dddfe80-65e4-11ea-99e7-4538bc17cfd0.png)
![accordion](https://user-images.githubusercontent.com/41297263/76673869-60d8ef00-65e4-11ea-87a2-3bbcfec282e3.png)
![hide](https://user-images.githubusercontent.com/41297263/76673870-62a2b280-65e4-11ea-9a94-24d0aba862ac.png)
![20180820111812_49881](https://user-images.githubusercontent.com/41297263/76673872-6a625700-65e4-11ea-8f60-0c815b486a29.jpg)

**Comment by seatonjiang** [comment]
![image](https://user-images.githubusercontent.com/57834639/76673886-a990a800-65e4-11ea-9c97-c0df2d9fcf65.png)

**Comment by yenyoong99** [comment]
我有一个这样的代码放在function里能够实现：
```php
/* 
* 隐藏部分内容 评论后可见 
*/  
function reply_to_read($atts, $content=null) {  
        extract(shortcode_atts(array("notice" => '<p class="reply-to-read"><div style="text-align:center;border:1px dashed #FF9A9A;padding:8px;margin:10px auto;color:#FF6666;">温馨提示：此处内容需要<a href="'. get_permalink().'#respond" title="评论本文">"评论本文"</a>后，<a href="javascript:window.location.reload();" title="刷新本页">"刷新本页"</a>才能查看。</div></p>'), $atts));//notice默认值     
        $email = null;     
        $user_ID = (int) wp_get_current_user()->ID;     
        if ($user_ID > 0) {  
            $email = get_userdata($user_ID)->user_email;  
            $admin_email = "admin@yybloger.com"; //博主Email  
            if ($email == $admin_email) {//若是博主则直接显示内容  
                return '<p class="reply-to-read" style="background:no-repeat">'.$content.'</p>';  
            }  
        } else if (isset($_COOKIE['comment_author_email_' . COOKIEHASH])) {  
            $email = str_replace('%40', '@', $_COOKIE['comment_author_email_' . COOKIEHASH]);  
        } else {  
            return strpos($notice,'提示: 此处内容需要')  ? $notice : '<div style="text-align:center;border:1px dashed #FF9A9A;padding:8px;margin:10px auto;color:#FF6666;"><p class="reply-to-read" title="此处内容需要评论本文后才能查看."> 温馨提示：'.$notice.'&nbsp;需要<a href="'. get_permalink().'#respond" title="评论本文">"评论本文"</a>后，<a href="javascript:window.location.reload();" title="刷新本页">"刷新本页"</a>才能查看。</div></p>';//未检测到评论信息（昵称、网站等）。不是博主，且未评论  
        }  
        if (empty($email)) {  
            return 'TEST CODE：111'.$notice;//无email  
        }  
        global $wpdb;  
        $post_id = get_the_ID();  
        $query = "SELECT `comment_ID` FROM {$wpdb->comments} WHERE `comment_post_ID`={$post_id} and `comment_author_email`='{$email}' LIMIT 1";     
        if ($wpdb->get_results($query)) {  
            return '<p class="reply-to-read" style="background:no-repeat">'.do_shortcode($content).'</p>';//若已评论  
        } else {  
            return strpos($notice,'提示: 此处内容需要')  ? $notice : '<div style="text-align:center;border:1px dashed #FF9A9A;padding:8px;margin:10px auto;color:#FF6666;"><p class="reply-to-read" title="此处内容需要评论本文后才能查看."> 温馨提示：'.$notice.'&nbsp;需要<a href="'. get_permalink().'#respond" title="评论本文">"评论本文"</a>后，<a href="javascript:window.location.reload();" title="刷新本页">"刷新本页"</a>才能查看。</div></p>';//已评论其他，未评论此文章  
        }  
    }  
    add_shortcode('reply', 'reply_to_read');  
```
![image](https://user-images.githubusercontent.com/23697812/80474174-bf321500-8979-11ea-9194-4cf336d29481.png)

MarkDown😁使用感觉不错的，可以实现代码高亮，编辑文章也很方便。

**Comment by kiopc** [comment]
不应该是支付之后可见么

**Comment by iamlvtu** [comment]
这些功能网上一搜都好多方法介绍的～～～

**Comment by kiopc** [comment]
> 这些功能网上一搜都好多方法介绍的～～～

你那边有好点的代码高亮的代码没？像csdn那种，最好不是插件

**Comment by seatonjiang** [comment]
@yenyoong99 @XMD0718  回复可见加上了，等新版本推送

![image](https://user-images.githubusercontent.com/57834639/85216413-eb38a800-b3b6-11ea-8711-64a2fbfbd1ef.png)
![image](https://user-images.githubusercontent.com/57834639/85216414-ed9b0200-b3b6-11ea-8f08-38a098f5237b.png)
![image](https://user-images.githubusercontent.com/57834639/85216415-effd5c00-b3b6-11ea-986f-a2520781b36f.png)

**Comment by seatonjiang** [comment]
代码高亮的功能不准备新增，但是我对 Enlighter 做了兼容，样式也比较好看。
https://wordpress.org/plugins/enlighter/

![image](https://user-images.githubusercontent.com/57834639/85223819-4f2f9080-b3f8-11ea-9e72-3d41b1eaef0f.png)

**Comment by seatonjiang** [comment]
收缩功能在新版本中更新

![image](https://user-images.githubusercontent.com/57834639/85225629-45605a00-b405-11ea-8c50-249caa72b379.png)
![image](https://user-images.githubusercontent.com/57834639/85225631-4db89500-b405-11ea-95dd-ae4bd5f82331.png)

**Comment by DreamFerry** [comment]
@seatonjiang 
新版本已使用，目前发现存在以下问题：
1.展开收缩的标题默认为黑色加粗，希望可以自定义格式
2.更改字体颜色的功能仍未实现

**Comment by seatonjiang** [comment]
个性化的功能，根据自身需求写到 custom 中即可。

**Comment by DreamFerry** [comment]
@seatonjiang 这不是个性化的功能啊，这是大众需求
![-ffe9cfed87325cf](https://user-images.githubusercontent.com/41297263/85299167-845ee000-b4d7-11ea-8d8d-d71d6fd8a493.jpg)
