### ISSUE TITLE
标签聚合不显示

### ISSUE THREAD

**Issue by kylin-kai** [seatonjiang/kratos#180]
添加了标签不显示

**Comment by seatonjiang** [comment]
请按照 Issues 提供的格式提交问题：

**问题描述**

（请图文并茂的描述一下具体问题，截图可以直接 Ctrl + V 进行粘贴）

**环境信息**

（将主题设置—>关于主题中的「基础信息」内容粘贴到这里）

**复现步奏**

（请分步描述复现这个问题的步骤）

**Comment by whosneo** [comment]
<img width="406" alt="截屏2020-03-1516 38 18" src="https://user-images.githubusercontent.com/11043462/76698231-62391300-66db-11ea-84e4-bce93738983e.png">
仔细检查自己的设置吧，用起来没有问题的。
