### ISSUE TITLE
表格超出的问题

### ISSUE THREAD

**Issue by jiahao-shen** [seatonjiang/kratos#181]
**问题描述**

不光是手机上，电脑上的表格也会超出页面，图1是Chrome下，图2是Safari下。不管是用TinyMCE Advanced还是直接把表格复制粘贴都会这样。
<img width="843" alt="Screen Shot 2020-03-15 at 03 07 16" src="https://user-images.githubusercontent.com/29255648/76688725-55c8a200-666a-11ea-9a8c-c23b052d06b2.png">
<img width="615" alt="Screen Shot 2020-03-15 at 03 05 41" src="https://user-images.githubusercontent.com/29255648/76688726-58c39280-666a-11ea-8228-e398dcf6b0de.png">

**环境信息**

PHP 版本：7.1.33-12+ubuntu16.04.1+deb.sury.org+1
Kratos 版本：3.0.5
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

**复现步奏**

表格内容过多就会这样

**Comment by seatonjiang** [comment]
问题统一在 #142 中解决
