### ISSUE TITLE
图片居中的 CSS 规则还是有点问题

### ISSUE THREAD

**Issue by Hill-98** [seatonjiang/kratos#182]
#170 上次修复的问题没有考虑到带链接的图片，也就是`p > a > img`，下一个版本改一下吧。

**Comment by seatonjiang** [comment]
感谢反馈，问题修复了，等推送新版本即可。

![image](https://user-images.githubusercontent.com/57834639/76721852-59e4e480-677c-11ea-959d-ca08e110d452.png)
