### ISSUE TITLE
更新v3.0.5后小工具缺失

### ISSUE THREAD

**Issue by withsalt** [seatonjiang/kratos#184]
**问题描述**

作者你好，感谢开发这款主题。我从2.8.0版本升级之后，发现缺少了搜素、分类等小工具。
目前全部的小工具只有这些：
![8G0HEt.jpg](https://s1.ax1x.com/2020/03/16/8G0HEt.jpg)
**环境信息**

`
PHP 版本：7.3.11  
Kratos 版本：3.0.5  
WordPress 版本：5.3.2  
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36 
`

**Comment by seatonjiang** [comment]
问题与 #154 相同，在 #154 中解决。

**Comment by seatonjiang** [comment]
搜索功能已经新增了，升级新版本即可。

![image](https://user-images.githubusercontent.com/57834639/78466739-57e8c280-7737-11ea-9254-3ffba584c5bb.png)
