### ISSUE TITLE
建议增加pjax全站无刷新功能

### ISSUE THREAD

**Issue by DreamFerry** [seatonjiang/kratos#185]
RT
话不多说，打赏安排
![20180820111812_49881](https://user-images.githubusercontent.com/41297263/76722308-f8be1080-677d-11ea-89b1-bc2fba3dfd1f.jpg)

**Comment by seatonjiang** [comment]
pjax 没有开发计划

**Comment by DreamFerry** [comment]
> pjax没有开发计划

没有计划后续也可以考虑安排，pjax无刷新显示有很多妙用。另外，如果登录状态可以采用ajax拉取就好了，这样子就能够实现全站静态化而不缓存登录状态

**Comment by ohotto** [comment]
一人血书

**Comment by wencaizhang** [comment]
@XMD0718 

可以在主题目录下的 `custom` 目录中自行实现，只需贴几行代码即可，具体代码如下：

1. 第一步，将下面代码粘贴到 `custom/custom.php` 文件中

```php
<?php
// 请在第三行开始编写代码

// pjax 资源加载
function theme_autoload_pjax()
{
    if (!is_admin()) {
        // css
        wp_enqueue_style('nprogress', '//cdn.bootcss.com/nprogress/0.2.0/nprogress.min.css', array(), '0.2.0');
        // js
        wp_enqueue_script('pjax', '//cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js', array(), '2.0.1', false);
        wp_enqueue_script('nprogress', '//cdn.bootcss.com/nprogress/0.2.0/nprogress.min.js', array(), '0.2.0', false);
    }
}
add_action('wp_enqueue_scripts', 'theme_autoload_pjax');
```
ps: 这里用到的 css 和 js 文件，使用了 [BootCDN](https://www.bootcdn.cn/) 的资源，可以改为自己网站的资源地址或者其他 cdn 地址。

2. 将下面代码粘贴到 `custom/custom.js` 文件中

```js
;
// 请在第三行开始编写代码
$(function () {
  $(document).pjax('a', 'body', { fragment: 'body' });
  $(document).on('pjax:send', function () {
    NProgress.start();
  })
  $(document).on('pjax:complete', function () {
    NProgress.done();

    loadThemeJs()
    if (typeof Prism !== 'undefined') {
      // 代码高亮
      Prism.highlightAll();
    }
  })

  $.ajaxSetup({
    cache: true
  });
  getThemeJsSrc();
  function getThemeJsSrc () {
    // 获取本站 kratos.min.js 文件地址
    if (!$.kratosjs) {
      $('script').each(function () {
        var src = $(this).attr('src') || ''
        if (src.indexOf( 'kratos.min.js' ) >= 0) {
          $.kratosjs = src
          return false;
        }
      })
    }
  }
  function loadThemeJs () {
    var url = $.kratosjs || 'https://n3.cdn.vtrois.com/kratos/3.0.9/assets/js/kratos.min.js'
    $.getScript( url ).done(function( script, textStatus ) {
      console.log( textStatus );
    });
  }
})
```

这里在 pjax 加载完成之后，做了两件事：
1. 重新加载主题脚本 `kratos.min.js` ，由于主题贴心地提供了 CDN 选项，所以这里为了和 WP 网站保持一致，是通过 jquery 来获取当前网站使用  `kratos.min.js` 的真实地址，另外把猫云 CDN 地址作为缺省值
2. 执行 Prism 高亮代码块的函数

解释一下：
1. 重新加载主题脚本 `kratos.min.js` 是因为在网页加载完成之后， `kratos.min.js` 对页面中的按钮（评论区表情、打赏、点赞等按钮）绑定了点击事件，使用 pjax 之后通过重新加载的方式来重新绑定事件（如果  `kratos.min.js` 使用事件代理则无需重新加载），但是因为浏览器缓存的缘故，所以重新加载 JS 文件的成本可以忽略不计。
2. Prism 是我个人一个在用的代码高亮插件，放在这里是作为一个参考，即一部分插件需要在页面加载完成之后初始化一下（或执行一些代码，如 `kratos.min.js`），那就需要在 pajax 完成之后手动执行一次。请根据自己网站情况选择保留或者删除。

**Comment by DreamFerry** [comment]
@wencaizhang 刚测试了一下，加载仍然需要刷新啊

**Comment by wencaizhang** [comment]
@XMD0718 

> 刚测试了一下，加载仍然需要刷新啊

可以先检测 pjax 相关代码是否已经生效，有可能是缓存导致的没有访问到最新页面，我自己的网站没问题，地址：http://101.201.57.17/

**Comment by wencaizhang** [comment]
@XMD0718 
`custom/custom.js` 代码所有改进，请参照 https://github.com/Vtrois/Kratos/issues/185#issuecomment-622410520

**Comment by DreamFerry** [comment]
@wencaizhang 你好，经重新部署，PJAX加载的问题已解决。请问代码高亮具体要怎么操作呢？

**Comment by wencaizhang** [comment]
@XMD0718 
> 请问代码高亮具体要怎么操作呢？

不清楚你的具体情况是什么，我猜可能是这两种情况：
1. 原来就没有代码高亮，现在想加入这个功能，那么可以使用 [Prism.js](https://prismjs.com/)。然后参考 2
2. 原来就可以代码高亮，现在没有了，有可能是因为代码高亮插件需要在页面完成加载的时候初始化，这种情况需要在 pjax 加载完成的时候重新初始化一次，以 Prism 为例，代码如下：

```js
  $(document).on('pjax:complete', function () {
    NProgress.done();

    if (typeof Prism !== 'undefined') {
      // 代码高亮
      Prism.highlightAll();
    }
  })
```

**Comment by DreamFerry** [comment]
@wencaizhang 我是原本没有代码高亮但想要增加代码高亮的，关于这点我在另一条[issue](https://github.com/Vtrois/Kratos/issues/179)有提到。Prism.js我以前有了解过，但是它必须要严格按照`“<pre class="language-XXX"><code class="language-XXX">你要贴的代码</code></pre>”`的格式才可以，这在编写文章时还是比较麻烦的，还有就是旧文章的代码部分要重新修改很麻烦。
非常感谢你的回复，老哥太给力了

**Comment by wencaizhang** [comment]
@XMD0718 
是的，插件要根据 `language-XXX` 来判断代码块属于哪种编程语言，进而分析出代码块中每个单词的类型（关键字、注释、字符串、布尔值等等），不同类型会有不同的字体颜色，从而实现高亮。

如果是格式简单的文章，可以了解一下 Markdown ，用来写技术文章还是很方便的，我用的 MarkDown 编辑器插件叫做 `WP Editor.md`，有时间可以尝试一下。

**Comment by iamlvtu** [comment]
@wencaizhang 大神，你的网站咋打不开呢？

**Comment by DreamFerry** [comment]
@wencaizhang 老哥最近还活跃吗？我有个一直没有解决的关于pjax导致点击事件失效的问题，还请老哥帮我排查一下，多谢了
custom.js内容如下：
```
;
// 请在第三行开始编写代码
$(function () {
  $(document).pjax('a', 'body', { fragment: 'body' });
  $(document).on('pjax:send', function () {
    NProgress.start();
  })
  $(document).on('pjax:complete', function () {
    NProgress.done();
  })

  $.ajaxSetup({
    cache: true
  });
  getThemeJsSrc();
  function getThemeJsSrc () {
    // 获取本站 kratos.min.js 文件地址
    if (!$.kratosjs) {
      $('script').each(function () {
        var src = $(this).attr('src') || ''
        if (src.indexOf( 'kratos.min.js' ) >= 0) {
          $.kratosjs = src
          return false;
        }
      })
    }
  }
  function loadThemeJs () {
    var url = $.kratosjs || 'https://cdn.jsdelivr.net/gh/vtrois/kratos@3.0.10/assets/js/kratos.min.js'
    $.getScript( url ).done(function( script, textStatus ) {
      console.log( textStatus );
    });
  }
})
```
出现问题的博客网址：https://www.xunmengdu.com
问题详情：通过pjax加载文章后，上方的下拉菜单栏将失效（如文章、子站），文章下方的打赏按钮也会失效。
另外，有时候在pjax加载后，仍会重新刷新网页，不知道是哪里出现了问题导致了这种情况的出现。

**Comment by wencaizhang** [comment]
@iamlvtu 网站地址：[https://webjam.cn](https://webjam.cn/) ，欢迎访问啊 :)

**Comment by wencaizhang** [comment]
@XMD0718 

你说的问题我在后续使用中也发现了，前面的代码只能大致实现 pjax 功能，但是页面中的细节功能需要逐一处理，如果你有时间和精力，并且对前端技术有一定了解，可以按照这个思路自行实现，否则不再建议使用上面代码，抱歉。

另外说一下 pjax，我觉得在这里使用 pjax 唯一的好处可能是页面跳转时视觉效果更好了，实际上对网页加载速度并无优化，这是因为静态文件（ css 和 js ）会自动被浏览器缓存到内存或硬盘中，再次加载耗费的时间几乎可以忽略不计。

如果你非常希望能用上 pjax 功能，可以看下这个项目：[xb2016/kratos-pjax](https://github.com/xb2016/kratos-pjax) ，基于 kratos 二次开发，同时加入了 pjax 功能，希望能够满足你的需求。

**Comment by DreamFerry** [comment]
@wencaizhang 

事实上，[xb2016/kratos-pjax](https://github.com/xb2016/kratos-pjax) 是我最初使用的主题，该主题部分地方的确做得很好，特别是视觉效果方面。但该主题在后期使用过程中发现存在一些问题，一是较为臃肿，二是主题作者的部分优化阉割了WP的部分功能，导致部分插件在使用过程中会出现问题，三是该主题与作者的API进行了连接，若作者单方面决定暂停服务，可能会导致主题突然不可用，这些不可控因素是我不能接受的，所以后来我舍弃了kratos-pjax主题很好看的视觉效果，转而使用不断进步的原生的Kratos主题。

我这个issue提出后，Kratos作者虽然表示近期没有计划和精力，但既然没有关闭这个issue，说明未来还是会支持的，只是时间问题而已。最后，感谢一下老哥的帮助，虽然pjax的实现有些不完美之处，但也是部分解决了我的需求了。打扰老哥了。

**Comment by wencaizhang** [comment]
@XMD0718 原来如此。期待作者早日实现 pjax 功能。

**Comment by seatonjiang** [comment]
Issues 功能即将关闭，请转移到 Discussions 继续讨论，https://github.com/vtrois/kratos/discussions

**Comment by n0099** [comment]
分享一下我目前在子主题中使用pjax的js配置：
```js
if (window.Pjax !== undefined) {
    window.pjax = new Pjax({
        elements: '.k-header a, .k-main a:not(.post-edit-link), .k-footer a',
        selectors: [
            '.k-main',
            '.introduce',
            'title',
            'meta[name=keywords]',
            'meta[name=description]',
            'meta[itemprop=image]',
            'meta[property="og:url"]',
            'meta[property="og:title"]',
            'meta[property="og:image"]',
            // 'meta[property="og:article:tag"]', // this tag might occurs more than one time
            'meta[property="twitter:title"]',
            'meta[property="twitter:creator"]',
            'script#kratos-js-extra'
        ],
        scrollTo: 330,
        cacheBust: false,
        debug: false,
        analytics: () => {
            // 没有使用google analytics的请删除这个analytics成员
            gtag('event', 'page_view', {
                page_title: document.title,
                page_location: window.location.href,
                page_path: window.location.pathname
            });
        }
    });
    document.addEventListener('pjax:complete', () => {
        document.dispatchEvent(new Event('DOMContentLoaded', { bubbles: true }));
        document.dispatchEvent(new Event('load', { bubbles: true }));
        window.dispatchEvent(new Event('load'));
    });
}
```
#516 #540
