### ISSUE TITLE
连续添加的图片贴合在一起

### ISSUE THREAD

**Issue by ziyooren** [seatonjiang/kratos#187]
**问题描述**

假设post内有多张图片是连续添加的，这些图片会紧紧贴在一起，很不美观。示例页面：[https://www.pcoic.com/system/windows/942.html](https://www.pcoic.com/system/windows/942.html) 

![image](https://user-images.githubusercontent.com/37561090/76741552-b101ae00-67aa-11ea-836c-89dd3c7c74bf.png)

**环境信息**

PHP 版本：7.2.28
Kratos 版本：3.0.6
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

**复现步奏**

新建文章，连续添加多张图片。

**Comment by seatonjiang** [comment]
图片之间手动添加回车

**Comment by ziyooren** [comment]
> 图片之间手动添加回车

好的👌
