### ISSUE TITLE
怎么升级才不会影响更改的配置文件等等

### ISSUE THREAD

**Issue by kylin-kai** [seatonjiang/kratos#188]
**问题描述**

（请图文并茂的描述一下具体问题，截图可以直接 Ctrl + V 进行粘贴）

**环境信息**

（将主题设置—>关于主题中的「基础信息」内容粘贴到这里）

**复现步奏**

（请分步描述复现这个问题的步骤）

**Comment by seatonjiang** [comment]
2.8 升级 3.0 会丢失配置信息，这个由于修改了配置名称导致的，需要自己备份好配置信息，3.0 之后的版本升级不会丢失配置，后台自动升级不是覆盖升级，而是下载新版本->删除旧版本（需要 theme 目录有足够的权限），所以如果你自己修改了主题文件，需要自行备份。3.0 版本之后建议将自己修改的内容统一放到 custom 目录，之后仅备份此目录内容即可，主题配置不会因升级而丢失。
