### ISSUE TITLE
侧边栏小工具随动功能

### ISSUE THREAD

**Issue by kylin-kai** [seatonjiang/kratos#189]
2.8有侧边栏小工具随动功能 为什么版本现在没有了  建议加上

**Comment by seatonjiang** [comment]
目前来看随动会产生很多无法修复的问题，所以暂时不考虑新增。

**Comment by kylin-kai** [comment]
之前好多功能现在好像都没了,比如说分享的按钮,建议之前有的尽量升级了可以加入,还有一个bug顶部按钮在火狐不显示,谷歌可以

**Comment by SuperNG6** [comment]
可否把近期评论功能加回来？我觉得这个功能很实用啊

**Comment by iamlvtu** [comment]
和我一样，喜欢之前版本的那些功能就坚持用之前的版本，然后自己再改改。。。哈哈～～

**Comment by seatonjiang** [comment]
侧边栏随动不准备新增，近期评论功能已经加进来了，新版本中会推送。
