### ISSUE TITLE
引导页

### ISSUE THREAD

**Issue by iamlvtu** [seatonjiang/kratos#190]
大神，这个主题新的版本咋把那个引导页给干掉了，主题设置里面也没有。
感觉旧的版本里有这个页面非常好！
如：https://www.wanghao.me 首页

最后想问下你的网站为啥不开呢？？？ :-((((((

谢谢！

**Comment by seatonjiang** [comment]
落地页后期会加的，暂时没用更新计划。官网近期上线。

**Comment by iamlvtu** [comment]
谢谢三哥～～～
