### ISSUE TITLE
建议首页特殊图片功能建议新增正方形

### ISSUE THREAD

**Issue by 2523955396** [seatonjiang/kratos#192]
首页特殊图片功能是长方形的，但是我之前用的主题都是用的正方形的logo图，换到这个主题的话就是长方形的logo图会把之前的正方形logo图拉宽

**Comment by chankenjio** [comment]
自己修改下不就行了

**Comment by seatonjiang** [comment]
自己在 custom/custom.css 中添加样式即可，主题从 2016 年至今都是固定比例的特色图。
