### ISSUE TITLE
手机图片排版问题

### ISSUE THREAD

**Issue by 2523955396** [seatonjiang/kratos#194]
**问题描述**

（请图文并茂的描述一下具体问题，截图可以直接 Ctrl + V 进行粘贴）
编辑时是这样的
![image](https://user-images.githubusercontent.com/44113373/77221690-e6314600-6b86-11ea-95ba-5d17b2a5774d.png)
发布后是这样的
![image](https://user-images.githubusercontent.com/44113373/77221664-a10d1400-6b86-11ea-9c12-40e1a68cc9f2.png)
手机图片横排

**环境信息**

（将主题设置—>关于主题中的「基础信息」内容粘贴到这里）

**复现步奏**

（请分步描述复现这个问题的步骤）

**Comment by seatonjiang** [comment]
由于插入图片的方法有好多种，为了平衡所有的方式，现在采用的是每张图片是一个块元素，会独占一行，看你想并排显示，建议可以把图片合并成一张大图来展示。
