### ISSUE TITLE
代码第一行与后面无法对齐

### ISSUE THREAD

**Issue by starshine98** [seatonjiang/kratos#195]
**问题描述**

此处为编辑器
![image](https://user-images.githubusercontent.com/57817807/77321477-36f29b80-6d4d-11ea-9af6-b91124ac5913.png)
此处为文章
![image](https://user-images.githubusercontent.com/57817807/77321491-3ce87c80-6d4d-11ea-874d-8a8c6019a709.png)

第二行开始  都和第一行差一个空格

**环境信息**

PHP 版本：7.2.26
Kratos 版本：3.0.7
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**Comment by seatonjiang** [comment]
问题已经修复，等新版本推送即可。

![image](https://user-images.githubusercontent.com/57834639/78424910-4655db00-76a3-11ea-964c-0e14d6d0650f.png)
