### ISSUE TITLE
请问如何添加自定义表情

### ISSUE THREAD

**Issue by IveTian** [seatonjiang/kratos#197]
**问题描述**
请问该如何添加自定义.png表情？
**环境信息**
PHP 版本：7.3.0
Kratos 版本：3.0.7
WordPress 版本：4.8.12
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36 Edg/80.0.361.69

**Comment by seatonjiang** [comment]
1. 将表情放到 assets\img\smilies 目录。
2. 找到 inc\theme-article.php 中的 smilies_reset 方法，把表情名称以及对应的简写按照上面的规则添加一行。
3. 找到 pages\page-smilies.php ，根据上面写的规则添加一行。
