### ISSUE TITLE
评论无头像显示，且点击回复并不会回复当前评论

### ISSUE THREAD

**Issue by alpha87** [seatonjiang/kratos#198]
**问题描述**

1. 评论没有头像显示，是 bug 还是以后也不会增加了？
2. 点击**回复**按钮并不会回复当前评论，而是创建新评论，必须在后台回复才能成为评论的子评论。

**环境信息**

PHP 版本：7.0.33-0ubuntu0.16.04.12
Kratos 版本：3.0.7
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**复现步奏**

点击已评论的回复即可复现。

**Comment by seatonjiang** [comment]
我这里测试正常的啊，回复评论的位置是有一个小位移来体现的。

![image](https://user-images.githubusercontent.com/57834639/78450425-1281b200-76b1-11ea-9b2e-ae7798f96238.png)

**Comment by wkingnet** [comment]
头像用的是gravatar网站的，你是不是没去gravatar网站注册？注册以后留言的时候邮箱和gravatar一致就显示头像了

**Comment by yenyoong99** [comment]
![image](https://user-images.githubusercontent.com/23697812/80473435-b856d280-8978-11ea-9e43-7fe0d5354531.png)

在设置--》讨论--》头像 改为默认就可以了，如果是Wordpress其他的头像就会出现空白的情况。如果有gravatar的头像则不受影响。

**Comment by seatonjiang** [comment]
![image](https://user-images.githubusercontent.com/57834639/83330868-a7291a80-a2c4-11ea-83a5-5335c903dc76.png)
问题解决了，并且增强了回复关系
