### ISSUE TITLE
视频无法显示

### ISSUE THREAD

**Issue by miguangxian** [seatonjiang/kratos#199]
**问题描述**
转载过来的优酷、腾讯、哔哩哔哩等视频站点的视频，发布后只显示视频链接
这个问题在其它模板中没有发现。
能否修正一下，谢谢
后台显示的交流群号，申请加入失败

PHP 版本：7.3.11
Kratos 版本：3.0.7
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

**Comment by seatonjiang** [comment]
Kratos 主题默认支持腾讯视频、哔哩哔哩、YouTube的视频插入，需要使用短代码。

![image](https://user-images.githubusercontent.com/57834639/78450275-1234e700-76b0-11ea-9bbf-58eb857be2a9.png)

![image](https://user-images.githubusercontent.com/57834639/78450278-1c56e580-76b0-11ea-8e55-62cc9da3f4e6.png)

QQ交流群：734508

微信交流群

![image](https://user-images.githubusercontent.com/57834639/78450341-7e174f80-76b0-11ea-9588-5581b7cb23eb.png)
