### ISSUE TITLE
3.0电脑端表格列宽问题

### ISSUE THREAD

**Issue by SWAHZX** [seatonjiang/kratos#200]
**问题描述**
3.0版本，在文章或页面插入TablePress制作的表格时，表格的列宽是是各列平均，而不是按单元格内容适应列宽。
不知能否让表格按照单元格内容适应列宽，或者像移动端一样，在最下方显示滚动条。

**环境信息**

PHP 版本：7.3.16
Kratos 版本：3.0.7
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**Comment by seatonjiang** [comment]
之前是自适应的，但是会因为字数过长导致表格样式溢出，所以目前找到的兼容性解决方法就是这样。

**Comment by iamlvtu** [comment]
表格增加一个class项，然后CSS定义。。。。

**Comment by seatonjiang** [comment]
目前新版本已经对表格显示做了优化，可以体验试一下。
