### ISSUE TITLE
手机访问时侧边栏内容全都不显示

### ISSUE THREAD

**Issue by miguangxian** [seatonjiang/kratos#201]
在PC端显示的内容，用手机浏览器或者微信端浏览站点时，完全不显示，不知道这是否是有意设计成这样的，如果是，能否增加一个开关，用来控制在手机端显示

PHP 版本：7.3.11
Kratos 版本：3.0.7
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

**Comment by seatonjiang** [comment]
你是指小工具在移动端无法正常访问是吗？移动端有些内容是去掉的，为了简化显示内容，增强用户阅读体验，所以才这么做，右侧的小工具比较重要的部分都放在正文下放了，如果还有什么其他需求，可以提出来，做下评估看一下是不是需要新增功能。

**Comment by miguangxian** [comment]
哦，明白了。还有，视频是不能播放的，就是转载的视频。对文字设定的颜色，也不能正确显示，只是显示黑色。
















在 2020-04-04 09:24:56，"Seaton Jiang" <notifications@github.com> 写道：

你是指小工具在移动端无法正常访问是吗？移动端有些内容是去掉的，为了简化显示内容，增强用户阅读体验，所以才这么做，右侧的小工具比较重要的部分都放在正文下放了，如果还有什么其他需求，可以提出来，做下评估看一下是不是需要新增功能。

**Comment by seatonjiang** [comment]
Kratos 主题默认支持腾讯视频、哔哩哔哩、YouTube的视频插入，需要使用短代码。

![image](https://user-images.githubusercontent.com/57834639/78450275-1234e700-76b0-11ea-9bbf-58eb857be2a9.png)

![image](https://user-images.githubusercontent.com/57834639/78450278-1c56e580-76b0-11ea-8e55-62cc9da3f4e6.png)
