### ISSUE TITLE
页脚网站访问404

### ISSUE THREAD

**Issue by InfiniteZh** [seatonjiang/kratos#203]
**问题描述**

页脚处版权信息的THEME KRATOS MADE BY VTROIS，VTROIS网站访问404

**环境信息**

PHP 版本：5.6.40
Kratos 版本：3.0.7
WordPress 版本：5.4
用户代理信息：Mozilla / 5.0（Windows NT 10.0; Win64; x64）AppleWebKit / 537.36（KHTML，例如Gecko）Chrome / 80.0.3987.163 Safari / 537.36

**复现步奏**

页脚点击VTROIS

**Comment by seatonjiang** [comment]
目前官网正在灰度测试，待测试完成之后就可以访问了，感谢支持。
