### ISSUE TITLE
Page页面模版 Keywords 和 Description 设置

### ISSUE THREAD

**Issue by iamlvtu** [seatonjiang/kratos#204]
三哥，貌似主题中新建页面Meta中Description无内容，另外Keywords中只有页面名称和网站名称，并且这两个是连在一起的，就是当前页面title，但没有用符号分开。
`
  | <title>B - A</title><meta name="keywords" content="BA"><meta name="description" itemprop="description" content="">
`
谢谢三哥！！！

**Comment by seatonjiang** [comment]
文章以及页面编辑页面均新增了一个『SEO 设置』的功能，并且修改了 Keywords 和 Description 的配置优先级，下面是优先级介绍，该功能将在 3.0.11 版本中推送。

优先级介绍：
1、在主页将显示『主题设置 -> 收录配置』中配置的站点描述 及 关键词的内容。
2、在文章中 Description 优先显示『SEO 设置』的内容，如果没有配置，将获取摘要中的内容，如果没有配置摘要，将自动拉取文章前 200 个字。Keywords 优先显示『SEO 设置』的内容，如果没有配置，将获取标签中的内容。
3、在页面中 Description 优先显示『SEO 设置』的内容，如果没有配置，将显示『主题设置 -> 收录配置』中配置的内容。Keywords 优先显示『SEO 设置』的内容，如果没有配置，将显示『主题设置 -> 收录配置』中配置的内容。
4、在分类中 Description 『文章 -> 分类目录』中的描述内容。
5、在标签中 Description 『文章 -> 标签』中的描述内容。

![image](https://user-images.githubusercontent.com/57834639/84560924-dd61a200-ad7a-11ea-8c64-bd8e817ae443.png)
![image](https://user-images.githubusercontent.com/57834639/84560947-1b5ec600-ad7b-11ea-94e4-f423048ec019.png)

**Comment by iamlvtu** [comment]
谢谢三哥，我用的还是你的2.x版本的主题，哈哈～～
