### ISSUE TITLE
文章列表不显示特色图片

### ISSUE THREAD

**Issue by buyi1net** [seatonjiang/kratos#205]
**问题描述**
![image](https://user-images.githubusercontent.com/61647517/78602721-8080d180-7889-11ea-8360-6724d2ac610e.png)

![image](https://user-images.githubusercontent.com/61647517/78602624-57604100-7889-11ea-8358-9fd9aa93a6a1.png)

**环境信息**

PHP 版本：7.2.28
Kratos 版本：3.0.8
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

**复现步奏**

不知道是不是主题的原因。暂时没有找到关于特色图片的特殊设置。请验证一下此问题。

**Comment by iamlvtu** [comment]
`add_theme_support( 'post-thumbnails' ); `

**Comment by seatonjiang** [comment]
主题设置 - 首页配置 - 特色图片  看一下是否关了
![image](https://user-images.githubusercontent.com/57834639/78754580-4e1ac580-79aa-11ea-8c53-59c0bf70c076.png)
