### ISSUE TITLE
静态资源加速jsDelivr开启了怎么用？

### ISSUE THREAD

**Issue by 24021438** [seatonjiang/kratos#206]
之前发帖子都是pigo配合jsDelivr来手动生成cdn图片地址，这个选项开启了之后怎么用？

**Comment by 24021438** [comment]
![cdn](https://user-images.githubusercontent.com/56147487/78952339-d367bc80-7b07-11ea-927f-a3da23a9b303.png)

**Comment by seatonjiang** [comment]
CDN 加速的资源目前是 css 和 js，近期将默认的图片也会放到加速里面

**Comment by seatonjiang** [comment]
如果需要加速文章的图片，还得配合插件实现，主题仅实现主题资源的加速
