### ISSUE TITLE
主页about-background.png能不能自定义

### ISSUE THREAD

**Issue by Nicotinamide** [seatonjiang/kratos#207]
**问题描述**

主页about-background.png能不能自定义

我想把这张图片放在图床上，但是我在没法在代码里找到它，修改它。

**Comment by seatonjiang** [comment]
直接替换地址即可，目前已经优化，将默认使用 CDN 加速图片资源。

https://cdn.jsdelivr.net/gh/vtrois/kratos@3.0.8/
https://n3.cdn.vtrois.com/kratos/3.0.8/

![image](https://user-images.githubusercontent.com/57834639/79057635-f7590880-7c95-11ea-95e8-43c3203f9986.png)

**Comment by Nicotinamide** [comment]
> 直接替换地址即可，目前已经优化，将默认使用 CDN 加速图片资源。
> 
> https://cdn.jsdelivr.net/gh/vtrois/kratos@3.0.8/
> https://n3.cdn.vtrois.com/kratos/3.0.8/
> 
> ![image](https://user-images.githubusercontent.com/57834639/79057635-f7590880-7c95-11ea-95e8-43c3203f9986.png)
![image](https://s1.ax1x.com/2020/04/12/Gq4o1s.png)
这个图片可不可以更换，我希望把它放在oss上
