### ISSUE TITLE
可否考虑添加滚动屏幕侧边栏小工具浮动功能？

### ISSUE THREAD

**Issue by wkingnet** [seatonjiang/kratos#208]
由于有些文章篇幅较长，会引入标题功能和目录插件。然后希望在文章向下滚动时，在屏幕右侧侧边栏小工具的位置，有一个浮动的文章目录，这样阅读会很方便，网站感觉也专业。

文章目录可以有插件生成，但浮动小工具因为牵扯到CSS，只能寄希望于kratos可以添加此功能

**Comment by seatonjiang** [comment]
问题统一在 #121 中解决

**Comment by iamlvtu** [comment]
旧版的有这个功能，但好像被我改着改没有了。。。
