### ISSUE TITLE
关于页面宽度

### ISSUE THREAD

**Issue by Clownce** [seatonjiang/kratos#210]
PC浏览器访问，页面两端是大片空白，这么做可能是为了排版好看点，但是感觉中间内容宽度还是太小了，特别是贴了代码之后，一行显示不全很难受，记得以前右侧小工具可以在文章页面不显示的；宽度不好改的话，至少希望点进文章后可以隐藏小工具，跪求大佬支持一下。

**Comment by wkingnet** [comment]
宽度的话临时修改方法：你可以在自定义额外CSS里加一句 .container{max-width:70%}  比例自己调。

侧边小工具你可以试用Custom Sidebars插件来定制首页、文章、页面页，显示不同或隐藏小工具。

**Comment by MrSeaning** [comment]
或者在自定义的css里加入它也行 @media (min-width: 1320px){
.container {
    max-width: 1320px;
	}
}

**Comment by seatonjiang** [comment]
新增了页面布局功能，等更新即可

![image](https://user-images.githubusercontent.com/57834639/83994819-11f3e900-a98a-11ea-8aa1-d46636f034c8.png)

![image](https://user-images.githubusercontent.com/57834639/83994822-14564300-a98a-11ea-99e8-a8d0a77bac44.png)

![image](https://user-images.githubusercontent.com/57834639/83994829-17513380-a98a-11ea-9568-4329d8c2acf1.png)
