### ISSUE TITLE
xx

### ISSUE THREAD

**Issue by MrSeaning** [seatonjiang/kratos#211]
**问题描述**

wordpress私密文章也会显示在首页列表中

**环境信息**

wordpress版本5.4

**复现步奏**
文章设置为私密，列表能显示

**Comment by yenyoong99** [comment]
我的改为私密是没有显示，但是如果是保密（需要输入密码）的文章就会显示出来。

**Comment by cokemine** [comment]
怕是登录了Admin？开无痕也这样？
