### ISSUE TITLE
菜单栏分级问题

### ISSUE THREAD

**Issue by yenyoong99** [seatonjiang/kratos#212]
**问题描述**

版本更新后，菜单栏显示不出三级菜单

![image](https://user-images.githubusercontent.com/23697812/80376127-f1853900-88cb-11ea-9b4e-ddcddb59e0e0.png)

原本的三级菜单栏是这样的：

![image](https://user-images.githubusercontent.com/23697812/80376769-e252bb00-88cc-11ea-9821-219162226f00.png)

文章分类路径只显示到二级子项目，三级子项目没有显示：

![image](https://user-images.githubusercontent.com/23697812/80378916-f21fce80-88cf-11ea-874e-9a9b2da34ca0.png)

有设置三级子项目，但是没法显示，设置如下：

![image](https://user-images.githubusercontent.com/23697812/80379062-2a271180-88d0-11ea-9d5f-334e60824fa9.png)

PHP 版本：7.3.3
Kratos 版本：3.0.9
WordPress 版本：5.4
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36

麻烦你看看是什么问题，谢谢你

**Comment by yenyoong99** [comment]
显示不出3级菜单栏

**Comment by yenyoong99** [comment]
![image](https://user-images.githubusercontent.com/23697812/80472864-e2f45b80-8977-11ea-8271-391f46242131.png)
请问这些功能有什么用吗？如果能全局自定义文章字型应该会更好。

最近我使用了MarkDown 插件，H1/H2那些标题字型感觉都不太好看。

谢谢。😁

**Comment by iamlvtu** [comment]
貌似新版主题不支持三级。
CSS动画效果和图标字体，肯定有用呀，不了解可以问下度娘。。。。

**Comment by seatonjiang** [comment]
面包屑导航不显示父级的问题已经修复了，新版本中推送。

菜单栏目前仅支持2级菜单，暂时不做多级菜单支持。

CSS 动画库可以自定义效果，目前应用到了标题介绍上升的一个效果， font awesome 是一个图标库，可以在菜单栏中调用。

![image](https://user-images.githubusercontent.com/57834639/83994678-b88bba00-a989-11ea-8428-2c6eec7850e7.png)


![image](https://user-images.githubusercontent.com/57834639/83994577-68acf300-a989-11ea-830f-4791127df9cc.png)

![image](https://user-images.githubusercontent.com/57834639/83994534-4b782480-a989-11ea-8171-ec97bbd23a75.png)
