### ISSUE TITLE
vtrois.com打不开了，自定义函数怎么用呀？

### ISSUE THREAD

**Issue by yjl118** [seatonjiang/kratos#214]
**问题描述**

请仔细描述一下遇到的问题，截图可以直接 Ctrl + V 上传。

**环境信息**

将主题设置—>关于主题中「基础信息」的内容粘贴到这里。

**复现步奏**

请分步描述复现这个问题的步骤。

**Comment by seatonjiang** [comment]
官网暂时还没有开放，wp的自定义函数你可以自己在function里面写
