### ISSUE TITLE
请问首页文章列表能否修改一下样式，图片缩小，标题加宽？

### ISSUE THREAD

**Issue by wkingnet** [seatonjiang/kratos#215]
![QQ截图20200501164148](https://user-images.githubusercontent.com/57652989/80793866-e16ea180-8bca-11ea-873c-1fa34a77e48c.png)

现在的样式如图，左边图片占用了过大的空间，导致文章标题显示的很少。请问能否修改一下样式，让标题占用一整行，图片适当缩小剪裁和文章简介文字对齐，感谢

**Comment by MrSeaning** [comment]
这个自己在custom.css里写样式就行了啊

**Comment by wkingnet** [comment]
> 这个自己在custom.css里写样式就行了啊

所以问题就是我不会写。。。

**Comment by MrSeaning** [comment]
.k-main .board .article-panel .a-thumb{width:100px;height:200px;} /*100是宽度，200是高度，自己改*/
.k-main .board .article-panel .a-post{margin-left:195px;}/*195是距左侧的距离，越大越往右，自己改*/大概就是这样

**Comment by wkingnet** [comment]
> .k-main .board .article-panel .a-thumb{width:100px;height:200px;} /_100是宽度，200是高度，自己改_/
> .k-main .board .article-panel .a-post{margin-left:195px;}/_195是距左侧的距离，越大越往右，自己改_/大概就是这样

按你说的修改了，图片大小能调整，但margin-left:195px改动无效，标题不会往左移动占满一整行

**Comment by MrSeaning** [comment]
你网址是啥，我帮你调下

**Comment by wkingnet** [comment]
> 你网址是啥，我帮你调下

http://blog.wkings.net

感谢大佬！

**Comment by iamlvtu** [comment]
在你的CSS文件中修改这个：
.container {
max-width: 61.8%;
}
61.8%真的太窄了，改大点。。。。

**Comment by seatonjiang** [comment]
主题起到一个模板作用，准备的 custom 文件是为了用户自定义修改的。

**Comment by seatonjiang** [comment]
文章这里进行了优化（图片和文章内容以及标题长度），新版本将在近期推送。

![image](https://user-images.githubusercontent.com/57834639/102046441-51f2c780-3e16-11eb-95af-f75e93ed0bd8.png)
