### ISSUE TITLE
<!–nextpage–>分页样式问题

### ISSUE THREAD

**Issue by SWAHZX** [seatonjiang/kratos#216]
[**问题描述**]

使用<!–nextpage–>分页，如果分页过多，页码需要换行显示时，分页样式有异常。
![nextpage](https://user-images.githubusercontent.com/46831343/80947821-87b4e400-8e23-11ea-9185-62d497d23a85.jpg)

**环境信息**

PHP 版本：7.3.17
Kratos 版本：3.0.9
WordPress 版本：5.4.1
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36

**Comment by seatonjiang** [comment]
收到问题，正在调整优化

**Comment by seatonjiang** [comment]
问题已经修复了，将在新版本中推送，建议还是不要超过 13 页，超过了就分文章吧，不要分页了。

![image](https://user-images.githubusercontent.com/57834639/102050504-f62c3c80-3e1d-11eb-9e6d-7704e0882f58.png)
![image](https://user-images.githubusercontent.com/57834639/102050534-ffb5a480-3e1d-11eb-8e7c-f29753ede37a.png)
