### ISSUE TITLE
文章的下方能否顯示作者本人的信息呢

### ISSUE THREAD

**Issue by MoConWu** [seatonjiang/kratos#217]
**问题描述**

文章的下方顯示的站長信息，能否顯示作者本人的信息呢？
不然每個文章顯示的都是站長信息，看起來還以為都是站長寫的文章呢
就是最底部 点赞 那个地方，显示的应该是作者而不是站长

**Comment by iamlvtu** [comment]
pages/page-toolbar.php 检查这个文件。。。

**Comment by seatonjiang** [comment]
Kratos 3.x 版本的定位是个人博客，如果是多人共同维护，建议自行修改 `pages/page-toolbar.php`

参考方法
get_the_author_meta
https://developer.wordpress.org/reference/functions/get_the_author_meta/

```
global $post;
$author_id = $post->post_author;

// 昵称
get_the_author_meta( 'nicename', $author_id );
 
// 简介
get_the_author_meta( 'user_description', $author_id );

// 头像
get_avatar( get_the_author_meta( $author_id ) )
```

**Comment by MoConWu** [comment]
thanks
