### ISSUE TITLE
更换主题后 首页没问题，文章页有错误

### ISSUE THREAD

**Issue by alexinmel** [seatonjiang/kratos#218]
首页
![image](https://user-images.githubusercontent.com/62312926/81796333-a700ef00-9550-11ea-9aa7-3b036e36cb9f.png)
文章页
![image](https://user-images.githubusercontent.com/62312926/81796098-5093b080-9550-11ea-8ae3-a39126aeb57d.png)

不知道问题出在哪 请大佬帮忙

**Comment by alexinmel** [comment]
很喜欢这个主题 就是这个错误不知道哪里调整

**Comment by iamlvtu** [comment]
发个链接可能更容易看到你的问题？

**Comment by seatonjiang** [comment]
问题解决了吗？

**Comment by alexinmel** [comment]
有个插件冲突 禁用后 问题解决了
