### ISSUE TITLE
希望作者能加些功能，比如文章页可以有隐藏侧边栏，将文章页面扩大的功能，目前文章空间过小。感谢作者的辛苦努力

### ISSUE THREAD

**Issue by dreamyt** [seatonjiang/kratos#219]
**问题描述**

请仔细描述一下遇到的问题，截图可以直接 Ctrl + V 上传。

**环境信息**

将主题设置—>关于主题中「基础信息」的内容粘贴到这里。

**复现步奏**

请分步描述复现这个问题的步骤。

**Comment by MrSeaning** [comment]
自己可以在costom.js中自己写一下

**Comment by iamlvtu** [comment]
这些个性化的东西可以自己折腾呀。。。

**Comment by weiyidu** [comment]
我直接把相关代码删掉了
www.234du.com

**Comment by seatonjiang** [comment]
新增了页面布局功能，等更新即可

![image](https://user-images.githubusercontent.com/57834639/83988288-66409e00-a975-11ea-8b20-aa97ef30b7b3.png)

![image](https://user-images.githubusercontent.com/57834639/83988257-4f01b080-a975-11ea-9dd7-d391875bb6d6.png)

![image](https://user-images.githubusercontent.com/57834639/83988277-5d4fcc80-a975-11ea-84fd-8bc105b708a2.png)
