### ISSUE TITLE
建议优化回复评论关系

### ISSUE THREAD

**Issue by kiopc** [seatonjiang/kratos#223]
**问题描述**
建议优化评论回复关系

**环境信息**
无关环境信息

**复现步奏**
个人使用的评论回复关系代码,添加到了functions.php
/**
 * 获取评论信息
 * @10:优先级
 * @3：自定义函数能接受几个参数
 */
function mini_get_qa($out,$author,$comment_id){
    $comment = get_comment($comment_id);
    // 如果没有父级评论，则正常返回，因为没有回复关系
    if ( empty( $comment->comment_parent ) ){
        return $out;
    }
    // 如果有父级评论，则添加回复关系
    // 获取父（原）评论
    $parent = get_comment($comment->comment_parent);
    // 获取父（原）评论作者
    $pauthor = get_comment_author($parent);
    //构建回复关系
    $pcid = '#content-' . $parent->comment_ID;
    $new = $out . '回复' . "<a href='{$pcid}'>{$pauthor}</a>";
    // 返回修改后的评论
    return $new;
}
add_filter('get_comment_author_link','mini_get_qa', 10, 3);

// 需要在后台设置 -> 讨论 -> 其他评论设置 -> 启用评论嵌套
// 引入回复时，评论框跟随 -> mini_get_qa()
if( is_singular() && comments_open() && get_option('thread_comments') ){
    wp_enqueue_script('comment-reply');
}

**Comment by seatonjiang** [comment]
![image](https://user-images.githubusercontent.com/57834639/83330868-a7291a80-a2c4-11ea-83a5-5335c903dc76.png)
增强了评论关系

**Comment by kiopc** [comment]
> ![image](https://user-images.githubusercontent.com/57834639/83330868-a7291a80-a2c4-11ea-83a5-5335c903dc76.png)
> 增强了评论关系

辛苦大佬
