### ISSUE TITLE
不知作者是否有计划增加夜间模式？

### ISSUE THREAD

**Issue by Robotxm** [seatonjiang/kratos#224]
**问题描述**

现在基本上各个系统都提供了夜间模式的选项，同时网页也可以自适应系统设置。作者目前有计划为主题增加夜间模式切换吗？

**环境信息**

无

**复现步奏**

无

**Comment by seatonjiang** [comment]
Dark Mode 目前会产生适配问题，还在研究完美的解决方法。

**Comment by iamlvtu** [comment]
> Dark Mode 目前会产生适配问题，还在研究完美的解决方法。

可以考虑用类似于safari浏览器自带的那种“阅读模式”效果？？？

**Comment by dreamguxiang** [comment]
很期待能够实现这个功能，加油

**Comment by seatonjiang** [comment]
Issues 功能即将关闭，请转移到 Discussions 继续讨论，https://github.com/vtrois/kratos/discussions
