### ISSUE TITLE
首页底部错位

### ISSUE THREAD

**Issue by kiopc** [seatonjiang/kratos#225]
**问题描述**
配置：顶部配置 --> 颜色导航
问题：footer错位
浏览器：chrome
**环境信息**

PHP 版本：7.2.27
Kratos 版本：3.0.9
WordPress 版本：5.4.1
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36

**复现步奏**
![](https://ftp.bmp.ovh/imgs/2020/06/b87d3957eb2fb2ee.png)

**Comment by iamlvtu** [comment]
有链接不？

**Comment by kiopc** [comment]
你好，多次测试之后发现，如果没有文章（或只有1~2篇）的时候，底部是错位的状态，当有文章在3篇以上之后底部才会正常！应该是div class="contanier"部分在没有文章内容的状态下高度不够才会出现这个问题，小瑕疵，问题不大~~



在 2020-06-04 07:44:25，"Alex" <notifications@github.com> 写道：

有链接不？

**Comment by iamlvtu** [comment]
container 加个"min-height: xxpx"样式吧，或者侧栏加几个项目也可以起到这个作用。
不过这个问题可以忽略，一旦多发布日志了就没有问题了。。。。

**Comment by kiopc** [comment]
是的，发多了就没问题了，小瑕疵，问题不大



在 2020-06-04 14:25:41，"Alex" <notifications@github.com> 写道：

container 加个"min-height: xxpx"样式吧，或者侧栏加几个项目也可以起到这个作用。
不过这个问题可以忽略，一旦多发布日志了就没有问题了。。。。

**Comment by seatonjiang** [comment]
这个 feature 在 2.x 版本中就添加了，内容充实起来就好了，问题忽略。
