### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by kiopc** [seatonjiang/kratos#226]
**问题描述**

[vqq][/vqq]

[bilibili cid=""][/bilibili]

[music][/music]

**环境信息**

PHP 版本：7.2.27
Kratos 版本：3.0.9
WordPress 版本：5.4.1
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36

**复现步奏**

这是怎么用的？？！！还是我使用方法不对，页面只能显示一个黑窗口

**Comment by iamlvtu** [comment]
对照你要分享的视频好好研究下这个文件inc/theme-shortcode.php

**Comment by kiopc** [comment]
> 对照你要分享的视频好好研究下这个文件inc/theme-shortcode.php

ok，thank u

**Comment by seatonjiang** [comment]
https://v.qq.com/x/cover/mzc002005wlunzw/u0032xa195v.html
[vqq]u0032xa195v[/vqq]

https://www.youtube.com/watch?v=gFBwXdguRrY
[youtube]gFBwXdguRrY[/youtube]

https://www.bilibili.com/video/BV1ZE411X7vJ
[bilibili cid="120652445"]69619044[/bilibili]

![image](https://user-images.githubusercontent.com/57834639/83985440-d9ddad80-a96b-11ea-8d18-eaf140efd970.png)
