### ISSUE TITLE
文章归档问题

### ISSUE THREAD

**Issue by hiblueboy** [seatonjiang/kratos#227]
这个版本是没有文章归档这个小工具了吗

**Comment by iamlvtu** [comment]
inc/theme-widgets.php文件中第23行删除就会显示程序自带的“归档小工具”了

**Comment by seatonjiang** [comment]
新增了文章归档小工具，等版本更新即可
![image](https://user-images.githubusercontent.com/57834639/83986046-04c90100-a96e-11ea-9499-7e8abe3dce68.png)
