### ISSUE TITLE
关于插入音乐播放器

### ISSUE THREAD

**Issue by mengbao233** [seatonjiang/kratos#228]
请问下，就是那个我插入第三方音乐播放器没法插入，我需要用页脚，但是我找不到

**Comment by seatonjiang** [comment]
可以写到 主题设置->收录配置->统计代码 中，这里就是在页脚注入的

**Comment by seatonjiang** [comment]
![image](https://user-images.githubusercontent.com/57834639/83985577-5ff9f400-a96c-11ea-9f89-8dcd15b85103.png)
![image](https://user-images.githubusercontent.com/57834639/83985590-69835c00-a96c-11ea-9db8-3cfac4f05d37.png)

**Comment by DrMengBao** [comment]
好的好的
