### ISSUE TITLE
文章不同级别标题样式优化

### ISSUE THREAD

**Issue by Maple-pro** [seatonjiang/kratos#229]
**问题描述**
在3.x版本中文章的不同级别的标题（h1, h2, h3, ...）区分并不明显，导致文章显得比较凌乱。
建议优化不同级别标题的样式，使文章更有层次感。
请仔细描述一下遇到的问题，截图可以直接 Ctrl + V 上传。
![image](https://user-images.githubusercontent.com/52351480/84016530-ff8ca600-a9af-11ea-89f3-44191ce9e65b.png)
![image](https://user-images.githubusercontent.com/52351480/84016504-f6033e00-a9af-11ea-816a-b28c5b0dbb2f.png)

**环境信息**
PHP 版本：5.6.40
Kratos 版本：3.0.10
WordPress 版本：5.4.1
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4164.2 Safari/537.36
将主题设置—>关于主题中「基础信息」的内容粘贴到这里。

**复现步奏**
无
请分步描述复现这个问题的步骤。

**Comment by seatonjiang** [comment]
h1 - h6 的尺寸应该是比较合理的，你看一下你的文章是不是没设置好标题？

![image](https://user-images.githubusercontent.com/57834639/84561501-8ca07800-ad7f-11ea-8a4f-39b1abe63548.png)

**Comment by seatonjiang** [comment]
调优了一下字体大小

![image](https://user-images.githubusercontent.com/57834639/84561668-f53c2480-ad80-11ea-888a-c6cfee2d9c2d.png)
![image](https://user-images.githubusercontent.com/57834639/84561714-519f4400-ad81-11ea-8be2-07e6c332ebf3.png)

**Comment by Maple-pro** [comment]
其实我觉得上一版的h2标题还挺好的，不知道为什么改了呢？

**Comment by seatonjiang** [comment]
@Maple-pro 
![image](https://user-images.githubusercontent.com/57834639/84568383-b83c5600-adb1-11ea-893f-19c2ff8f2294.png)
![image](https://user-images.githubusercontent.com/57834639/84568385-be323700-adb1-11ea-870e-e6e0c754f41a.png)

**Comment by Maple-pro** [comment]
哦哦，原来改到这里了，好的
