### ISSUE TITLE
主题代码有bug

### ISSUE THREAD

**Issue by update7700** [seatonjiang/kratos#232]
// js
wp_deregister_script('jquery');
wp_enqueue_script('jquery', ASSET_PATH . '/assets/js/jquery.min.js', array(), '3.4.1', false);
这段代码false没有用

**Comment by update7700** [comment]
false没有作用，jquery最后还是会加载到body的下面，如果在body中写jquery的代码就报错了。

**Comment by seatonjiang** [comment]
问题修复了，等新版推送即可。
