### ISSUE TITLE
几个增强建议

### ISSUE THREAD

**Issue by DreamFerry** [seatonjiang/kratos#234]
1.建议整合站点地图功能，这样就可以少装一个插件了，一大利好

2.建议加入登录保护模块，不需要多强大，限制一下失败次数和登录频次就行了

3.SMTP发信模块在部分企业邮和邮件推送服务可能存在无法发信的问题，但作者说不是主题的问题，遇到类似问题的使用者请在本条issue留言。另外，建议作者将发信人账号与SMTP账号分开。

**Comment by seatonjiang** [comment]
WordPress 设计了 theme 和 plugin，有些功能适合在主题中体现而有些功能适合在插件中体现，Kratos 主题会在用户体验方面入手，这三点问题都可以看做单独的模块，可以用插件来解决。有些功能众口难调，有些人会认为对自己没用的功能加在里面会造成主题的臃肿，所以 3.x 版本引入了 custom 目录，自定义的功能样式都可以写到这里面。

**Comment by DreamFerry** [comment]
@seatonjiang 站点地图和登录保护模块先做一下吧，这两个应该是大多数使用者都需要的，加上也不会显得臃肿，至于SMTP模块，将邮箱账号与SMTP账号分开来应该能解决部分问题

**Comment by seatonjiang** [comment]
第一个问题，WP5.5之后已经自带了站点地图功能，现在已经加到robots.txt里面调用了。第二个问题，后台登录已经加上了腾讯云验证的登录保护。第三个问题，应该就是你的配置问题了。

**Comment by n0099** [comment]
3.建议使用插件https://wordpress.org/plugins/post-smtp
