### ISSUE TITLE
博客特色图片

### ISSUE THREAD

**Issue by Maple-pro** [seatonjiang/kratos#235]
**问题描述**

现在博客的特色图片只有拉伸这一种方式，会让图片变形。能不能添加一种填充的方式，类似于设置电脑桌面壁纸的不同方式。
![image](https://user-images.githubusercontent.com/52351480/85530706-b9d30d00-b640-11ea-890b-0a102d7218b9.png)

**环境信息**

PHP 版本：5.6.40
Kratos 版本：3.0.10
WordPress 版本：5.4.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4173.0 Safari/537.36

**复现步奏**

文章添加特色图片时

**Comment by seatonjiang** [comment]
特色图片目前的比例是 48:29，后期考虑新增其他的样式。

**Comment by seatonjiang** [comment]
新版本优化了一下特色图的默认比例，固定为 16:9 ，如果上传的图片尺寸不正确，将自动裁剪一张符合的图片，PC 端和移动端的图片尺寸将在任何尺寸保持一致，新版本将于本月推送。
