### ISSUE TITLE
块级伸缩的图标依赖 Font Awesome 图标库

### ISSUE THREAD

**Issue by orilights** [seatonjiang/kratos#236]
**问题描述**

建议把这个小+号加进主题默认加载的 iconfont 里
![image](https://user-images.githubusercontent.com/61224409/85552180-530c1e80-b655-11ea-9caf-cd7cc431825d.png)

**环境信息**

PHP 版本：7.3.19
Kratos 版本：3.0.11
WordPress 版本：5.4
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36 Edg/83.0.478.54

**Comment by seatonjiang** [comment]
![image](https://user-images.githubusercontent.com/57834639/85643501-ecbfe400-b6c6-11ea-972b-35748dffa840.png)

现在把这个图片放到 iconfont 中了，Font Awesome 默认是不加载的，需要手动开启。
