### ISSUE TITLE
使用中存在的一些问题，优化建议

### ISSUE THREAD

**Issue by jiemo9527** [seatonjiang/kratos#237]
一封面的图片尺寸显示不清晰，建议增大尺寸或缩略。
二是文章标题只能显示15个字（后面是省略号），而长的文章标题大约是25个字，显示观感不佳。
三是没有放友情链接的地方

**Comment by seatonjiang** [comment]
小工具中有友情链接工具
![image](https://user-images.githubusercontent.com/57834639/87618814-5757c300-c74d-11ea-815e-be6ce9e2d310.png)

**Comment by seatonjiang** [comment]
目前标题已经增加到21个文字，基本可以满足大多数人的需求了。
特色图片的尺寸比例建议在 1.875:1
