### ISSUE TITLE
建议导航栏优化一下，滚动页面，可以固定在顶部（吸顶效果）

### ISSUE THREAD

**Issue by wuhenge** [seatonjiang/kratos#238]
**问题描述**

建议导航栏优化一下，滚动页面，可以固定在顶部（吸顶效果）
另外导航栏优化一下位置，一般都是四个字，8-9个导航链接左右

**环境信息**

将主题设置—>关于主题中「基础信息」的内容粘贴到这里。

**复现步奏**

请分步描述复现这个问题的步骤。

**Comment by seatonjiang** [comment]
导航 8 个也放不开啊，太多分类建议用二级目录，navbar 在优化中

**Comment by seatonjiang** [comment]
Issues 功能即将关闭，请转移到 Discussions 继续讨论，https://github.com/vtrois/kratos/discussions
