### ISSUE TITLE
希望手机端可以选开小工具栏，会有用的

### ISSUE THREAD

**Issue by SuperYYT** [seatonjiang/kratos#24]

**Comment by PillarsZhang** [comment]
你的意思就是在屏幕尺寸较小时将侧边栏显示在下方（原本是直接不显示），这个我也很支持哟～

**Comment by ghost** [comment]
文章页面在移动端的设计就是最简单的将文章内容展示出来，移动端的页面元素越少越实用，所以不准备将小工具展示到文章下面。
