### ISSUE TITLE
编辑器被强制改为经典编辑器，无法切换成区块编辑器，使用其他主题时没问题，在不安装其他编辑器的情况下，默认是区块编辑器

### ISSUE THREAD

**Issue by update7700** [seatonjiang/kratos#240]
编辑器被强制改为经典编辑器，无法切换成区块编辑器，使用其他主题时没问题，在不安装其他编辑器的情况下，默认是区块编辑器

希望给个解决方案

**Comment by seatonjiang** [comment]
主题设置 -> 全站配置 -> Gutenberg 编辑器
![image](https://user-images.githubusercontent.com/57834639/86111500-69085c00-baf9-11ea-9d3e-bc204da36be8.png)
