### ISSUE TITLE
Safari浏览器中文章图片无法正常显示 

### ISSUE THREAD

**Issue by cocobase** [seatonjiang/kratos#242]
wordpress发布的文章中含图片，正常在chrome浏览器中可以显示，但是在safari浏览器中就没有显示出来。

**环境信息**

PHP 版本：7.0.27
Kratos 版本：3.0.11
WordPress 版本：5.4.2
User Agent 信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36

**复现步奏**

1. 打开Chrome浏览器，访问http://huang.center/bbc100-classical-books/
2.打开safari浏览器，访问http://huang.center/bbc100-classical-books/
3.对比

**Comment by cocobase** [comment]
经过多次查询和分析，最后定位是因该问题所致：
Jetpack的【性能】-【速度】页面中配置了：启用站点加速导致

**Comment by cocobase** [comment]
但是在chrome的调试页面中，依然可以看到如下家在的错误
GET https://stats.wp.com/e-202027.js net::ERR_TIMED_OUT

不知道在哪里加载了这js

**Comment by seatonjiang** [comment]
参考 https://wordpress.org/support/topic/stats-wp-com/

**Comment by seatonjiang** [comment]
Jetpack 插件的问题，不是主题的问题
