### ISSUE TITLE
有什么办法可以让文章的 ID 能够连续？难办的是图片会占用一个id

### ISSUE THREAD

**Issue by 8090s** [seatonjiang/kratos#244]
是这样，我是用的 open live writer 客户端写文章，写文章的时候会直接粘贴图片到文章中，这样发布以后，每个图片都会占用2个 ID , 有没有什么办法能让文章中的图片不占用id，据网上说先把图片上传到媒体库，然后再文章中引用可以达到目的，但是如此太麻烦了，另外，禁用autosave ， revision 网上有挺多的办法， 就这个图片占用id的问题，各位，有没有什么好办法？谢谢

**Comment by seatonjiang** [comment]
如果是说是想使用 url/112 这样的路由建议别折腾
