### ISSUE TITLE
如何修改标签聚合的数量不是固定为8个？

### ISSUE THREAD

**Issue by cocobase** [seatonjiang/kratos#245]
**问题描述**

标签聚合的数量看起来是无法修改的？是否可以做配置，或者在代码里涉及到这个问题的位置在哪里，我看看可否增加个配置参数

**Comment by seatonjiang** [comment]
![image](https://user-images.githubusercontent.com/57834639/86523705-8eeb8300-bea2-11ea-8c0f-805cb861093c.png)
