### ISSUE TITLE
你们在文章页点击图片会弹出一个新窗口吗？

### ISSUE THREAD

**Issue by chunbo007** [seatonjiang/kratos#249]
你们在文章页点击图片会弹出一个新窗口吗？

**Comment by seatonjiang** [comment]
上传选择图片的时候 链接到 选项改成无即可
![image](https://user-images.githubusercontent.com/57834639/87618450-786be400-c74c-11ea-936c-c6bc076fbc3f.png)

**Comment by chunbo007** [comment]
> 上传选择图片的时候 链接到 选项改成无即可
> ![image](https://user-images.githubusercontent.com/57834639/87618450-786be400-c74c-11ea-936c-c6bc076fbc3f.png)

感谢
