### ISSUE TITLE
youtube视频脚本，文章链接样式

### ISSUE THREAD

**Issue by bi-xuri** [seatonjiang/kratos#250]
**主题很不错目前发现youtube视频脚本无法存在问题**
解决：
<iframe id='test' width='100%' src='https://www.youtube.com/自己加 ' frameborder=0 'allowfullscreen'></iframe>
<script type="text/javascript">
document.getElementById("test").style.height=document.getElementById("test").scrollWidth*0.75+"px";
</script>
![image](https://user-images.githubusercontent.com/67690716/87513323-2030d580-c6ab-11ea-891f-181d9a830a3a.png)

**文章链接自动没有样式**
解决：
<iframe class="wp-embedded-content" sandbox="allow-scripts" security="restricted" style="position: absolute; clip: rect(1px, 1px, 1px, 1px);" title="《kvm-or-xen  VPS如何选择》—fto2" src="文章链接" data-secret="yfE97RTPH8" width=100% frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>
![image](https://user-images.githubusercontent.com/67690716/87513258-042d3400-c6ab-11ea-836b-4e2d3d123888.png)

**Comment by seatonjiang** [comment]
试一下短连接
[youtube]gFBwXdguRrY[/youtube]
https://www.youtube.com/watch?v=gFBwXdguRrY

![image](https://user-images.githubusercontent.com/57834639/87617911-165eaf00-c74b-11ea-96a0-3c6c86044fc9.png)
![image](https://user-images.githubusercontent.com/57834639/87617919-1bbbf980-c74b-11ea-98e6-c54635da9359.png)

**Comment by bi-xuri** [comment]
可以的   谢谢啊
