### ISSUE TITLE
i dont know the password of the file i've download

### ISSUE THREAD

**Issue by waxy1314a** [seatonjiang/kratos#251]
**问题描述**

请仔细描述一下遇到的问题，截图可以直接 Ctrl + V 上传。

**环境信息**

将主题设置—>关于主题中「基础信息」的内容粘贴到这里。

**复现步奏**

请分步描述复现这个问题的步骤。

**Comment by seatonjiang** [comment]
There is no password for the theme file, what password are you referring to?
