### ISSUE TITLE
Hope to increase the friendship link function

### ISSUE THREAD

**Issue by nine-city** [seatonjiang/kratos#252]
I want to put other websites such as my friend’s blog link at the bottom, hoping to add a friendly link function

**Comment by seatonjiang** [comment]
This feature is included in the widgets

![image](https://user-images.githubusercontent.com/57834639/87785436-ba8b4780-c86a-11ea-8c1f-817e4740ea53.png)
![image](https://user-images.githubusercontent.com/57834639/87785512-d4c52580-c86a-11ea-979d-d7678ccbb8ed.png)
