### ISSUE TITLE
你好，bilibili视频无法显示

### ISSUE THREAD

**Issue by fullstackpeng** [seatonjiang/kratos#253]
**问题描述**
点击bilibili图标后页面中无法显示视频
请仔细描述一下遇到的问题，截图可以直接 Ctrl + V 上传。
![image](https://user-images.githubusercontent.com/41058332/87867488-bea78a00-c97c-11ea-809b-fdcb6180ba1c.png)
![image](https://user-images.githubusercontent.com/41058332/87867493-c7985b80-c97c-11ea-8077-186bce172fd4.png)
![image](https://user-images.githubusercontent.com/41058332/87867495-cc5d0f80-c97c-11ea-8949-231e54278ae5.png)

**环境信息**

将主题设置—>关于主题中「基础信息」的内容粘贴到这里。

**复现步奏**

请分步描述复现这个问题的步骤。

**Comment by seatonjiang** [comment]
https://www.bilibili.com/widget/getPageList?aid=12722140

通过这个接口获取 CID，填写的例子如下

[bilibili cid="20919317"]12722140[bilibili]

**Comment by xinaiwunai** [comment]
建议使用新的参数bvid。该参数只需要一个便可以正常显示视频，且该参数现在是视频网址的最新编号，直接在地址栏就可以获取。
http://player.bilibili.com/player.html?bvid=BV1Fa4y177Y7&page=1

原本aid + cid的方式比较不易使用：
http://player.bilibili.com/player.html?aid=669724818&cid=237124504&page=1

**Comment by xinaiwunai** [comment]
> https://www.bilibili.com/widget/getPageList?aid=12722140
> 
> 通过这个接口获取 CID，填写的例子如下
> 
> [bilibili cid="20919317"]12722140[bilibili]

建议使用新的参数bvid。该参数只需要一个便可以正常显示视频，且该参数现在是视频网址的最新编号，直接在地址栏就可以获取。
http://player.bilibili.com/player.html?bvid=BV1Fa4y177Y7&page=1

原本aid + cid的方式比较不易使用：
http://player.bilibili.com/player.html?aid=669724818&cid=237124504&page=1

**Comment by seatonjiang** [comment]
更新了B站的引用方式，等新版本更新即可。

https://www.bilibili.com/video/BV17t411k752

[bilibili]BV17t411k752[/bilibili]

![image](https://user-images.githubusercontent.com/57834639/93732244-14114900-fc03-11ea-82da-bd682fdff645.png)
