### ISSUE TITLE
关于移动站点页面

### ISSUE THREAD

**Issue by dryangyq** [seatonjiang/kratos#254]
移动站点，因为用到了响应式布局，跟PC端有很大不同，如何才能加入近期评论之类的内容呢？现在有人评论，我用手机进去都不知道他评论的是哪个文章，找起来很不方便。

**Comment by seatonjiang** [comment]
手机端建议直接进后台去看评论

**Comment by seatonjiang** [comment]
近期评论已经加到了PC端，将在新版本中进行推送。
