### ISSUE TITLE
最新版Kratos邮件配置正确后无法发送邮件通知

### ISSUE THREAD

**Issue by gimgoo** [seatonjiang/kratos#256]
如题，原来版本配置后有评论会通知，但现在设置不会，连垃圾邮件都没有测试多个邮箱都不行。

**Comment by seatonjiang** [comment]
管理员在后台「主题设置」->「邮件配置」页面，找到「SMTP 服务」选项，点击勾选后会弹出配置信息，根据提示填写相应的信息即可。提示：邮件服务器由邮件服务商提供，比如：smtp.exmail.qq.com；服务器端口由邮件服务商提供，比如：465；授权方式是登录鉴权的方式，根据服务商提供的信息填写，比如：ssl；邮箱帐号和邮箱密码则填写相应的信息即可，最后可以点击下面的「测试邮件」按钮，如果填写正确，管理员邮箱将收到一封来自所填写邮箱账号的测试邮件。

**Comment by seatonjiang** [comment]
参考 https://github.com/vtrois/kratos/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AF-smtp-%E6%9C%8D%E5%8A%A1

**Comment by gimgoo** [comment]
很感谢大佬耐心指点迷津，但是我不是第一次用大佬这个主题的，我之前就在用，但是现在确实无法发送，我确保填对了。我也知道测试会收到邮件，因为我升级前是可以收到邮件的。

**Comment by seatonjiang** [comment]
功能测试是没有问题的，你可以找到 `theme-smtp.php`，注释掉第30行，开启调试，看一下 log 返回的具体内容

https://github.com/vtrois/kratos/blob/be6f4ff791051f19f915be04d4121d58fb7cfe20/inc/theme-smtp.php#L25-L30

![image](https://user-images.githubusercontent.com/57834639/88605174-c4534d00-d0ab-11ea-8979-9deadc1021e1.png)

**Comment by gimgoo** [comment]
好，谢谢大佬，请问开启Debug后，log路径在哪

**Comment by seatonjiang** [comment]
wp-config.php 要开启 debug，日志在 wp-content 目录下
```
define(‘WP_DEBUG’, true);
define(‘WP_DEBUG_LOG’, true);
```

**Comment by gimgoo** [comment]
[29-Jul-2020 03:39:44 UTC] WP_Error Object
(
    [errors] => Array
        (
            [wp_mail_failed] => Array
                (
                    [0] => SMTP Error: Could not authenticate.
                )

        )

    [error_data] => Array
        (
            [wp_mail_failed] => Array
                (
                    [to] => Array
                        (
                            [0] => 接受邮件的邮箱
                        )

                    [subject] => [测试]邮件服务配置成功
                    [message] => 恭喜您 SMTP 邮件服务配置成功！
                    [headers] => Array
                        (
                        )

                    [attachments] => Array
                        (
                        )

                    [phpmailer_exception_code] => 0
                )

        )

)

**Comment by gimgoo** [comment]
![image](https://user-images.githubusercontent.com/31849284/88754202-a4e22000-d190-11ea-862b-428cb19ac7da.png)
真的很奇怪，我以为会是授权码问题，但是，当我取163更换授权码以后，还是这个log。

**Comment by gimgoo** [comment]
但我发现你那个图多了个ssl选项

**Comment by gimgoo** [comment]
![image](https://user-images.githubusercontent.com/31849284/88754351-086c4d80-d191-11ea-877c-e7f9521599cd.png)

**Comment by seatonjiang** [comment]
授权方式改一下，Port = 465 写 `ssl`，Port = 587 写 `tls`

**Comment by gimgoo** [comment]
谢谢大佬，改了以后可以了，ssl不是加密方式吗？最新版的改成授权方式了？
