### ISSUE TITLE
首页的个人头像下面能显示名字吗

### ISSUE THREAD

**Issue by John10240** [seatonjiang/kratos#257]
首页的个人头像下面能显示名字吗，给个打勾的选项让我们自己选择也行，不显示名字总觉得不舒服哈哈。
![image](https://user-images.githubusercontent.com/30192801/88471384-67d12000-cf3b-11ea-92cb-57353af2f140.png)

另外个人头像下面的简介可以支持自定义HTML代码吗。

**Comment by seatonjiang** [comment]
支持HTML代码，你可以自己写进去

**Comment by seatonjiang** [comment]
新增了这个功能，等推送即可。

![image](https://user-images.githubusercontent.com/57834639/88752652-0b653f00-d18d-11ea-82d7-f9c4f1c40483.png)
