### ISSUE TITLE
手机端 列表文章图片显示高度问题

### ISSUE THREAD

**Issue by kkwow** [seatonjiang/kratos#258]
你好，默认手机端文章图片是截取显示高度，我想实现完整显示高度。请问该如何设置？

**Comment by seatonjiang** [comment]
可以自己调整  `.a-thumb` 及 `.a-thumb img` 相关代码

https://github.com/vtrois/kratos/blob/6aeba2347cd128195dfe93db8a508467272e6b50/assets/css/kratos.css#L697-L716

**Comment by kkwow** [comment]
width: auto;  改 width: 100%;  保存后，刷新页面 没有任何变化。

**Comment by seatonjiang** [comment]
新版本优化了一下特色图的默认比例，固定为 16:9 ，如果上传的图片尺寸不正确，将自动裁剪一张符合的图片，PC 端和移动端的图片尺寸将在任何尺寸保持一致。新版本将在本月推送。
