### ISSUE TITLE
首页中SEO缺少<h1>标题标签的问题，影响SEO

### ISSUE THREAD

**Issue by cocobase** [seatonjiang/kratos#259]
使用主题后，微软bing.com  的站点收录时候提示有一个高度严重的问题，首页缺乏 `<h1>` 标签。
SEO中对于 `<h1> `的需求是非常重要的
不知道这个问题如何解决？

**Comment by seatonjiang** [comment]
首页不影响收录，文章标题在首页都是 h2 标签

**Comment by seatonjiang** [comment]
这个问题已经优化了，将会在新版本中推送
