### ISSUE TITLE
请问下是否可以支持AMP插件

### ISSUE THREAD

**Issue by 30115776** [seatonjiang/kratos#260]
AMP

Enable AMP on your WordPress site, the WordPress way.

1.5.5版本

AMP Project Contributors 

PHP 版本：7.4.8
Kratos 版本：3.1.1
WordPress 版本：5.4.2

**Comment by seatonjiang** [comment]
刚测试了一下，似乎是支持 AMP 插件的

**Comment by seatonjiang** [comment]
我这里在最新版中也测试了一下，这个插件是正常的。
