### ISSUE TITLE
页面CSS 404

### ISSUE THREAD

**Issue by YI--** [seatonjiang/kratos#261]
找到地方了

**Comment by YI--** [comment]
关闭问题

**Comment by seatonjiang** [comment]
先升级 3.1.1 版本，主题设置里面有个 『静态资源加速』开启之后就是 JSDelivr 节点，关闭就是本地加载， 最新版本中去掉了自建CDN
 
![image](https://user-images.githubusercontent.com/57834639/89139557-979eaa00-d571-11ea-96c0-ae981ec8c74f.png)

**Comment by seatonjiang** [comment]
参考 #267
