### ISSUE TITLE
cdn 失效了 无法加载样式 怎么加载本地的呢

### ISSUE THREAD

**Issue by hiblueboy** [seatonjiang/kratos#262]
打开博客后没有样式，Console 输出  Failed to load resource: the server responded with a status of 404 () 还有对应的 cdn 404 ，请问让其可以加载本地文件吗

**Comment by hiblueboy** [comment]
找到了解决方案

**Comment by seatonjiang** [comment]
Kratos v3.1.1 为了提高可用性，去掉了自建的CDN（https://n3.cdn.vtrois.com/），仅保留了 JSDelivr 节点，如果不想升级主题可以把这里调成 JSDelivr ，如果升级主题，升级之后默认是 JSDelivr 节点，如果不开这个功能，就是本地加载资源

![image](https://user-images.githubusercontent.com/57834639/89140554-8905c200-d574-11ea-94d9-7f90036e4293.png)

**Comment by seatonjiang** [comment]
参考 #267
