### ISSUE TITLE
如何在更新主题的时候保留旧版的设置

### ISSUE THREAD

**Issue by A0CBEB339CB02898** [seatonjiang/kratos#264]
**问题描述**

更新主题的时候会丢失掉原来主题设置的一些内容，要怎么保持（带到新版本中来）呢。

**环境信息**

PHP 版本：7.3.0
Kratos 版本：3.0.9
WordPress 版本：5.4.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

**复现步奏**

无

**Comment by seatonjiang** [comment]
3.0 版本之后升级不会丢失主题设置了，都是写进 wp 数据库里的

**Comment by A0CBEB339CB02898** [comment]
> 3.0 版本之后升级不会丢失主题设置了，都是写进 wp 数据库里的

但是我通过手动上传新版的上去并没有载入原有的设置，是要通过别的 方式升级吗？

**Comment by seatonjiang** [comment]
后台可以直接升级，8月10日之后 WP 5.5 版本可以直接上传主题自动升级

**Comment by seatonjiang** [comment]
定位到问题了，由于 Github 下载到的安装包文件名是带后缀的，其他途径下载的不带后缀，但是配置信息存储的名字用的是文件名，导致如果变更了主题文件夹的名字，导致配置丢失的问题，现在修复了，固定使用主题名 kratos
