### ISSUE TITLE
关于媒体托管资源返回路径不正确的问题

### ISSUE THREAD

**Issue by bhxdn** [seatonjiang/kratos#265]
**问题描述**

我开启了媒体托管资源，发现返回的url地址不正确。

**环境信息**

PHP 版本：5.6.40
Kratos 版本：3.1.3
WordPress 版本：5.4.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**复现步奏**

假设我要上传一张图片，图片是211.jpg
![image](https://user-images.githubusercontent.com/53896774/89317110-86f44e00-d6af-11ea-86d0-d1a0dfd2b64d.png)
上传之后，文件名就自动变成了211-scaled.jpg.
并且图片的url的地址也是错误的
![image](https://user-images.githubusercontent.com/53896774/89317247-b2773880-d6af-11ea-9635-0dcb3922c531.png)
我上午测试，进行抓包，发现再往云端存照片，返回successs的包里面的data数据，filename和url属性就是自动加了scaled的，导致返回的数据中，url的地址错误，不能正常访问。我看到data数据下面有一个类似于url的属性，就是图片的正确地址。
不知道是我个人的原因还是因为DogeCloud修改了返回报文的参数导致出现的问题，希望能得到解决。

**Comment by seatonjiang** [comment]
刚刚测试了一下，返回是正常的，你是不是开了什么插件导致的

![image](https://user-images.githubusercontent.com/57834639/89369655-59d88780-d711-11ea-9794-112d811b1f44.png)

**Comment by bhxdn** [comment]
> 刚刚测试了一下，返回是正常的，你是不是开了什么插件导致的
> 
> ![图片](https://user-images.githubusercontent.com/57834639/89369655-59d88780-d711-11ea-9794-112d811b1f44.png)

我刚刚又测试了一下，感觉是DogeCloud的原因，我昨天测试的时候上传的图片是一些张高和宽比较大的图片，发送过去之后返回的url是缩略图的，所以不能正常显示。刚刚我测试了一些比较小的图片，发现可以正常上传了。谢谢解答。

**Comment by seatonjiang** [comment]
这个接口上传10M之内的文件是没有问题的，有问题及时反馈。
