### ISSUE TITLE
连接n3.cdn.vtrois.com失败

### ISSUE THREAD

**Issue by myf5** [seatonjiang/kratos#266]
**问题描述**
启用使用猫云CDN缓存css/jss，发现连接全部失败

为测试是否是本地问题，使用外部代理测试，发现也无法连接

**环境信息**

PHP 版本：7.4.6
Kratos 版本：3.1.0
WordPress 版本：5.4.2
User Agent 信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36

**复现步奏**

请分步描述复现这个问题的步骤。

**Comment by seatonjiang** [comment]
更新到 3.1.3 版本即可，可以参考一下 #267
