### ISSUE TITLE
寻求帮助

### ISSUE THREAD

**Issue by TIMEXH** [seatonjiang/kratos#269]
**问题描述**

无法变更主题设置

**环境信息**

PHP 版本：7.4.0
Kratos 版本：3.1.4
WordPress 版本：5.3.2
User Agent 信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

**复现步奏**

无

**Comment by hexone2086** [comment]
也出现了同样的问题
*****
**环境信息**
PHP 版本：7.4.0
Kratos 版本：3.1.4
WordPress 版本： 5.4.2

**Comment by seatonjiang** [comment]
@cwrb8888 删除主题目录，通过后台上传主题试一下？

**Comment by TIMEXH** [comment]
尝试过了，无效




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seaton Jiang"<notifications@github.com&gt;; 
发送时间: 2020年8月9日(星期天) 下午2:17
收件人: "vtrois/kratos"<kratos@noreply.github.com&gt;; 
抄送: "时空小黄"<3101710757@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vtrois/kratos] 寻求帮助 (#269)





 
@cwrb8888 删除主题目录，通过后台上传主题试一下？

**Comment by seatonjiang** [comment]
已经定位到问题，将在后续版本中修复，等后台推送即可。
