### ISSUE TITLE
顶部导航栏高度异常

### ISSUE THREAD

**Issue by Maple-pro** [seatonjiang/kratos#270]
**问题描述**

选择浏览站点时不显示工具栏，顶部导航栏高度异常。
下面为对比图。
![image](https://user-images.githubusercontent.com/52351480/89729173-a6032f00-da65-11ea-9ece-252cc8eb7f10.png)
![image](https://user-images.githubusercontent.com/52351480/89729185-c337fd80-da65-11ea-958e-fe5764765a1a.png)
不显示工具栏时，导航栏和下方的内容卡片之间没有间隙。

**环境信息**

PHP 版本：7.4.8
Kratos 版本：3.1.5
WordPress 版本：5.4.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36

**复现步奏**

1. 选择浏览站点不显示工具栏
2. 进入站点

**Comment by seatonjiang** [comment]
主题设置中添加了一个开关，修复这个问题，等新版本推送，或者直接拉取最新代码即可。

![image](https://user-images.githubusercontent.com/57834639/89759959-d9a19000-db1d-11ea-90b9-517edcf025f6.png)
