### ISSUE TITLE
开发者您好。text editor黏贴时，多余的换行会自动消失

### ISSUE THREAD

**Issue by WenqianC** [seatonjiang/kratos#271]
非常感谢您的这个主题，谢谢您！！

发现除自己站点以外的地方，把文本复制进text editor后，多余的换行会消失。
下面两张图，原文本是两段中间有空行的。
在【可视化】界面中，黏贴后空行直接消失。
在【文本】界面中，黏贴后能看到空行，但是实际不起作用
<img width="405" alt="Screen Shot 2020-08-10 at 22 50 43" src="https://user-images.githubusercontent.com/46984632/89862239-623f2100-db5c-11ea-827d-579dbea37a68.png">

<img width="487" alt="Screen Shot 2020-08-10 at 22 52 09" src="https://user-images.githubusercontent.com/46984632/89862254-6a975c00-db5c-11ea-85a8-038831badff2.png">

查了下应该是主题的问题，不是wp本身的问题。
实在不知道怎么解决，不好意思来打扰了……

**Comment by seatonjiang** [comment]
WP 编辑器问题，如果要有空行，先把空行回车到可视化中，在代码里看到会有
![image](https://user-images.githubusercontent.com/57834639/89868305-2bf9b400-dbe5-11ea-8ff6-4658df30fe57.png)
![image](https://user-images.githubusercontent.com/57834639/89868320-30be6800-dbe5-11ea-955f-b0bab11ebf78.png)

**Comment by WenqianC** [comment]
> WP 编辑器问题，如果要有空行，先把空行回车到可视化中，在代码里看到会有
> ![image](https://user-images.githubusercontent.com/57834639/89868305-2bf9b400-dbe5-11ea-8ff6-4658df30fe57.png)
> ![image](https://user-images.githubusercontent.com/57834639/89868320-30be6800-dbe5-11ea-955f-b0bab11ebf78.png)

感谢回复！所以是只能手动添加空行，对吗？因为如果直接在文本界面中用&nbsp替换掉空行的话，我设置的首行自动缩进就不起作用了。

**Comment by seatonjiang** [comment]
直接复制内容到编辑器里面，是会保留空行的
