### ISSUE TITLE
关于widget的一些问题

### ISSUE THREAD

**Issue by dryangyq** [seatonjiang/kratos#273]
主题带的widget不好用，主要有两个方面：

1. 文章聚合，默认显示的是按照热度，能否默认显示按照最新文章？或者给个选项。
2. 没有最新评论的widget，是否能够考虑添加一个？

**Comment by hibobmaster** [comment]
同求！
还有能否添加一个简单的站点统计功能

**Comment by seatonjiang** [comment]
@yangyongquan85 这两个问题都已经做了更新，等待新版本推送即可使用了

![image](https://user-images.githubusercontent.com/57834639/102017644-1c60c680-3da3-11eb-9b6e-62800bec5eea.png)
![image](https://user-images.githubusercontent.com/57834639/102017654-30a4c380-3da3-11eb-9aad-197567d904eb.png)
