### ISSUE TITLE
关于首页文章栏显示问题

### ISSUE THREAD

**Issue by yumetec** [seatonjiang/kratos#274]
大佬，请问能否给首页增加一个像【文章配置-页面布局】那样的设置，就是首页那里感觉文章栏显示太窄了，我以为去掉所有侧边栏小工具会自动加宽，但是并没有。

然后我自己去custom.css那里调了下效果似乎不是很好，要么电脑上显示可以了，然后手机显示不好，不适配

或者大佬能否指点下我如何进行修改？

**Comment by orilights** [comment]
把这里改成col-lg-12就行了，我记得是在index.php文件里

![image](https://user-images.githubusercontent.com/61224409/90705748-393e2f00-e2c6-11ea-825f-bdb831083633.png)


动手能力强一点的话可以自己加一个选择

![image](https://user-images.githubusercontent.com/61224409/90705907-9508b800-e2c6-11ea-8b36-20d674a69170.png)

**Comment by yumetec** [comment]
谢谢大佬，已修改
