### ISSUE TITLE
kratos主题能否兼容wedocs插件？

### ISSUE THREAD

**Issue by qglian** [seatonjiang/kratos#275]
**问题描述**
Kratos v3.1.5 对wedocs文档插件的兼容性不是很好，尤其是文档首页。
![wedoc](https://user-images.githubusercontent.com/65819267/90707819-fb8fd500-e2ca-11ea-834c-2268fadd64f2.jpg)

wedocs插件地址 https://wordpress.org/plugins/wedocs/

**环境信息**

基础信息
PHP 版本：7.3.18
Kratos 版本：3.1.5
WordPress 版本：5.4.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36 Edg/84.0.522.61

**复现步奏**
请访问  http://www.ditiexia.com/docs

**Comment by seatonjiang** [comment]
测试了一下这个插件，这个插件官方介绍并不是会适配所有的主题，需要自己修改插件提供的页面去覆盖主题，可以参考该插件的说明来自己实现 https://github.com/tareq1988/wedocs-plugin/wiki/Templating
