### ISSUE TITLE
主题与一个Mac风格的代码高亮插件不太兼容，麻烦帮忙看看怎么解决哈

### ISSUE THREAD

**Issue by supersu097** [seatonjiang/kratos#277]
**问题描述**
代码高亮应该显示为如下：
![image](https://user-images.githubusercontent.com/7045106/91302109-8b0c1b00-e7d8-11ea-8db6-99874c5f7b42.png)
实际显示为如下：
![image](https://user-images.githubusercontent.com/7045106/91302275-cad30280-e7d8-11ea-9038-20a03dd41e4d.png)

**环境信息**
PHP 版本：7.1.33
Kratos 版本：3.1.6
WordPress 版本：5.3.4

**复现步奏**
到 https://www.xiunima.com/101.html 这里下载代码高亮插件安装，
在插件设置里面选择mosheng这个主题(这个就是Mac风格的高亮主题)，
然后随便创建一篇文章粘贴一点代码，就能看到上面第二张截图中的不正常显示了。

**Comment by supersu097** [comment]
如果不太好解决的话就算了哈，我在写py脚本迁移到enlighter

**Comment by seatonjiang** [comment]
这个插件测试了一下，建议把插件里的 css 都加上 `!important` 就行了

**Comment by supersu097** [comment]
> 这个插件测试了一下，建议把插件里的 css 都加上 `!important` 就行了

好的，我这就试试哈~

**Comment by supersu097** [comment]
> 这个插件测试了一下，建议把插件里的 css 都加上 `!important` 就行了

加上!important果然可以了，不过还有个小问题，就是toolbar那里的全选代码和复制显示的有点不正常，如下：
![image](https://user-images.githubusercontent.com/7045106/91631519-afe8d400-ea0c-11ea-8aa5-f2409d2c7121.png)
正常的如下：
![image](https://user-images.githubusercontent.com/7045106/91631526-c0994a00-ea0c-11ea-8e47-9fb532703bc9.png)
感觉貌似要改css才能解决这个小问题，但是鄙人对css实在不熟，麻烦你抽空看看要怎么改哈~

**Comment by seatonjiang** [comment]
你把网址发一下，我看看

**Comment by supersu097** [comment]
> 你把网址发一下，我看看

不正常的显示是部署在本地的虚拟机里面的截图，我线上的博客还没切换到kratos呢，线上用的是修改版的[kratos-pjax](https://github.com/xb2016/kratos-pjax)（你可以看看为啥pjax版本的kratos显示正常，它是基于你的2点几的版本开发的），我现在线上的正常显示的博客是比如说 https://www.sharpgan.com/notify-hostloc-hot/ 这个。

**Comment by iamlvtu** [comment]
kratos.min.css中
`.k-main .details .toolbar {
margin-top: 16px;
padding: 20px;
background-color: #fff; 
-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.1);
-moz-box-shadow: 0 1px 2px rgba(0,0,0,.1);
box-shadow: 0 1px 2px rgba(0,0,0,.1);
}`
删除background-color: #fff; 即可

**Comment by supersu097** [comment]
> kratos.min.css中
> `.k-main .details .toolbar { margin-top: 16px; padding: 20px; background-color: #fff; -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.1); -moz-box-shadow: 0 1px 2px rgba(0,0,0,.1); box-shadow: 0 1px 2px rgba(0,0,0,.1); }`
> 删除background-color: #fff; 即可

好的，我试试哈

**Comment by supersu097** [comment]
> kratos.min.css中
> `.k-main .details .toolbar { margin-top: 16px; padding: 20px; background-color: #fff; -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.1); -moz-box-shadow: 0 1px 2px rgba(0,0,0,.1); box-shadow: 0 1px 2px rgba(0,0,0,.1); }`
> 删除background-color: #fff; 即可

![Screenshot_2020-09-14-10-36-07-829_com android chrome](https://user-images.githubusercontent.com/7045106/93038293-317c6b00-f677-11ea-81be-5d3c41499356.jpg)
删除掉这个之后，比之前好多了，但位置还应该靠上一些，麻烦看看还要怎么修改哈~

**Comment by iamlvtu** [comment]
同样的位置
padding: 20px;
改为
padding: 0 10px;

**Comment by supersu097** [comment]
> 同样的位置
> padding: 20px;
> 改为
> padding: 0 10px;

刚刚试了一下，好像改了之后还是老样子，第一次删除background-color: #fff; 时只是把本地缓存清了一下，刷新页面马上就生效了，这一次不知道是不是我的阿里云的全站加速节点上缓存没有刷新导致的。

**Comment by supersu097** [comment]
@iamlvtu 感觉好像好了一点
![image](https://user-images.githubusercontent.com/7045106/93101706-2fe58e00-f6dd-11ea-9e96-61c4342cd1a2.png)
