### ISSUE TITLE
文章里的页面导览有问题。

### ISSUE THREAD

**Issue by WenqianC** [seatonjiang/kratos#278]
**问题描述**

会显示全部的页码。
<img width="824" alt="Screen Shot 2020-08-27 at 21 07 48" src="https://user-images.githubusercontent.com/46984632/91520244-aa26ad80-e8a9-11ea-9e85-1ff7ab204471.png">

想改成首页的那种页码导览（下图），代码应该是用pagelist();吧，但是放到single.php里没有任何改变，不知道哪里做错了。
<img width="359" alt="Screen Shot 2020-08-27 at 21 12 42" src="https://user-images.githubusercontent.com/46984632/91520406-10133500-e8aa-11ea-88f6-58d055cbde4a.png">

另外请问有打算添加输入页码跳转的功能吗？

感谢开发者！这个主题真的特别喜欢~

**Comment by seatonjiang** [comment]
复现了这个问题，正在修复

**Comment by seatonjiang** [comment]
这个问题统一在 #216 中解决修复
