### ISSUE TITLE
站点标题问题

### ISSUE THREAD

**Issue by Maple-pro** [seatonjiang/kratos#279]
**问题描述**

请仔细描述一下遇到的问题，截图可以直接 Ctrl + V 上传。
![image](https://user-images.githubusercontent.com/52351480/91550188-bf0f4980-e95a-11ea-93f6-7d1ec804a7df.png)
站点标题后多了一个“-”，本来应该是“Maples' Space”

**环境信息**

PHP 版本：7.4.9
Kratos 版本：3.1.6
WordPress 版本：5.5
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

**复现步奏**

在wordpress后台的设置中设置站点标题为“Maples' Space"
![image](https://user-images.githubusercontent.com/52351480/91550396-0f86a700-e95b-11ea-9349-f6c8fe7362ed.png)

**Comment by seatonjiang** [comment]
你看一下副标题是不是有空格？我这测试了一下没问题

![image](https://user-images.githubusercontent.com/57834639/91628200-0dbaf300-e9f0-11ea-9acb-c12d27189714.png)

![image](https://user-images.githubusercontent.com/57834639/91628198-08f63f00-e9f0-11ea-8216-e2d6ba272015.png)

**Comment by Maple-pro** [comment]
副标题为空时还是有这个问题。我把副标题设置为“Home”，算是解决了吧。
