### ISSUE TITLE
【功能建议】文章特色图片能否支持图床链接

### ISSUE THREAD

**Issue by isyume** [seatonjiang/kratos#280]
如题，大佬能否考虑让文章的特色图片支持图床链接而不是要上传到服务器，虽说图片也不是很大，但是如果能换成图床外链，不仅打开网页速度更快，还能减少服务器请求。另外一个就是，如果支持外链的话，备份只需要备份sql文件就行了。不然还要备份content下的upload文件夹里面的众多小图片。

**Comment by seatonjiang** [comment]
主题设置里配置一下媒体资源托管就可以实现了

![image](https://user-images.githubusercontent.com/57834639/91628170-cfbdcf00-e9ef-11ea-8c83-dae5dd2cdcc2.png)

![image](https://user-images.githubusercontent.com/57834639/91628166-c6ccfd80-e9ef-11ea-91db-4d705e533267.png)
