### ISSUE TITLE
主题好像不兼容reCaptcha by BestWebSoft这个插件，麻烦抽空看看怎么解决哈

### ISSUE THREAD

**Issue by supersu097** [seatonjiang/kratos#282]
**问题描述**

这个插件启用后，登录页会注入google 的recaptcha 人机验证勾选框，但是文章页下面的评论区域却不会出现勾选框

**环境信息**
PHP 版本：7.1.3
Kratos 版本：3.1.6
WordPress 版本：5.3.4

**复现步奏**

https://cn.wordpress.org/plugins/google-captcha/
安装上面的插件就后到下面这个网址就可以看到了，
https://www.sharpgan.com/convert-thousands-of-prometheus-metrics-to-grafana-query-statement/
我查看网页源码，发现recaptcha的js根本没有加载进文章页，谷歌了一下，有很多说是因为主题的footer.php没有调用wp_footer()这个函数，我去看了一下，kratos是调用的了，那就不知道该怎么办了，麻烦抽空看看怎么解决哈~

**Comment by Lvshujun0918** [comment]
应该是因为国内谷歌被墙了，不是主题问题吧

**Comment by supersu097** [comment]
> 应该是因为国内谷歌被墙了，不是主题问题吧

已经手动把插件内的url替换为recaptcha的国内镜像啦，况且wp-login页面可以正常使用呢~

**Comment by ohotto** [comment]
我也遇到这个问题了，只有登录页生效了，评论区没有生效，请问楼主解决了没呢？

**Comment by seatonjiang** [comment]
主题的评论那里自定义了，应该是插件找不到位置了

**Comment by seatonjiang** [comment]
Issues 功能即将关闭，请转移到 Discussions 继续讨论，https://github.com/vtrois/kratos/discussions
