### ISSUE TITLE
下个版本加上（恢复）首页幻灯片功能吧~~

### ISSUE THREAD

**Issue by 404gods** [seatonjiang/kratos#283]
下个版本加上（恢复）首页幻灯片功能吧~~
谢谢谢谢
这样用颜色导航才不会显得单调~~~

**Comment by seatonjiang** [comment]
首页轮播将在 v3.2.0 中推送，下面是动图

![image](https://camo.githubusercontent.com/41d1b858183ad2db42280cf785786c9680841efd/68747470733a2f2f73312e617831782e636f6d2f323032302f30392f33302f3075636e5a342e676966)
