### ISSUE TITLE
页面和文章中的SEO设置始终不会生效

### ISSUE THREAD

**Issue by ghost** [seatonjiang/kratos#284]
**问题描述**

页面和文章中的SEO设置,描述/关键词设置好,点击更新,页面刷新后,对应文本框值被清空,在对应文章或页面查看调用key和description是主题设置中的收录配置的内容,也确实没有生效

**环境信息**

PHP 版本：7.4.9
Kratos 版本：3.1.6
WordPress 版本：5.5.1
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

**复现步奏**

没有做特别操作,就是正常的新增文章/页面,修改文章/页面,然后发布/更新.

**Comment by seatonjiang** [comment]
问题修复了，等新版本推送即可
