### ISSUE TITLE
主题无法删除

### ISSUE THREAD

**Issue by kevin-zhu-ca** [seatonjiang/kratos#285]
**问题描述**
无法从后台删除主题

**环境信息**
PHP 版本：7.4.9
Kratos 版本：3.1.6
WordPress 版本：5.5.1
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

**复现步奏**
1. 原主题版本为3.1.1，测试可以正常删除
2. 下载release中的3.1.6版本
3. 上传主题升级到3.1.6，可以正常使用 （也测试过先完整删除3.1.1，然后全新安装3.1.6）
4. 在后台主题中切换到其他主题，尝试删除Kratos，报错：Deletion failed: 请求的主题不存在。
5. wp-content/themes中主题目录为 kratos-3.1.6，未被删除

猜测这个问题与新版本调整目录结构有关~请作者调查一下 谢谢~

**Comment by seatonjiang** [comment]
上传主题使用后台上传，不要FTP上传，可能会导致权限有问题。

**Comment by kevin-zhu-ca** [comment]
@seatonjiang 已经解决了，感谢~
