### ISSUE TITLE
博客页面显示突然不正常了

### ISSUE THREAD

**Issue by bruceluo111** [seatonjiang/kratos#286]
**问题描述**
前段时间博客首页显示突然有问题了，顶部图片只显示部分，顶部按钮也跑到左上角变成蓝色的文字，像超链接一样，首页特色图片也变的很大，总之就是看不出有应用主题，就是大图片加文字超链接的感觉，看了下树莓派的SD卡空间也足够，连接的硬盘空间也够，清空浏览器缓存换浏览器，还是显示有问题。
我是在树莓派3B+上用LAMP搭的wordpress博客

[**环境信息**](url)

将主题设置—>关于主题中「基础信息」的内容粘贴到这里。
PHP 版本：7.3.14-1~deb10u1
Kratos 版本：3.0.9
WordPress 版本：5.4.1
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

**复现步奏**
之前几个月没有任何显示问题
一段时间没看，前段时间看博客，发现页面就变得跟文字超链接加图片的感觉一样

**Comment by seatonjiang** [comment]
升级一下最新版本，你那应该是静态资源获取不到了，参考 https://github.com/vtrois/kratos/issues/267
