### ISSUE TITLE
请问段落首行如何缩进

### ISSUE THREAD

**Issue by wyw2012** [seatonjiang/kratos#290]
您好，我很喜欢你的主题。我之前使用你的2.4版本的，首行是自动缩进的，昨天升级到最新的版本3.1.7，发现首行无法自动缩进。我修改了kratos.css，添加了 text-indent:2em; 但是依然没有效果。请问有什么方式可以自动缩进吗？
.k-main .details .article .content p {
  color: #151515;
  line-height: 30px;
  text-indent:2em;
}

**Comment by seatonjiang** [comment]
自定义代码写到 `custom/custom.css`

**Comment by wyw2012** [comment]
> 自定义代码写到 `custom/custom.css`

谢谢，果然有效果。
