### ISSUE TITLE
3.1.7版本在IE 11下右下角图标显示异常

### ISSUE THREAD

**Issue by wyw2012** [seatonjiang/kratos#291]
您好，我在3.1.7版本发现一个问题，在IE 11浏览器下发现右下角的图片显示有问题，以及“下一页”也不显示，chrome和edge浏览器都正常。请问有办法解决吗？
PHP 版本：5.5.30
Kratos 版本：3.1.7
WordPress 版本：5.1.6
![image](https://user-images.githubusercontent.com/8927346/94342936-3e219b80-0047-11eb-8405-ffe4590b8e88.png)

**Comment by seatonjiang** [comment]
看一下字体资源是不是正常加载了，不建议使用IE浏览器，IE可能还会出现其他问题

**Comment by wyw2012** [comment]
谢谢指引，我猜应该也是iconfont未能正常加载的缘故，目前不知何种原因造成。不过也不关心它了，Chrome浏览器能用就行。
