### ISSUE TITLE
如此完美的主题竟出现了一丝不完美！！强迫症如坐针毡转转反侧夜不能寐，，关于LOGO尺寸

### ISSUE THREAD

**Issue by axjuan** [seatonjiang/kratos#296]
**问题描述**
经过反复测试，LOGO尺寸最大好像是100*60，希望LOGO醒目一点做到60*60，再放网站名称的话就只有40像素的宽度了，非常拥挤，不美观，，，
我看现在的LOGO尺寸在平板和手机状态下都可以适当长一些，不影响整体布局，，
希望作者前辈可以适当加宽LOGO尺寸，最好能增加60PX-100px
拜谢！
**环境信息**
PHP 版本：5.6.40
Kratos 版本：3.2.0
WordPress 版本：5.4.2
User Agent 信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**复现步奏**

**Comment by axjuan** [comment]
刚才又测试了一下，长度大于100PX就会自动缩小
我也想过把网站名字放在图标下面，高度可以设置的比较高比如100px，但是稍微长一些下面的页面显示就会被遮挡了，，

**Comment by seatonjiang** [comment]
每个人的logo尺寸不同，这里建议自定义修改代码，添加到 custom/custom.css 使其生效

**Comment by seatonjiang** [comment]
PC 端的 Logo 尺寸调整到宽 168px 了，移动端调整到了 130px，可以满足大部分的情况。

![image](https://user-images.githubusercontent.com/57834639/102035985-bd2fa000-3dfc-11eb-943b-f4077b86640d.png)
![image](https://user-images.githubusercontent.com/57834639/102036006-c91b6200-3dfc-11eb-9d20-9ce7d9394d31.png)
