### ISSUE TITLE
建议整合自动给页面添加html后缀的功能

### ISSUE THREAD

**Issue by DreamFerry** [seatonjiang/kratos#297]
伪静态链接对搜索引擎更加友好，并且很多CDN默认是仅缓存静态页面的，即html为后缀的页面，文章尚可通过修改固定链接比较方便的完成修改，但这个设置并不会作用于页面，每次升级完主题后，由于functions.php文件被覆盖，我都要不厌其烦的去添加
```
add_action('init', 'html_page_permalink', -1);
function html_page_permalink() {
    global $wp_rewrite;
    if ( !strpos($wp_rewrite->get_page_permastruct(), '.html')){
        $wp_rewrite->page_structure = $wp_rewrite->page_structure . '.html';
    }
}
```
以实现给页面链接自动添加html后缀的功能。
我希望主题能够集成修改文章及页面链接后缀的功能，这项功能大有裨益并且不会使主题臃肿多少。

**Comment by seatonjiang** [comment]
这段代码会对一些自定义固定链接不兼容，并不是所有的配置都适用。

**Comment by DreamFerry** [comment]
这段代码是我自用的，适合我自己的情况，我这里贴出这段代码是辅助说明，并非是要求将这段代码给整合进主题。WP自带的固定链接设置只对文章的链接起作用，不能应用于页面的链接。我希望主题设置里增加一项可以设置页面链接后缀的功能

**Comment by seatonjiang** [comment]
这个功能建议配合插件来实现，主题中不做添加。
