### ISSUE TITLE
建议：未登录时右侧侧边栏，博主头像请取消超链接到后台登录网址

### ISSUE THREAD

**Issue by wkingnet** [seatonjiang/kratos#298]
建议：未登录时右侧侧边栏，博主头像请取消超链接到后台登录网址。

由于可能会被暴力穷举破解管理员密码，即使密码够复杂无法破解，但也是一个造成DOS攻击的点。所以建议取消博主头像请取消超链接到后台登录网址，或者加个选项是否链接。

**Comment by seatonjiang** [comment]
加了一个控制选项
![image](https://user-images.githubusercontent.com/57834639/97125095-b629d100-176d-11eb-86ff-76c8a0b72b0a.png)
