### ISSUE TITLE
回复用户的留言时，插入图片不显示

### ISSUE THREAD

**Issue by gimgoo** [seatonjiang/kratos#301]
用户留言后，我回复用户，测试了两种，一种是只回复图片，用了img标签，另一种是先写一行中文，然后再插入img标签，但是最后都是不显示图片的，而是，除了中文外，图片那些都是html标签

**Comment by seatonjiang** [comment]
WordPress 出于安全考虑默认禁止了一些 html 标签，你可以自己通过 $allowedtags 加上参考

https://github.com/WordPress/WordPress/blob/cfa1fb8c83bf8bede92dfcb95619b2908fadc7bd/wp-includes/kses.php#L414-L446
