### ISSUE TITLE
特色图片尺寸在PC段和手机端比例不一致

### ISSUE THREAD

**Issue by zhangzixun** [seatonjiang/kratos#302]
**问题描述**

特色图片
1）在PC端尺寸为：234x139，234/139=1.6834532
2）在手机端尺寸为：429x228，429/228=1.881579
3）默认图片尺寸为：750x400，750/400=15/8=1.875

**环境信息**

PHP 版本：7.2.15
Kratos 版本：3.2.1
WordPress 版本：4.9.4
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

**复现步奏**

上传任意特色图片，在不同的客户端会被裁减到相应尺寸。
由于比例不一致，对于有边框或图形靠近边缘的图片，裁减将导致图片在不同客户端显示效果不佳。

**Comment by zhangzixun** [comment]
显示效果不佳的情况，效果参考以下网址：
[https://www.lean.org.cn](url)

**Comment by seatonjiang** [comment]
![image](https://user-images.githubusercontent.com/57834639/99931147-6417a380-2d4b-11eb-902f-6ee2a8f726cc.png)

参考一下这里的比例，手机端的尺寸不是固定的

**Comment by zhangzixun** [comment]
> ![image](https://user-images.githubusercontent.com/57834639/99931147-6417a380-2d4b-11eb-902f-6ee2a8f726cc.png)
> 
> 参考一下这里的比例，手机端的尺寸不是固定的

实测1.875:1效果比较好，也就是750:400=15:8=(16-1)/(9-1)

**Comment by seatonjiang** [comment]
新版本优化了一下特色图的默认比例，固定为 16:9 ，如果上传的图片尺寸不正确，将自动裁剪一张符合的图片，PC 端和移动端的图片尺寸将在任何尺寸保持一致。
