### ISSUE TITLE
请教下首页和列表页缩略图调用的问题

### ISSUE THREAD

**Issue by vbskycn** [seatonjiang/kratos#303]
老大你好，想请教下首页和列表页缩略图调用的问题
目前首页和列表页开启了显示特色图
但是不会调用缩略图，会显示大图，1个图片100多K，导致页面打开很慢
后台检查了下，是有正常生成的
但是我的不会正常调用缩略图
能指点下吗，是设置问题还是其它问题呢
https://www.zhoujie218.top/     
mailto:zhoujie218@gmail.com

**Comment by seatonjiang** [comment]
我记得之前是去掉了缩略功能的，防止有些图片在 PC 和手机端显示不一致的问题，建议是上传图片的时候自己先进行压缩再上传。

**Comment by vbskycn** [comment]
好的，感谢回复，明白怎么修改了，谢谢！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vtrois/kratos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月23日(星期一) 中午1:21
收件人:&nbsp;"vtrois/kratos"<kratos@noreply.github.com&gt;;
抄送:&nbsp;"开心每一天"<88164962@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vtrois/kratos] 请教下首页和列表页缩略图调用的问题 (#303)





 
我记得之前是去掉了缩略功能的，防止有些图片在 PC 和手机端显示不一致的问题，建议是上传图片的时候自己先进行压缩再上传。
