### ISSUE TITLE
bilibili 视频无法播放

### ISSUE THREAD

**Issue by zhangzixun** [seatonjiang/kratos#304]
**问题描述**

bilibili 视频无法播放
[bilibili]https://www.bilibili.com/video/BV1KK41137zu[/bilibili]

https://www.lean.org.cn/just-in-time/

**环境信息**

PHP 版本：7.2.15
Kratos 版本：3.2.1
WordPress 版本：4.9.4
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

**复现步奏**

1）修订文章
2）加入代码 [bilibili]https://www.bilibili.com/video/BV1KK41137zu[/bilibili]
3）确认发布

**Comment by seatonjiang** [comment]
试试这个代码

[bilibili]BV1KK41137zu[/bilibili]

**Comment by zhangzixun** [comment]
> 试试这个代码
> 
> [bilibili]BV1KK41137zu[/bilibili]

这个代码有效，赞！

不过，话又说回来。既然bilibili官方最方便复制的是链接，可否考虑同时兼容链接和特征码？这样，可以提高发视频的效率，同时也可以减少小白的出错率。

**Comment by seatonjiang** [comment]
这个问题到时候发一个说明书吧，一直都是这样调用的。
