### ISSUE TITLE
3.2.3版本logo变大遮挡住了下面的页面

### ISSUE THREAD

**Issue by EastonSun** [seatonjiang/kratos#308]
**问题描述**
更新3.2.3版本后网站logo变大，导航栏高度也发生了变化，遮挡住了下面的页面。
**环境信息**
PHP 版本：7.4.12
Kratos 版本：3.2.3
WordPress 版本：5.6
**复现步奏**
wordpress后台更新主题版本，更新后发现logo比上一版大，导航栏高度也变大了，遮挡住了下面的页面。
![主题](https://user-images.githubusercontent.com/52378245/102084308-f2b1a900-3e4f-11eb-9fa4-39ad19496ade.png)

**Comment by seatonjiang** [comment]
网站地址发一下

**Comment by dd0072** [comment]
https://www.eyunbook.com

**Comment by seatonjiang** [comment]
你这个图片有点高，建议自己添加一下代码吧，改下面两个数

```
.k-nav .navbar-brand img {
    width: xxpx;
}

@media screen and (max-width: 768px){
    .k-nav .navbar-brand img {
        width: xxpx;
    }
}
```

**Comment by EastonSun** [comment]
> 你这个图片有点高，建议自己添加一下代码吧，改下面两个数
> 
> ```
> .k-nav .navbar-brand img {
>     width: xxpx;
> }
> 
> @media screen and (max-width: 768px){
>     .k-nav .navbar-brand img {
>         width: xxpx;
>     }
> }
> ```

如果我不想改代码，图片尺寸应该多少合适？

**Comment by seatonjiang** [comment]
建议 168*22 的图片，你那个 Logo 设计的是正方的，我这设计的时候是按长条形做的。

**Comment by EastonSun** [comment]
OK，懂了
