### ISSUE TITLE
大图片加上说明文字后，会撑破页面

### ISSUE THREAD

**Issue by arbennp** [seatonjiang/kratos#309]
**问题描述**
插入媒体库的图片，选择图片的尺寸为完整大小。如果不添加图片说明，图片即使很大（比如2000像素宽度）， 显示的时候也会限制为文章页面的宽度。如果给图片添加了说明，图片在文章中显示时就会撑破页面。
使用Gutenberg编辑器插入图片时，给大图片加上图片说明，可以正常显示，不会撑破页面。
请问是我操作的问题吗？如果不使用Gutenberg编辑器，有什么方法可以避免这个问题？
“图片说明”是我很想用的功能。

**环境信息**
PHP 版本：7.2.24
Kratos 版本：3.2.3
WordPress 版本：5.6
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**复现步奏**
编辑文章，使用“添加媒体”插入图片，在媒体库中选择图片。
在“附件详情”的“说明”栏中，输入图片说明文字。
“尺寸”选择“完整尺寸（1920*1080)。
将图片插入文章。

**Comment by seatonjiang** [comment]
问题修复了，等下次更新即可。
