### ISSUE TITLE
请问//cdn.bootcss.com/ 想着的js 和css 相关的设置代码在哪里

### ISSUE THREAD

**Issue by panw3i** [seatonjiang/kratos#31]
id='highlight_css-css'  href='//cdn.bootcss.com/highlight.js/9.10.0/styles/github.min.css?ver=1.6'

没有找到

**Comment by Vtrois** [comment]
这是想要改啥，说的再具体点呢？

**Comment by ghost** [comment]
主题目录的 functions.php 中有一个 Load scripts 方法，主题加载资源在这里控制。
