### ISSUE TITLE
Plugin: jQuery is not defined

### ISSUE THREAD

**Issue by lirc572** [seatonjiang/kratos#310]
**问题描述**

[cardoza-3d-tag-cloud](https://wordpress.org/plugins/cardoza-3d-tag-cloud/)插件在`wp_head` hook里调用`jQuery`导致出错: `Uncaught ReferenceError: jQuery is not defined`

或许kratos可以改用wp内置的jquery？<https://pippinsplugins.com/why-loading-your-own-jquery-is-irresponsible/>

**复现步奏**

- 安装kratos主题
- 安装[cardoza-3d-tag-cloud](https://wordpress.org/plugins/cardoza-3d-tag-cloud/)插件
- 查看console

**Comment by seatonjiang** [comment]
这个问题是插件的资源引入不规范导致的，自定义的 jQuery 加载在 <head> 中，理论上其他任何 JS 文件都要加载到 <body> 的最下面，但是这个插件将 JS 文件加载到了 jQuery 之前，导致的报错。

**Comment by lirc572** [comment]
谢谢！改了改插件解决了! :beer:
