### ISSUE TITLE
文章内容中行结尾处英文单词会被拆分换行

### ISSUE THREAD

**Issue by lirc572** [seatonjiang/kratos#311]
**问题描述**

如题，我觉得下面几个地方应该改成`word-break: normal`

https://github.com/vtrois/kratos/blob/9a1ea54c7d2e0c0b6a0cd324e268b4da3bcc534d/assets/css/kratos.css#L819
https://github.com/vtrois/kratos/blob/9a1ea54c7d2e0c0b6a0cd324e268b4da3bcc534d/assets/css/kratos.css#L889
https://github.com/vtrois/kratos/blob/9a1ea54c7d2e0c0b6a0cd324e268b4da3bcc534d/assets/css/kratos.css#L988
https://github.com/vtrois/kratos/blob/9a1ea54c7d2e0c0b6a0cd324e268b4da3bcc534d/assets/css/kratos.css#L1091

**Comment by seatonjiang** [comment]
有两处可以改为 break-word，其他的不需要改。
![image](https://user-images.githubusercontent.com/57834639/102450447-5e269100-4071-11eb-9aba-929377a377e8.png)
