### ISSUE TITLE
希望评论区增加图形验证码开启的小功能

### ISSUE THREAD

**Issue by yenyoong99** [seatonjiang/kratos#313]
**问题描述**
发现文章评论被人发布大量广告，恶意内容，垃圾评论等，恶意刷留言区等显现。

**环境信息**
-

**复现步奏**
-

**Comment by goodDOS** [comment]
可以用Advanced noCaptcha & invisible Captcha插件

**Comment by nanguoyu** [comment]
Hi @yenyoong99 , 可以试试Akismet反垃圾评论插件。

**Comment by seatonjiang** [comment]
Issues 功能即将关闭，请转移到 Discussions 继续讨论，https://github.com/vtrois/kratos/discussions
