### ISSUE TITLE
提一个小小的建议，可不可以增加文章区域的宽度

### ISSUE THREAD

**Issue by wabcwell** [seatonjiang/kratos#315]
首先感谢大佬提供这么好用的主题，，写博客简单舒服

然后提一个小小的建议，可不可以增加文章区域的宽度
目前的文章区域的宽度有点小，，看着怪别扭的。
如果可以增加个10%就好了

再次感谢~

**Comment by chairwarmer** [comment]
赞成可以调整区域宽度

**Comment by seatonjiang** [comment]
Issues 功能即将关闭，请转移到 Discussions 继续讨论，https://github.com/vtrois/kratos/discussions
