### ISSUE TITLE
用codecolorer在这个主题，代码块行号显示有问题

### ISSUE THREAD

**Issue by chairwarmer** [seatonjiang/kratos#316]
**问题描述**

![image](https://user-images.githubusercontent.com/53132113/103171569-45e01e80-4888-11eb-9fa7-67fb75585590.png)

**Comment by CodFrm** [comment]
editor.md也是,只能自己手动修改样式了

https://github.com/vtrois/kratos/blob/main/assets/css/kratos.css#L1003

**Comment by seatonjiang** [comment]
刚刚试着装这个插件，报错了。。。

**Comment by CodFrm** [comment]
> 刚刚试着装这个插件，报错了。。。

editor.md么?我现在是将样式增加!important解决了,感觉还是挺丑陋的 😂 

![image](https://user-images.githubusercontent.com/22783163/103724905-676fa180-5010-11eb-93d4-4168663e98a1.png)

**Comment by seatonjiang** [comment]
高亮适配了 Enlighter 这个插件，可以试一下。
![image](https://user-images.githubusercontent.com/57834639/118944351-1214ab00-b987-11eb-9dd9-4c60c5c7732e.png)
