### ISSUE TITLE
腾讯的防水墙评论不兼容，没显示出来。这个能兼容进去么。还是要自己在哪里修改呀。

### ISSUE THREAD

**Issue by Lockey-J** [seatonjiang/kratos#317]
**问题描述**
腾讯的防水墙评论不兼容，没显示出来。这个能兼容进去么。还是要自己在哪里修改呀。
**环境信息**
PHP 版本：7.3.19-1~deb10u1
Kratos 版本：3.2.4
WordPress 版本：5.6
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66
**复现步奏**
增加防水墙插件，启用后评论无显示

**Comment by seatonjiang** [comment]
这个问题在看了，是评论那里的问题，跟谷歌防水墙一起修复。

**Comment by seatonjiang** [comment]
目前已经新增了后台登录的腾讯云验证，后期会添加评论的验证，统一在 #313 中答复，这个问题暂时关闭。
