### ISSUE TITLE
自定义设置的顶部设置，上传顶部图片失败。

### ISSUE THREAD

**Issue by JustinhoCHN** [seatonjiang/kratos#318]
**问题描述**
自定义设置的顶部设置，上传顶部图片失败。每次点击上传媒体里面的图片或者图床的url链接，保存设置后图片消失，没有生效
![微信截图_20201231164017](https://user-images.githubusercontent.com/24873787/103402232-33ffc380-4b87-11eb-9746-4ae3fb267979.png)

![微信截图_20201231164347](https://user-images.githubusercontent.com/24873787/103402256-614c7180-4b87-11eb-944f-6c583399821e.png)

顶部图片依然保持原来主题的图，无法更换。

**环境信息**

PHP 版本：7.2.34
Kratos 版本：3.2.4
WordPress 版本：5.6
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**复现步奏**

**Comment by seatonjiang** [comment]
我这里无法复现这个问题，你看一下是不是后台有什么插件冲突了？改别的都正常吗？

**Comment by seatonjiang** [comment]
这个问题应该是你那里的问题，现在暂时关闭，如果再遇到这样的问题，及时反馈。
