### ISSUE TITLE
主题请求加入日文

### ISSUE THREAD

**Issue by OvO-nei** [seatonjiang/kratos#326]
我可以帮忙翻译。合并到主线上。是否可以呢

**Comment by seatonjiang** [comment]
https://vtrois.crowdin.com/kratos/ja  新增了翻译，你可以去这里提交翻译内容，提交完成自动推送到项目里。

**Comment by OvO-nei** [comment]
Hi 逐句翻译工程量裂开，我偷了个懒，用poedit Pro+人工直接做出语言文件，已经pull了。大佬康康没问题可以合并试试看。
感谢

**Comment by seatonjiang** [comment]
我先合并到crowdin里面
