### ISSUE TITLE
希望可以增加顶部菜单

### ISSUE THREAD

**Issue by 1354961639** [seatonjiang/kratos#327]
如题，虽然主题自带图片和纯色的头部，但是自带的顶部菜单无法显示了，希望可以自定义是否可以显示顶部菜单。
![QQ截图20210127222206](https://user-images.githubusercontent.com/22723142/106004393-225dfd00-60ee-11eb-9cf2-a1871fd2644c.png)

**Comment by seatonjiang** [comment]
![image](https://user-images.githubusercontent.com/57834639/106005676-66053680-60ef-11eb-9035-11d7aae57517.png)

没问题啊，铁汁

**Comment by 1354961639** [comment]
我的锅。。。。。我把顶部设置成白色，导致看不到字了 :(
