### ISSUE TITLE
网易云音乐播放器修复

### ISSUE THREAD

**Issue by cinwellrao** [seatonjiang/kratos#33]
function wymusic($atts, $content=null, $code="") {
    $return = '<iframe class="" style="width:100%" frameborder="no" border="0" marginwidth="0" marginheight="0" height=86 src="//music.163.com/outchain/player?type=2&id=';
    $return .= $content;
    $return .= '&auto='. kratos_option('wy_music') .'&height=66"></iframe>';
    return $return;
}
add_shortcode('music' , 'wymusic' );

**Comment by ghost** [comment]
Done
