### ISSUE TITLE
无法使用哔哩哔哩的视频和youtube的视频

### ISSUE THREAD

**Issue by 30115776** [seatonjiang/kratos#330]
**问题描述**

无法使用哔哩哔哩的视频和youtube的视频
[bilibili]https://www.bilibili.com/video/BV1gJ411n7j4?from=search&seid=9372568807423811950[/bilibili]
[bilibili]https://www.bilibili.com/video/BV1gJ411n7j4[/bilibili]

都不行

**环境信息**

PHP 版本：8.0.1
Kratos 版本：3.2.5
WordPress 版本：5.6.1
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**复现步奏**

**Comment by seatonjiang** [comment]
[bilibili]BV1gJ411n7j4[/bilibili]
