### ISSUE TITLE
3.2.6 升级后fontawesome的图标显示异常

### ISSUE THREAD

**Issue by Lockey-J** [seatonjiang/kratos#333]
**问题描述**
3.2.5升级到3.2.6后，原先菜单栏能正常显示fontawesome变成5.15.2。现在图标全是一个方框的。退回3.2.5跟fontawesome5.13就又正常
**环境信息**
PHP 版本：7.3.19-1~deb10u1
Kratos 版本：3.2.5
WordPress 版本：5.6.1
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
**复现步奏**
升级到3.2.6

**Comment by seatonjiang** [comment]
问题修复了，下个版本同步。
