### ISSUE TITLE
youtube 视频无法播放

### ISSUE THREAD

**Issue by kkwow** [seatonjiang/kratos#337]
![image](https://user-images.githubusercontent.com/15723157/109126335-19615980-7788-11eb-9dea-d1a8f6889103.png)

内容格式：[youtube]https://www.youtube.com/watch?v=7_QWG79SHpM[/youtube]
梯子正常。

**Comment by kkwow** [comment]
![image](https://user-images.githubusercontent.com/15723157/109126817-a6a4ae00-7788-11eb-8968-65044aecd5ed.png)

官网嵌入 正常。

**Comment by seatonjiang** [comment]
[youtube]7_QWG79SHpM[/youtube]

**Comment by kkwow** [comment]
非常感谢！！！
