### ISSUE TITLE
能否新增一个功能，优化搜索

### ISSUE THREAD

**Issue by yaociyuan** [seatonjiang/kratos#338]
wordpress在默认搜索时，会搜索文章的内容

在主题量过大时，搜索会卡死

// 只搜索文章标题
function wpse_11826_search_by_title( $search, $wp_query ) {
    if ( ! empty( $search ) && ! empty( $wp_query->query_vars['search_terms'] ) ) {
        global $wpdb;
        $q = $wp_query->query_vars;
        $n = ! empty( $q['exact'] ) ? '' : '%';
        $search = array();
        foreach ( ( array ) $q['search_terms'] as $term )
            $search[] = $wpdb->prepare( "$wpdb->posts.post_title LIKE %s", $n . $wpdb->esc_like( $term ) . $n );
        if ( ! is_user_logged_in() )
            $search[] = "$wpdb->posts.post_password = ''";
        $search = ' AND ' . implode( ' AND ', $search );
    }
    return $search;
}
add_filter( 'posts_search', 'wpse_11826_search_by_title', 10, 2 );

在functions.php 内添加代码可以解决

但是每次更新主题，文件就会被覆盖

能否集成这种功能，或者添加一个 functions.php 已定义的主题设置选项功能

**Comment by seatonjiang** [comment]
感谢反馈，已经添加了这个功能，下个版本可以使用了。
