### ISSUE TITLE
建议手机界面也做成和pad一样

### ISSUE THREAD

**Issue by 100234** [seatonjiang/kratos#339]
多谢开发者的辛苦付出，提一个小建议仅供参考，希望手机界面布局也做成和pad一样，一行文章左边缩略图右边文章标题和少许开头，目前上图下文的模式非常占空间，一屏幕只能显示两个文章。再次感谢
![image](https://user-images.githubusercontent.com/12790468/109693030-246f1c00-7bc4-11eb-91ac-c4e1ce74feeb.png)

**Comment by seatonjiang** [comment]
手机考虑的是一些小屏幕，如果这样显示的话，字体啥都看不清了
