### ISSUE TITLE
文章评论前端不兼容require_name_email wp_option（评论作者必须填入姓名和电子邮件地址）

### ISSUE THREAD

**Issue by n0099** [seatonjiang/kratos#340]
**问题描述**
https://github.com/vtrois/kratos/blob/e22d746a4176cf4a4feea8006dc77acf21c7ca06/comments.php#L37
https://github.com/vtrois/kratos/blob/e22d746a4176cf4a4feea8006dc77acf21c7ca06/comments.php#L45
处的required属性为硬编码，不会跟随[require_name_email选项](https://developer.wordpress.org/apis/handbook/options/)值而变动

**环境信息**
PHP 版本：7.4.12
Kratos 版本：3.2.7
WordPress 版本：5.6.2
User Agent 信息：Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.7 Safari/537.36

**复现步奏**
1. 在wp-admin/options-discussion.php中取消`评论作者必须填入姓名和电子邮件地址`
2. 在任意可评论文章尝试评论

**Comment by seatonjiang** [comment]
这里改了一下，后台可控了，前端会弹窗报错了

![image](https://user-images.githubusercontent.com/57834639/110564796-6b42b000-8188-11eb-9974-b7377b14c467.png)

![image](https://user-images.githubusercontent.com/57834639/110564701-42bab600-8188-11eb-85d1-3c4ad1eeac61.png)
