### ISSUE TITLE
文章页作者头像不被gravatar.loli.net加速

### ISSUE THREAD

**Issue by n0099** [seatonjiang/kratos#342]
**问题描述**
主题设置开启多用户模式后文章页下方作者信息部分头像url不会受加速gravatar主题设置影响，仍然为secure.gravatar.com，而评论用户头像url域已被替换为gravatar.loli.net

**环境信息**
PHP 版本：7.4.12
Kratos 版本：3.2.7
WordPress 版本：5.6.2
User Agent 信息：Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.7 Safari/537.36

**复现步奏**
1. 主题设置开启`在文章列表显示当前文章作者，在文章页面页脚显示当前作者介绍`
2. 主题设置开启`开启 Gravatar 头像加速`

**Comment by n0099** [comment]
https://github.com/vtrois/kratos/blob/b0ae3c9491feca6c6f4fe5142db5ef3e73981b81/pages/page-toolbar.php#L12
可能[`get_avatar_url`](https://developer.wordpress.org/reference/functions/get_avatar_url/)不受[`get_avatar` hook](https://developer.wordpress.org/reference/hooks/get_avatar/)的影响

建议尝试在https://github.com/vtrois/kratos/blob/2f22474b11b33e39bd9380d7d8e57615dbbd496a/inc/theme-core.php#L183 处再加入[`pre_get_avatar` hook](https://developer.wordpress.org/reference/hooks/pre_get_avatar/)

**Comment by n0099** [comment]
`add_filter('get_avatar_url', 'get_https_avatar');`

**Comment by seatonjiang** [comment]
感谢反馈，这个问题已经修复了，已经去掉了站长配置，可以更简单的配置博客了。
