### ISSUE TITLE
建议允许用户决定是否关闭wp的文章自动保存、修订版本功能

### ISSUE THREAD

**Issue by n0099** [seatonjiang/kratos#344]
**问题描述**
https://github.com/vtrois/kratos/blob/d6a4ecf5b70e8073d0b6a19312bb5a00d407cc1a/inc/theme-core.php#L99-L100
虽然自动保存会刷很多postid，但总比误关了浏览器文章修改丢失了好

**Comment by seatonjiang** [comment]
新增了这个功能，下个版本推送。
