### ISSUE TITLE
3.2.8 中取消了站长配置，请问要如何使用自定义头像？

### ISSUE THREAD

**Issue by g93920079** [seatonjiang/kratos#347]
**问题描述**

**环境信息**

**复现步奏**

**Comment by seatonjiang** [comment]
在用户 个人资料中进行配置即可
![image](https://user-images.githubusercontent.com/57834639/111019006-6afc1c00-83f7-11eb-9f46-4ccb1f384f55.png)

**Comment by g93920079** [comment]
> 在用户 个人资料中进行配置即可
> ![image](https://user-images.githubusercontent.com/57834639/111019006-6afc1c00-83f7-11eb-9f46-4ccb1f384f55.png)

谢谢大佬，已经搞定了
