### ISSUE TITLE
最新的3.2.8怎么修改站长头像呢？没有这个站长配置了，我修改了gravatar的头像，博客文章里面的也没有变

### ISSUE THREAD

**Issue by paulllb** [seatonjiang/kratos#349]
如何修改站长头像？
管理员在后台「主题设置」->「站长配置」页面，找到「个人头像」选项，点击「删除」按钮，再点击「上传」按钮，即可上传自定义的头像图片。提示：该图片显示在小工具「个人简介」以及文章内容页面最下方站长信息中。同时，输入框也可以直接输入外链的图片地址。

**Comment by paulllb** [comment]
![image](https://user-images.githubusercontent.com/36190147/111069378-cf0e0580-8507-11eb-8a25-838fb1e0b3a3.png)
![image](https://user-images.githubusercontent.com/36190147/111069384-d7fed700-8507-11eb-8692-0fc6a71973ed.png)
评论的时候可以显示自己的头像，但是博客页面没有

**Comment by g93920079** [comment]
设置-讨论里面把默认头像改为空白，而不是神秘人士

**Comment by icexmoon** [comment]
> 设置-讨论里面把默认头像改为空白，而不是神秘人士

哈哈哈，终于有头像了，不容易啊，多谢
