### ISSUE TITLE
切换不了官方的区块编辑器

### ISSUE THREAD

**Issue by lifengdi** [seatonjiang/kratos#351]
**问题描述**
使用主题之后，不能切换Gutenberg编辑器

**环境信息**
PHP 版本：7.0.33
Kratos 版本：3.2.8
WordPress 版本：5.7
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36

**复现步奏**
文章编辑页面
![image](https://user-images.githubusercontent.com/19971474/111121538-bd7c3a80-85a7-11eb-950e-c507e6f73d08.png)

**Comment by lifengdi** [comment]
主题设置那里已经开启了Gutenberg编辑器
![image](https://user-images.githubusercontent.com/19971474/111121823-1d72e100-85a8-11eb-8d08-bc81f431bf1a.png)

**Comment by seatonjiang** [comment]
我刚刚试了一下，没有问题啊，主题控制里面开启了之后就可以了啊

![image](https://user-images.githubusercontent.com/57834639/111644732-1283af00-883b-11eb-9db1-a6f51eb6d9d2.png)

**Comment by lifengdi** [comment]
是不是因为插件冲突的原因，我之前下载了一个叫经典编辑器的插件
![image](https://user-images.githubusercontent.com/19971474/111676840-8f258600-8859-11eb-98d6-451e1784c685.png)

还有一个Advanced Editor Tools (previously TinyMCE Advanced)这个插件
![image](https://user-images.githubusercontent.com/19971474/111676896-99e01b00-8859-11eb-8658-d905d3d2a85c.png)

但是我把这俩玩意儿禁用了也不行。。。很奇怪
