### ISSUE TITLE
How can I add a shortcode to index.php?

### ISSUE THREAD

**Issue by luisee** [seatonjiang/kratos#352]
Hello, sorry to write in English, how would be the way to put a shortcode in the **index.php,** I have tried things like this and many more

`<?php echo successbox($atts, $content = "[successbox title='Important']Lorem Lorem[/successbox]", $code = ""); ?> `

And the result is this:

<img width="770" alt="example_shorcode" src="https://user-images.githubusercontent.com/39359544/111526781-28a34980-872d-11eb-92c4-5b722bf0ff85.png">

🙋‍♂️ **I really appreciate the help, I need to put it in the index.**

**Comment by seatonjiang** [comment]
Is that what you want?

`echo do_shortcode("[successbox title='Important']Lorem Lorem[/successbox]");`

![image](https://user-images.githubusercontent.com/57834639/111643609-0d723000-883a-11eb-98ba-c4a727ba7d8d.png)

**Comment by luisee** [comment]
> Is that what you want?
> 
> `echo do_shortcode("[successbox title='Important']Lorem Lorem[/successbox]");`
> 
> ![image](https://user-images.githubusercontent.com/57834639/111643609-0d723000-883a-11eb-98ba-c4a727ba7d8d.png)

Right, I really appreciate the help.
