### ISSUE TITLE
开启Gutenberg编辑器写文章后发布出现致命错误提示

### ISSUE THREAD

**Issue by paulllb** [seatonjiang/kratos#353]
![image](https://user-images.githubusercontent.com/36190147/111644611-f54ee080-883a-11eb-8125-a1887b3fe5a3.png)
![image](https://user-images.githubusercontent.com/36190147/111644652-ff70df00-883a-11eb-90fa-59d69744c38f.png)

**Comment by paulllb** [comment]
可以加个微信不大兄弟

发自我的iPhone

**Comment by seatonjiang** [comment]
问题解决了吗，如果依旧有问题，可以参考 https://wordpress.org/support/article/debugging-in-wordpress/ ，把 debug 模式打开，看一下报错，现在这个问题暂时关闭，有任何问题请继续回复。
