### ISSUE TITLE
为啥用md插件编辑很好看，发布确很丑，需要设置啥吗。。代码都没办法高亮

### ISSUE THREAD

**Issue by paulllb** [seatonjiang/kratos#354]
![image](https://user-images.githubusercontent.com/36190147/111751298-4b6d6380-88cf-11eb-81ae-c5edd06ecfcf.png)
![image](https://user-images.githubusercontent.com/36190147/111751390-66d86e80-88cf-11eb-80d8-e30f179748d1.png)

**Comment by seatonjiang** [comment]
装一个代码高亮的插件吧

**Comment by icexmoon** [comment]
问下楼主用的哪个md插件，效果如何，我也想整一个。
还有，装了插件后已有文档显示受影响吗。

**Comment by seatonjiang** [comment]
高亮适配了 Enlighter 这个插件，可以试一下，后期文章样式还会有调整。
![image](https://user-images.githubusercontent.com/57834639/118944938-99621e80-b987-11eb-8beb-9f61c786dd91.png)
