### ISSUE TITLE
有些文章无法显示

### ISSUE THREAD

**Issue by likingzi** [seatonjiang/kratos#355]
**问题描述**
我启用了这个主题后，点击首页文章标题进入，发现有一些文章只能显示标题，没法显示详情，如图
![image](https://user-images.githubusercontent.com/8468677/111868601-da54ab80-89b5-11eb-8e72-45c8c277b74e.png)
只显示了标题，后面的内容没法显示，但有的文章却可以显示内容。

**环境信息**
PHP 版本：7.4.16
Kratos 版本：3.2.8
WordPress 版本：5.7
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4000.3 Safari/537.36

**复现步奏**
不知是啥原因呢？

**Comment by seatonjiang** [comment]
你这样说我也无法复现问题啊，先禁插件看看，是不是有冲突的，再把debug打开，看看下面没内容，肯定有报错

**Comment by likingzi** [comment]
谢谢，我刚才终于找到原因了，两天时间，是那个语法高亮插件“Crayon Syntax Highlighter”搞的鬼，刚才查了下，他也没有更新，禁用了就好啦！匆匆来这里回复，也看到了您的提示，之前咋一直就没想到插件搞鬼啊，害得我各种处理数据库缓存、升级wp核心、主题，嗨，谢谢啦，下一步仔细设置下您这个主题，发现是我想要的主题，很棒，再次表示感谢！
