### ISSUE TITLE
使用了WP Editor.md 插件无法将代码块，显示高亮，用了好几个高亮插件，都无法显示，有冲突！

### ISSUE THREAD

**Issue by bestxiaoxiaoming-hm** [seatonjiang/kratos#356]
**问题描述**

**环境信息**

**复现步奏**

**Comment by seatonjiang** [comment]
单独使用高亮插件是没有问题的，配合Editor.md使用有冲突的话，应该是高亮和Editor.md有冲突啊

**Comment by nyable** [comment]
我现在正在用`WP Editor.md`，语法高亮主题风格是：`Tomorrow Night`。印象中直接使用确实有些样式会因为样式冲突被覆盖导致无法正常显示，比如行号被代码块覆盖、文字被出现纯色边框、文本/背景颜色与主题不一致之类的问题，修改`WP Editor.md`插件对应css的应用优先级就可以正常显示了。
![image](https://user-images.githubusercontent.com/29651926/113801838-34ae8400-978c-11eb-8055-efe70ca654de.png)

**Comment by seatonjiang** [comment]
高亮适配了 Enlighter 这个插件，可以试一下。
![image](https://user-images.githubusercontent.com/57834639/118944351-1214ab00-b987-11eb-9dd9-4c60c5c7732e.png)
