### ISSUE TITLE
能加几个页脚社交图标不

### ISSUE THREAD

**Issue by icexmoon** [seatonjiang/kratos#359]
**问题描述**
![image](https://user-images.githubusercontent.com/13990857/113414242-26104780-93ef-11eb-8005-40ad1654b4e6.png)
作者的页脚图标做的很赞。
国内平台能多加几个不，比如豆瓣。
**环境信息**

**复现步奏**

**Comment by iamlvtu** [comment]
inc/theme-options.php 自己增加就可以了！

**Comment by icexmoon** [comment]
> inc/theme-options.php 自己增加就可以了！

好的，多谢，我只是考虑到版本更新的问题给作者提个建议

**Comment by seatonjiang** [comment]
添加了一个豆瓣的例子，后期如果需要添加图标，自己根据这次提交进行修改就行了。

**Comment by icexmoon** [comment]
> 添加了一个豆瓣的例子，后期如果需要添加图标，自己根据这次提交进行修改就行了。

非常感谢，我之前研究了半天iconfont后放弃了。。。发现要改一整套。。。

**Comment by seatonjiang** [comment]
是的，这里每个图标都是我自己画的
