### ISSUE TITLE
IIS环境下使用kratos主题

### ISSUE THREAD

**Issue by ixiaoqian** [seatonjiang/kratos#36]
IIS环境下使用kratos主题 访问 domain/wp-json 会出错，其它主题正常
`PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function '_return_false' not found or invalid function name in C:\inetpub\wwwroot\localhost\wordpress\wp-includes\class-wp-hook.php on line 298`

**Comment by TechCiel** [comment]
请至少给出PHP版本
 
 
------------------ Original ------------------
