### ISSUE TITLE
推荐一个音乐播放器插件

### ISSUE THREAD

**Issue by icexmoon** [seatonjiang/kratos#360]
**问题描述**
RT，并非问题反馈，发现一个和这个主题还算搭的音乐播放器插件，详情可以看我的博文
<https://blog.icexmoon.xyz/?p=84>
**环境信息**

**复现步奏**

**Comment by iamlvtu** [comment]
其实你可以考虑一下aplayer，操作简单多了

**Comment by icexmoon** [comment]
看了一下，好像差不多，主要这个支持播放列表，很多wp的音乐插件只能一首歌

**Comment by iamlvtu** [comment]
aplayer也支持列表的，而且支持多平台。。。

**Comment by icexmoon** [comment]
> aplayer也支持列表的，而且支持多平台。。。

好吧，有空了再研究
