### ISSUE TITLE
侧边小工具：文章聚合设置默认无效

### ISSUE THREAD

**Issue by Jomixedyu** [seatonjiang/kratos#361]
**问题描述**
侧边小工具：文章聚合，设置最新为默认展示无效，虽然选项卡焦点在最新，但内容还是默认为热点。

**环境信息**

    PHP 版本：7.0.33
    Kratos 版本：3.2.8
    WordPress 版本：5.3.6
    User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0

**复现步奏**
修改文章聚合小工具为最新

**Comment by seatonjiang** [comment]
问题修复了，将在下个版本进行推送更新。
