### ISSUE TITLE
颜色导航 - 颜色输入框 中输入任意信息回车，Wordpress出现致命错误

### ISSUE THREAD

**Issue by StarryVoid** [seatonjiang/kratos#362]
**问题描述**
Wordpress 此站点遇到了致命错误，请查看您站点管理员电子邮箱中收到的邮件来获得指引。

**环境信息**
PHP 版本：7.4.11
Kratos 版本：3.2.8
WordPress 版本：5.7
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36

**复现步奏**
主题设置 - 顶部配置 - 颜色导航 - 颜色输入框 中输入任意信息回车，配置保存同时出现问题错误提示
![图片](https://user-images.githubusercontent.com/20756365/114506451-629c3880-9c64-11eb-971e-7b833893d061.png)

**Comment by seatonjiang** [comment]
这里回车出错不是颜色选择器的问题，发送测试邮件的按钮也在同一个表单里，所以回车的时候会触发，现在把回车提交去掉了，手动点击保存配置就不会出这个问题了，下个版本推送更新。
