### ISSUE TITLE
[询问]主题设置 - 收录配置 - 统计代码 可以自行增加 async 等参数么？

### ISSUE THREAD

**Issue by StarryVoid** [seatonjiang/kratos#363]
PHP 版本：7.4.11
Kratos 版本：3.2.8
WordPress 版本：5.7
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36

--------

主题设置 - 收录配置 - 统计代码

在这里面写入的```<script src="https://www.googletagmanager.com/gtag/js?id=G-**********" ><script>``` 能否自行增加 async 等异步参数
效果如 ```<script async src="https://www.googletagmanager.com/gtag/js?id=G-**********" ><script>``` 所示

目前填入配置后，点击保存，再刷新，发现被清除掉 async 参数，无法写入。

**Comment by seatonjiang** [comment]
这个参数默认被过滤了，我在新版本中加上了，等下个版本推送即可，参考 [wp_kses](https://developer.wordpress.org/reference/functions/wp_kses/)
