### ISSUE TITLE
自动更新失败

### ISSUE THREAD

**Issue by jalena** [seatonjiang/kratos#364]
**问题描述**

更新失败：因为我们不能复制一些文件，升级未被安装。这通常是因为存在不一致的文件权限。

**环境信息**
```
PHP 版本：8.0.3
Kratos 版本：3.2.8
WordPress 版本：5.7.1
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
```

**复现步奏**

**Comment by seatonjiang** [comment]
这个是你目录权限配置的有问题

**Comment by jalena** [comment]
> 这个是你目录权限配置的有问题

目录权限是确保没问题，但新的问题又出来了！！！

老哥你发布更新的话能不能不要放完整包啊！！

我自定义了custom里面的东西，现在全让你的空文件覆盖了！！

**Comment by seatonjiang** [comment]
4个月之前就在这个目录里写了说明，建议用 git 控制

![image](https://user-images.githubusercontent.com/57834639/115137341-30217f80-a058-11eb-9225-0e49b20f5850.png)

**Comment by seatonjiang** [comment]
主题升级的逻辑是删除文件夹再安装

**Comment by jalena** [comment]
压根就没有跑这个目录看过！！！更没有打开readme！！

**Comment by icexmoon** [comment]
> 压根就没有跑这个目录看过！！！更没有打开readme！！

老哥淡定，搞一个测试环境和每天备份才是根本之道，开源产品你要学会折腾

**Comment by icexmoon** [comment]
> 压根就没有跑这个目录看过！！！更没有打开readme！！

所有的插件和主题我都是在测试环境安装没问题才会在正式环境安装的

**Comment by jalena** [comment]
> > 压根就没有跑这个目录看过！！！更没有打开readme！！
> 
> 所有的插件和主题我都是在测试环境安装没问题才会在正式环境安装的

已搞定。可以结案了！
