### ISSUE TITLE
能否优化一下前台的链接显示

### ISSUE THREAD

**Issue by icexmoon** [seatonjiang/kratos#367]
**问题描述**
目前前台链接样式用的是display:inline-block，两个一行，显示出来的效果不是很好。
![image](https://user-images.githubusercontent.com/13990857/115205157-d5595800-a12b-11eb-86bd-da9507fb0fe4.png)
我想要这样的现实效果。
目前我是通过css魔改了一下，不过还是有一些问题，比如底层li元素的宽度还是原来的。
附上我的css:
div.widget.widget_links ul.xoxo.blogroll li {<br />
    /**overflow: hidden;**/
    text-overflow: ellipsis;
    white-space: nowrap;
    display: block;
}
**环境信息**

**复现步奏**

**Comment by seatonjiang** [comment]
这里用过是有点问题，之前我写的是一行2个，一会儿我看一下这个问题

**Comment by seatonjiang** [comment]
期初设计的时候，没考虑很长名字的标题，理想情况是这样的，后面我在调整一下这里。

![image](https://user-images.githubusercontent.com/57834639/118581630-83583080-b7c4-11eb-8c5a-d1e012064715.png)

**Comment by icexmoon** [comment]
> 期初设计的时候，没考虑很长名字的标题，理想情况是这样的，后面我在调整一下这里。
> 
> ![image](https://user-images.githubusercontent.com/57834639/118581630-83583080-b7c4-11eb-8c5a-d1e012064715.png)

期待，可以加个开关选项，可以选择当前小组件使用一行两列或者一列的样式之类的。

**Comment by seatonjiang** [comment]
Issues 功能即将关闭，请转移到 Discussions 继续讨论，https://github.com/vtrois/kratos/discussions
