### ISSUE TITLE
我可以提交代码吗？提交代码有什么要求吗？

### ISSUE THREAD

**Issue by KeyboardMan1996** [seatonjiang/kratos#368]
最近在主题里加了一些可以给目录设置默认特色图表的代码，可以提交上来吗？对代码格式有没有什么要求？

**Comment by seatonjiang** [comment]
你把代码提过来，再把演示效果截图贴一下

**Comment by icexmoon** [comment]
> 最近在主题里加了一些可以给目录设置默认特色图表的代码，可以提交上来吗？对代码格式有没有什么要求？

给大佬点赞

**Comment by KeyboardMan1996** [comment]
代码已经推上去了。

> 你把代码提过来，再把演示效果截图贴一下

**Comment by seatonjiang** [comment]
已经合并了
