### ISSUE TITLE
页面 warning

### ISSUE THREAD

**Issue by ysmintor** [seatonjiang/kratos#37]
`Warning: Illegal string offset 'top' in /www/wwwroot/www.yorkyu.com/wp-content/themes/Kratos-2.5.5/single.php on line 40`

`Warning: Illegal string offset 'footer' in /www/wwwroot/www.yorkyu.com/wp-content/themes/Kratos-2.5.5/single.php on line 44`

测试地址：https://www.yorkyu.com/uncategorized/markdown-test.html

好像看了下提示是广告的问题，但我又发现重置广告配置后会把社交的配置也清了。并且没有解决这个问题。

```php
<?php if ($ad['top']==1): ?>
 <img src="<?php echo kratos_option('ad_img')?>">
 <?php endif ?>
 <?php the_content(); ?>
<?php if ($ad['footer']==1): ?>
<img src="<?php echo kratos_option('ad_img')?>">
```

我不懂PHP，只会JAVA，希望 @Vtrois 能解决下这些问题，优化一下发现的bug.

**Comment by ysmintor** [comment]
由于作者没有回复，自己想到注释一部发代码，应该是广告图片就没效果了。有这个问题的可以说按如下解决
找到single.php

修改40行代码如下
```html
<!--
<div class="kratos-post-content">
<?php if ($ad['top']==1): ?>
<img src="<?php echo kratos_option('ad_img')?>">
<?php endif ?>
-->
<?php the_content(); ?>
<!--
<?php if ($ad['footer']==1): ?>
<img src="<?php echo kratos_option('ad_img')?>">
<?php endif ?>
</div>
-->
```

希望重加载nginx配置，或者重启下nginx看效果。希望作者有时间解决下这个问题。

主要是要保留`<?php the_content(); ?>`这个才有内容出现。

**Comment by TechCiel** [comment]
尝试在第一个if之前加入`var_dump($ad);`查看一下warning前的dump结果以供反馈。

另外请先**重新安装**wp和主题至最新版，并**关闭其他插件**以防冲突，看问题是否复现。

**Comment by ysmintor** [comment]
@TechCiel 

是的40行的If前面加`<?php `var_dump($ad);`?>`这个吗？提示如下，插件全部关闭了，主题是github2.5的release下的最新的，不知怎么还提示要更新，可能是解压后没有2.5.5的后缀没有识别吧。
最后按提示更新 后的，访问页面出现的结果。接下来该做什么呢？

server用的阿里的Nginx -Tengine2.2.0
```shell
Warning: shell_exec() has been disabled for security reasons in /www/wwwroot/www.yorkyu.com/wp-content/themes/Kratos-2.5.5/single.php on line 40

Warning: Illegal string offset 'top' in /www/wwwroot/www.yorkyu.com/wp-content/themes/Kratos-2.5.5/single.php on line 41
```

**Comment by TechCiel** [comment]
第40行应为
<?php var_dump($ad); if ($.....
不知道为什么会提示shell exec
我在怀疑你的网站是否已遭入侵，如果数据不多建议后台导出数据，重装服务器。

**Comment by ysmintor** [comment]
@TechCiel 

我之前以为你的意思是40前加`<?phpvar_dump($ad);?>`
按你最新的代码修改后提示如下


```php
string(0) "" 
Warning: Illegal string offset 'top' in /www/wwwroot/www.yorkyu.com/wp-content/themes/Kratos-2.5.5/single.php on line 40
```

好像是ad数组没有数组然后取值出的问题，就好像是outofindex这样的错误，是这样的吗？

**Comment by TechCiel** [comment]
期望ad是数组，然而是个空字符串。
@Vtrois

**Comment by ysmintor** [comment]
@TechCiel @Vtrois 怎么解决呢？是要加判断吗，我不懂php的语法。

**Comment by ghost** [comment]
新版本中已修复该问题
