### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by zirobin** [seatonjiang/kratos#370]
1.使用图形验证码插件【VAPTCHA 手势验证码】，在文章底部评论时不经过验证也能提交，如图：
![微信截图_20210426171245](https://user-images.githubusercontent.com/41822892/116059668-a7d45780-a6b3-11eb-9518-a9d4f4bdf24c.png)

2.使用【文档】插件，评论框表情溢出了，如图：
![微信截图_20210426171542](https://user-images.githubusercontent.com/41822892/116059812-d4886f00-a6b3-11eb-8867-3f09d7a2ad06.png)

**Comment by zirobin** [comment]
感谢大佬这个主题，用了好多年了，网站挂了找不到官网，后来偶然才发现在这哈哈

**Comment by seatonjiang** [comment]
这里样式应该是冲突了，我测试一下这个插件，看看能不能复现

**Comment by seatonjiang** [comment]
Issues 功能即将关闭，请转移到 Discussions 继续讨论，https://github.com/vtrois/kratos/discussions
