### ISSUE TITLE
重载暗黑样式冲突

### ISSUE THREAD

**Issue by jeremyjone** [seatonjiang/kratos#371]
主题很漂亮，但是没有暗黑模式比较遗憾。我一直用DarkReader的插件，感觉该插件动态渲染出来的暗黑模式还不错。今天想把该插件直接放到网站中。按照其方法：

```js
  DarkReader.setFetchMethod(window.fetch);
  DarkReader.enable({
       brightness: 100,
       contrast: 90,
       sepia: 10
  });
```

将上面函数放在自定义的 js 文件中。

设置完成后，在 Chrome 和 新版Edge 上无效，我以为是该方法不行，但在 FireFox 上却可以正常显示。我以为是浏览器问题，但是更换主题设置后全部浏览器都生效。放在我的其他网站上也可以全部生效。

基于以上，我认为可能是和该主题某些方法冲突吧，如果作者有机会可以看一下。

**Comment by jeremyjone** [comment]
当然，如果作者很快会出暗黑模式的话，就无所谓了

**Comment by seatonjiang** [comment]
后期会新增Dark Mode，问题与 #224 类似，关闭这个问题，后期更新之后会在 #224 中统一回复。
