### ISSUE TITLE
点赞出错：Uncaught ReferenceError: layer is not defined

### ISSUE THREAD

**Issue by alberthe** [seatonjiang/kratos#372]
**问题描述**
点击“点赞”按钮不工作。在开发工具中可见错误信息：Uncaught ReferenceError: layer is not defined （kratos.min.js?ver=3.2.8:1）

**环境信息**
google chrome Version 90.0.4430.93 (Official Build) (64-bit)

**复现步奏**

**Comment by seatonjiang** [comment]
网址发一下我看一下，这个问题应该是资源没完全加载导致的。

**Comment by seatonjiang** [comment]
这个问题应该是你那边资源加载的问题，大概率网络问题导致，暂时关闭这个问题，仍有问题请继续回复。
