### ISSUE TITLE
3.2.10 版本下侧边栏分类目录出现 bug

### ISSUE THREAD

**Issue by g93920079** [seatonjiang/kratos#375]
**问题描述**
3.2.10 版本下点击页面分类目录时必须点中方块内字体才进行跳转，否则会出现光标位于目录字体旁或无反应；标签聚合无此问题
![image](https://user-images.githubusercontent.com/31822907/118750819-c84a9880-b892-11eb-9735-77bfbba4871e.png)

**环境信息**
PHP 版本：7.4.19
Kratos 版本：3.2.10
WordPress 版本：5.7.2
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36

**复现步奏**
点击侧边栏分类中目录方块

**Comment by seatonjiang** [comment]
问题修复了，下个版本推送。
