### ISSUE TITLE
文章目录显示问题

### ISSUE THREAD

**Issue by zkj1072** [seatonjiang/kratos#376]
**问题描述**
作者你好，今天看到主题新增了“文章目录”，刚好需要这个功能，于是我立马就更新了。
不过在使用过程中，我发现在显示上有些问题，具体看图。
![image](https://user-images.githubusercontent.com/59950606/119255645-7cc81f80-bbef-11eb-8dd1-505e27415481.png)
左边的圆点没有排成一串，然后特色标题把[h2title]也显示出来了（不知道这算不算bug，毕竟标题中就有这个标签）
我用的是win10 2K分辨 125%系统缩放。

**环境信息**
PHP 版本：7.3.28
Kratos 版本：3.3.0
WordPress 版本：4.9.18
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

**复现步奏**
在编辑器中编写以下内容
```
<h1>一级标题</h1>
<h2>二级标题</h2>
<h3>三级标题</h3>
<h2>[h2title]特色二级标题[/h2title]</h2>
```

**Comment by seatonjiang** [comment]
问题解决了，等下个版本推送就可以了
![image](https://user-images.githubusercontent.com/57834639/119294863-05929a00-bc88-11eb-9ccd-bedf94fad1b0.png)
