### ISSUE TITLE
文章页面

### ISSUE THREAD

**Issue by icexmoon** [seatonjiang/kratos#377]
**问题描述**
目前带侧边栏的文章详情页还是页面利用太低，对于长文章来说侧边栏比较鸡肋，但是那个目录功能又很有用，能否将其整合到不带侧边栏的文章详情页，做成浮动按钮，点击后展示目录之类的?
**环境信息**

**复现步奏**

**Comment by seatonjiang** [comment]
现在已经有浮动功能了，如果比较长的文章比较多的话，可以开一下这个功能。

**Comment by icexmoon** [comment]
感谢，给开发者点赞~

**Comment by n0099** [comment]
目录应该移到文章顶部区域（正文上方标题下方）

**Comment by icexmoon** [comment]
> 目录应该移到文章顶部区域（正文上方标题下方）

我反而更喜欢侧边浮动的目录，那样更实用，可以随时通过目录跳转，文章头部的固定目录比较鸡肋。

**Comment by seatonjiang** [comment]
下个版本文章目录可以自定义侧边栏的位置了

**Comment by n0099** [comment]
> > 目录应该移到文章顶部区域（正文上方标题下方）
> 
> 我反而更喜欢侧边浮动的目录，那样更实用，可以随时通过目录跳转，文章头部的固定目录比较鸡肋。

建议full viewport height (100vh) sticky
