### ISSUE TITLE
文章页的文章目录能否改变下位置呢

### ISSUE THREAD

**Issue by jalena** [seatonjiang/kratos#378]
**问题描述**
文章目录显示在widget的最后一个，已经失去了它存在的意义。。

要么显示在第一个widget。

**环境信息**

**复现步奏**

**Comment by jalena** [comment]
再者，该主题的widget上应用于首页与文章页的，如果能区别设置的话就更好了！

**Comment by seatonjiang** [comment]
现在把文章目录搞成小工具了，自己添加即可。
