### ISSUE TITLE
<!–nextpage–>分页问题

### ISSUE THREAD

**Issue by qcgzxw** [seatonjiang/kratos#38]
无法分页，希望优化下

**Comment by qcgzxw** [comment]
以及锚点平滑处理的问题

**Comment by TechCiel** [comment]
hmmm...这是WordPress特性么

**Comment by qcgzxw** [comment]
分页应该是TinyMCE插件里面的吧
写了一篇特长的文章，希望可以分页，结果主题不支持0.0，提醒一下三哥，让他优化一下。
准备用锚点文章开头做一个大纲的东西，结果点了之后就直接弹出另一个窗口了

**Comment by TechCiel** [comment]
如果是编辑器加强插件里的（自带主题不支持）这款主题不一定考虑支持。
以及平滑滚动这事我觉得应该是大纲插件处理，而不是主题。
以上，个人观点。

**Comment by qcgzxw** [comment]
好吧

**Comment by whosneo** [comment]
> 如果是编辑器加强插件里的（自带主题不支持）这款主题不一定考虑支持。 以及平滑滚动这事我觉得应该是大纲插件处理，而不是主题。 以上，个人观点。
> […](#)
> On 18 Aug 2017, at 18:00, qcgzxw ***@***.***> wrote: 分页应该是TinyMCE插件里面的吧 写了一篇特长的文章，希望可以分页，结果主题不支持0.0，提醒一下三哥，让他优化一下。 准备用锚点文章开头做一个大纲的东西，结果点了之后就直接弹出另一个窗口了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

经过测试，自带的主题如二〇二〇，Twenty Tweleve 都是支持分页的。我建议作者可以考虑一下的。

**Comment by ziyooren** [comment]
确实，文章不支持分页。另外就是链接到本页锚文本，无论怎么设置都会在新标签页打开。

**Comment by seatonjiang** [comment]
新增了一个分页功能按钮，在文章以及页面中新增了分页功能及样式，等下个版本推送即可。

![image](https://user-images.githubusercontent.com/57834639/76673144-65e67000-65dd-11ea-84ba-a9f52327df59.png)

![image](https://user-images.githubusercontent.com/57834639/76673141-5ff08f00-65dd-11ea-91c8-a100034160b8.png)

![image](https://user-images.githubusercontent.com/57834639/76673130-49e2ce80-65dd-11ea-88ce-316989f3d7cf.png)

![image](https://user-images.githubusercontent.com/57834639/76673135-4fd8af80-65dd-11ea-9a3c-029dcd3d46fa.png)
