### ISSUE TITLE
3.2.9以上版本文章页面排版错乱

### ISSUE THREAD

**Issue by littlef0x** [seatonjiang/kratos#380]
**问题描述**
更新3.2.9之后首页正常，文章页面排版混乱，且不显示文章内容，截图如下（部分信息打码）：

页首：

![图片](https://user-images.githubusercontent.com/32670075/121151848-4ccb7e00-c877-11eb-898a-d9f3ee8da547.png)
![图片](https://user-images.githubusercontent.com/32670075/121152078-7c7a8600-c877-11eb-8e38-de1fb304e5e8.png)

页面中间是大量巨大的logo，页尾：
![图片](https://user-images.githubusercontent.com/32670075/121152280-a3d15300-c877-11eb-9513-c663561361bc.png)

3.2.8同一页面排版如下：
![图片](https://user-images.githubusercontent.com/32670075/121152502-d8450f00-c877-11eb-8884-c6e560b6f3b7.png)

**环境信息**
Ubuntu 20.04.2
OpenLiteSpeed 1.6.21 + MariaDB 10.3.29 + lsphp 7.4 + WordPress 5.7.2
访问：Windows 10 20H2，Firefox 89.0

**复现步奏**
通过WordPress内置更新功能从3.2.8更新，或删除主题重新上传，均可复现
版本3.2.9、3.3.1均可复现
尝试禁用部分插件，无法解决

**Comment by coderstory** [comment]
看上去是css没加载完成

**Comment by littlef0x** [comment]
> 
> 
> 看上去是css没加载完成

可能是的，不过我对前端一无所知，不知大佬能否提供一点线索如何调试，感谢

**Comment by seatonjiang** [comment]
你看一下是不是改了版本号

**Comment by littlef0x** [comment]
> 
> 
> 你看一下是不是改了版本号

没有理解呢，能否详细解释一下？

**Comment by seatonjiang** [comment]
更新一下最新版本，看一下是不是正常了，再检测一下你那里到 https://cdn.jsdelivr.net 链路是不是正常，链路如果有问题，可以把静态资源加速『开启静态资源加速（CSS、JS、Font）』这个功能关掉试一下，如果再有问题请再打开这个问题。
![image](https://user-images.githubusercontent.com/57834639/123498953-a8fb1400-d665-11eb-98f7-7ab60842f153.png)

**Comment by littlef0x** [comment]
感谢开发者回复，更新了3.3.4版本，问题依然存在，已经回退。
尝试开关animate.css、静态资源加速、Gravatar加速，都没有解决。
我本机访问https://cdn.jsdelivr.net 正常，VPS `curl https://cdn.jsdelivr.net` 也正常（会重定向到https://www.jsdelivr.com）。
有考虑过LSCache插件的问题，关闭了插件的所有CSS优化并清除缓存，并没有解决。
ps.之前更新了OpenLiteSpeed，现在版本是1.7.11

**Comment by n0099** [comment]
建议截图f12-network

**Comment by littlef0x** [comment]
更新一下，同一VPS同一环境，使用Cyberpanel内置的模板（带LSCache）新建了一个wp站并安装kratos 3.3.4，不启用https，未安装其他插件和主题，未修改设置，似乎是正常的，推测是网站配置问题或者插件冲突导致。
马上要出差，待回来挨个测试下，再来反馈。

**Comment by seatonjiang** [comment]
这个问题暂时关闭，有问题再回复。
