### ISSUE TITLE
更新能不能不要覆盖Custom啊

### ISSUE THREAD

**Issue by jalena** [seatonjiang/kratos#381]
**问题描述**
每次更新都要覆盖custom，好麻烦啊，每次自动升级后都要自己登录SSH去把custom的东西拉取一遍，做升级包的时候能不能把这个custom文件夹下的内容排除掉啊。

**Comment by jalena** [comment]
> 建议用 git 控制一下，WP 的更新机制不是热更新

每次更新后我都要去git pull一次！

**Comment by n0099** [comment]
建议使用wp子主题 https://developer.wordpress.org/themes/advanced-topics/child-themes/

**Comment by seatonjiang** [comment]
等下次更新，使用子主题即可。
