### ISSUE TITLE
能否给广告位增加hmtl代码显示选项

### ISSUE THREAD

**Issue by acgycy** [seatonjiang/kratos#382]
能否给广告位增加hmtl代码显示选项

默认的主题广告，只能添加一个广告，而且不能外链显示图片

可否在广告处增加

hmtl代码自定义功能呢？

**Comment by seatonjiang** [comment]
指的是文章的广告还是侧边栏的广告

**Comment by acgycy** [comment]
> 指的是文章的广告还是侧边栏的广告

文章的广告，上下两处

**Comment by seatonjiang** [comment]
外链图片是没问题的，这里不准备添加自定义HTML的位置，一旦写不好，容易出问题。
![image](https://user-images.githubusercontent.com/57834639/123498897-473aaa00-d665-11eb-88aa-754fe48fc6dd.png)

**Comment by acgycy** [comment]
> 外链图片是没有问题的，这里不准备添加自定义HTML的位置，写不好，容易出问题。
> ![图像](https://user-images.githubusercontent.com/57834639/123498897-473aaa00-d665-11eb-88aa-754fe48fc6dd.png)


不做html的话，能否考虑增加广告位数量呢，只有一个上下两个广告位，还是太少了，如果改代码实现的话，每次主题更新就要重新在改一遍文件

**Comment by n0099** [comment]
> > 外链图片是没有问题的，这里不准备添加自定义HTML的位置，写不好，容易出问题。
> > ![图像](https://user-images.githubusercontent.com/57834639/123498897-473aaa00-d665-11eb-88aa-754fe48fc6dd.png)
> 
> 不做html的话，能否考虑增加广告位数量呢，只有一个上下两个广告位，还是太少了，如果改代码实现的话，每次主题更新就要重新在改一遍文件

建议使用子主题进行修改https://developer.wordpress.org/themes/advanced-topics/child-themes/
