### ISSUE TITLE
非常规图片URL不能设置，望支持

### ISSUE THREAD

**Issue by index-js** [seatonjiang/kratos#387]
比如https://u.s.fyi/uploads/wechat.png!blog
保存不成功
因为设置了防盗链，不加!blog结尾不能访问，所以必须要符合upyun规范

**Comment by n0099** [comment]
迫真防盗链

**Comment by n0099** [comment]
设置在哪儿？主题设置里引用的图片url？

**Comment by index-js** [comment]
对，s_wechat_url
感觉设置里的图片都不能带特殊字符，不知道在哪里处理

**Comment by seatonjiang** [comment]
参考这个，加到自己的 function 里面即可
https://github.com/vtrois/kratos/blob/5492883d93be95a98443c3c885e41d4abc6bd1e3/inc/theme-volcengine.php#L132-L156

**Comment by seatonjiang** [comment]
明白了，开始我以为你要在文章的图片里面添加后缀，现在对主题设置没有限制了，可以自己随意添加了，等下个版本更新。
![image](https://user-images.githubusercontent.com/57834639/123499464-794e0b00-d669-11eb-90a4-1066b372623d.png)

**Comment by n0099** [comment]
建议直接`add_filter( 'of_sanitize_upload', 'esc_url' );`

**Comment by seatonjiang** [comment]
再保留一段时间，看反应再进行优化。

**Comment by n0099** [comment]
> 建议直接`add_filter( 'of_sanitize_upload', 'esc_url' );`

防xss用，您手动正则处理url不也是为了xss？
