### ISSUE TITLE
评论数量问题

### ISSUE THREAD

**Issue by NorthNanmu** [seatonjiang/kratos#39]
主题single.php和content.php中的
`<a href="<?php the_permalink() ?>#respond"><i class="fa fa-commenting-o"></i> <?php echo kratos_comments_users($post->ID); ?>条评论</a>`
显示的实际上为评论人数，而非评论数量
将`<?php echo kratos_comments_users($post->ID); ?>`
更改为
`<?php comments_number('0', '1', '%')`
后问题解决

**Comment by TechCiel** [comment]
真尴尬 @Vtrois

**Comment by NorthNanmu** [comment]
@TechCiel 咦，猫也在啊

**Comment by JaxsonWang** [comment]
呃...
![image](https://user-images.githubusercontent.com/16836692/29520925-df880b76-86b5-11e7-8dc1-9236b52054c0.png)

**Comment by ghost** [comment]
Done 感谢 @NorthNanmu
