### ISSUE TITLE
关于启用评论分页后回复评论时的两个问题

### ISSUE THREAD

**Issue by n0099** [seatonjiang/kratos#391]
**问题描述**
- 首先本主题的评论分页url为`/article/comment-page-页数/`
- 回复评论链接url为`/article/?replytocom=被回复评论id#respond`，没有携带`comment-page-页数`url“目录”导致下方评论内容中可能不会显示正在回复的评论
- 导致点击正在回复链接（url为`/article/?replytocom=被回复评论id#comment-被回复评论id`）不会跳至该评论（因为并不在当前显示页面）

**环境信息**
PHP 版本：7.4.20
Kratos 版本：3.3.3 with #390 merged
WordPress 版本：5.7.2
User Agent 信息：Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4552.0 Safari/537.36

**复现步奏**
1. 修改/comments.php应用#390 中的修改
2. 更改/wp-admin/options-discussion.php中的评论分页设置为每页显示1条评论
3. 创建一篇文章并创建3条评论
4. 在该文章页点击回复评论链接

**Comment by n0099** [comment]
这可能是wp本身的bug，因为在https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-includes/comment-template.php#L1747 ，get_comment_reply_link()并没有设置cpage
可以使用[get_page_of_comment()](https://developer.wordpress.org/reference/functions/get_page_of_comment/)查找评论所在页数

**Comment by seatonjiang** [comment]
Issues 功能即将关闭，请转移到 Discussions 继续讨论，https://github.com/vtrois/kratos/discussions
