### ISSUE TITLE
文章太长导致目录不动问题

### ISSUE THREAD

**Issue by lichunpeng3300** [seatonjiang/kratos#392]
**问题描述**

当文章太长时，会出现右侧目录无法跟随文章滚动而滚动，只有快到了文章底部目录才会出现滚动。

**环境信息**

PHP 版本：7.4.19
Kratos 版本：3.3.4
WordPress 版本：5.7.2
User Agent 信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

**复现步奏**

现象地址：https://linux98.com/linux/74.html

**Comment by n0099** [comment]
这就是sticky
您可以关掉`主题设置-小工具右边栏随动`缓解，或者手写css针对某些长文章禁用sticky

**Comment by lichunpeng3300** [comment]
> 这就是sticky
> 您可以关掉`主题设置-小工具右边栏随动`缓解，或者手写css针对某些长文章禁用sticky

但是关闭后出现的问题是：文章滑动到中部，目录栏结束了，阅读下面文章的时候就看不到目录了。

**Comment by n0099** [comment]
> > 这就是sticky
> > 您可以关掉`主题设置-小工具右边栏随动`缓解，或者手写css针对某些长文章禁用sticky
> 
> 但是关闭后出现的问题是：文章滑动到中部，目录栏结束了，阅读下面文章的时候就看不到目录了。

这就是没有sticky
建议full viewport height (100vh) sticky

**Comment by seatonjiang** [comment]
Issues 功能即将关闭，请转移到 Discussions 继续讨论，https://github.com/vtrois/kratos/discussions
