### ISSUE TITLE
能否增加广告位数量

### ISSUE THREAD

**Issue by acgycy** [seatonjiang/kratos#394]
能否增加广告位数量，只能填2个广告位有点不够用

**Comment by seatonjiang** [comment]
文章那里的广告位吗？

**Comment by acgycy** [comment]
> 文章那里的广告位吗？

是的

**Comment by seatonjiang** [comment]
新版本添加了几个广告位，文章页面最多6个

![image](https://user-images.githubusercontent.com/57834639/130198978-fb783ad2-9ebb-40e0-a919-1078b974cdb4.png)
![image](https://user-images.githubusercontent.com/57834639/130198951-b4b84157-eb57-4617-bd12-f8ab530f3776.png)
