### ISSUE TITLE
子主题js的kratos.directory错误

### ISSUE THREAD

**Issue by index-js** [seatonjiang/kratos#395]
打赏页面icon
https://github.com/vtrois/kratos/blob/main/assets/js/kratos.js#L139

这里kratos.directory可以直接取主主题的目录，子主题没配置的情况下，现在会404

**Comment by index-js** [comment]
https://github.com/vtrois/kratos/blob/main/inc/theme-core.php#L87
这里可以直接改成$asset_path吧

**Comment by seatonjiang** [comment]
可以这样改，这个是个固定路径，之前写的时候跟二维码图片一块写的，没写死，等下个版本一起推送。
