### ISSUE TITLE
更新3.3.4后无法使用又拍云存储插件

### ISSUE THREAD

**Issue by yanboit** [seatonjiang/kratos#396]
更新了3.3.4后无法使用又拍云插件，上传媒体提示图片后期处理失败，可能是服务器忙或没有足够的资源。请尝试上传较小的文件。推荐的最大尺寸为2500像素

**Comment by yanboit** [comment]
我换个主题就好了，说明应该是主题的问题

**Comment by seatonjiang** [comment]
Issues 功能即将关闭，请转移到 Discussions 继续讨论，https://github.com/vtrois/kratos/discussions
