### ISSUE TITLE
文章列表简介内容的显示字数控制

### ISSUE THREAD

**Issue by CuteLeaf** [seatonjiang/kratos#397]
**问题描述**
建议将文章列表简介内容的显示字数控制添加到主题设置里，这样方便修改，不需要通过修改源文件
https://github.com/vtrois/kratos/blob/240fe5af2ac40bc4a3a67a993bdb25367a3e72b4/inc/theme-article.php#L97
![image](https://user-images.githubusercontent.com/43440669/125608905-fe363d5a-be0b-499e-a1cc-c347f8c00ad7.png)

**Comment by n0099** [comment]
建议使用插件https://wordpress.org/plugins/advanced-excerpt/

**Comment by seatonjiang** [comment]
新增了一个选项，新版本中推送
![image](https://user-images.githubusercontent.com/57834639/130180391-e42ffd3d-9a7d-4a08-ae86-f05350050b5a.png)
