### ISSUE TITLE
希望较小屏幕的设备能够显示侧边栏

### ISSUE THREAD

**Issue by ymefg** [seatonjiang/kratos#4]
手机屏幕太小，侧边栏应该放到下面而不是直接去掉。因为侧边栏可以添加好多有用的小工具啊。

**Comment by Vtrois** [comment]
收到

**Comment by hadwinfu** [comment]
官方主题就是这么设计的

**Comment by Re-keto** [comment]
我也希望作者能在移动设备页面上加入侧边栏的位置！边栏有好多有用的小工具，例如简介，播放器，TAG等…

**Comment by SuperYYT** [comment]
其实放在底部也可以啊，因为小工具确实很实用

**Comment by kkkgo** [comment]
+1 移动设备没有搜索框 太不方便了

**Comment by Vtrois** [comment]
收到问题，近期想办法修复小工具与浮动的bug，添加移动设备支持！

**Comment by ghost** [comment]
其实各有利弊，我倒是建议做一个选项，可以开启和关闭！毕竟有些站点是不需要开启的，因为有些站点侧栏工具比较多，但是移动端如果都显示的话，就会显得页面太长，也影响加载

**Comment by ghost** [comment]
文章页面在移动端的设计就是最简单的将文章内容展示出来，移动端的页面元素越少越实用，所以不准备将小工具展示到文章下面。
