### ISSUE TITLE
文章编辑的时候没有可视化编辑

### ISSUE THREAD

**Issue by woimi** [seatonjiang/kratos#40]
少代码了貌似~

**Comment by TechCiel** [comment]
请尝试禁用所有插件，重新安装最新版wp和主题。

**Comment by woimi** [comment]
用了

Kindeditor For Wordpress
替代解决。。。

**Comment by woimi** [comment]
@TechCiel 试过了，不行啊。。。http://www.51php.com/wordpress/22013.html这个也试过了

**Comment by TechCiel** [comment]
切换回默认主题是否解决问题？若不解决那就不是该主题的问题。

**Comment by ghost** [comment]
这不是主题的问题
