### ISSUE TITLE
统计代码自动转码问题

### ISSUE THREAD

**Issue by gmtgo** [seatonjiang/kratos#400]
**问题描述**
主题设置 --> 收录配置 --> 统计代码，设置后自动转码了。
输入代码：
```
<script type="text/javascript" src="https://s9.cnzz.com/z_stat.php?id=12801xxx&web_id=12801xxx"></script>
```
保存后转码为：
```
<script type="text/javascript" src="https://s9.cnzz.com/z_stat.php?id=12801xxx&amp;web_id=12801xxx"></script>
```
**环境信息**
3.3.4
**复现步奏**

**Comment by seatonjiang** [comment]
问题修复了，等下个版本推送即可
![image](https://user-images.githubusercontent.com/57834639/130179633-29922b9f-d8ad-482e-abed-e94e72e4a37c.png)
![image](https://user-images.githubusercontent.com/57834639/130179649-2d8f38ae-56a4-47d9-ac8a-dcb5367f9bbc.png)
