### ISSUE TITLE
当前wordpress最新版本（5.8）的小工具（旧版小工具除外）保存会报错

### ISSUE THREAD

**Issue by caoguanghui** [seatonjiang/kratos#401]
**问题描述**
选择旧版小工具是可以保存的：
![image](https://user-images.githubusercontent.com/3625774/126901791-3fb100d9-b732-4783-8a88-e6734ab7ede2.png)

但是选择任意一个新版的小工具，报错报错：
![image](https://user-images.githubusercontent.com/3625774/126901843-cf8d35d2-b004-4ae8-96cb-9a8e9ab56dee.png)

**环境信息**
wordpress 5.8中文版
**复现步奏**

**Comment by n0099** [comment]
+!

**Comment by seatonjiang** [comment]
主题更新到最新版本即可，最新版的主题暂时忽略了块级小工具，还是经典样式。
