### ISSUE TITLE
顶部与正文之间有白条

### ISSUE THREAD

**Issue by Var-void** [seatonjiang/kratos#403]
设置了顶部图片导航，但是图片与正文之间有一道白条
![Screen Shot 2021-08-01 at 6 00 38 PM](https://user-images.githubusercontent.com/68727286/127767019-4d645317-d0a7-4b76-a5f5-c6f4bd22e3b7.jpg)
怎么把这道白条去掉（融入背景颜色中），期待见下图
![Screen Shot 2021-08-01 at 6 00 48 PM](https://user-images.githubusercontent.com/68727286/127767036-823b29e4-3d3b-44c3-bf4a-72ca00d71565.jpg)
谢谢大佬🐂

**Comment by seatonjiang** [comment]
这个应该是你这个图片的尺寸问题，按照示例的那个图片尺寸比例改一下试试。

**Comment by seatonjiang** [comment]
问题已经复现了，等下个版本推送就可以修复了。
