### ISSUE TITLE
能否调整一下正文的表格渲染

### ISSUE THREAD

**Issue by icexmoon** [seatonjiang/kratos#406]
**问题描述**
RT
这是我用Typro编辑markdown时候的本地渲染效果：
![image](https://user-images.githubusercontent.com/13990857/130021789-c38ad95a-9aee-4274-a98b-2b3f9705022e.png)
这是在Wordpress上的渲染效果：
![image](https://user-images.githubusercontent.com/13990857/130021948-80553d3a-58fa-4642-8de1-99765d82c9a4.png)
这是在CSDN上发表的渲染效果：
![image](https://user-images.githubusercontent.com/13990857/130022021-12033077-fd18-4dcf-9f24-42a8b0a959a8.png)

**环境信息**

**复现步奏**

**Comment by seatonjiang** [comment]
Issues 功能即将关闭，请转移到 Discussions 继续讨论，https://github.com/vtrois/kratos/discussions
