### ISSUE TITLE
当文章标题过长时，会导致文章摘要显示超出页面布局方框

### ISSUE THREAD

**Issue by hiikii** [seatonjiang/kratos#45]
Hi, 作者你好！
这个主题用起来非常棒！不过我遇到了一点点问题，就是当一篇文章如果标题太长（比如在首页显示有三行甚至四行）时，会导致下面的文章摘要超出方框显示。不知我的描述是否有错，此问题貌似只在标题在三行或以上时才会出现，另外移动设备的网页没有这个问题。

**Comment by ghost** [comment]
已修复，默认配合缩略文字 110 个
