### ISSUE TITLE
文章列表显示异常

### ISSUE THREAD

**Issue by caoruiy** [seatonjiang/kratos#51]
自动获取的摘要中，如果含有较长的网址或者英文文字，会导致列表布局异常，因为无法自动换行。

https://github.com/Vtrois/Kratos/blob/e85a527a3036946df29953b6e11f19c12950e818/style.css#L2514

修改该类为：
```
.kratos-entry-content-new p {
    font-size: 15px;
    word-wrap: break-word;
}
```

解决这个问题！由于无法上传图片，给个链接吧

[点此查看异常效果.png](https://blog.plcent.com/wp-content/uploads/2018/04/list-show-error.png)

**Comment by ghost** [comment]
v2.6.0 已经修复了这个问题，升级试一下？
