### ISSUE TITLE
能否修复一下下载按钮的代码

### ISSUE THREAD

**Issue by JoyNop** [seatonjiang/kratos#58]
未点击 的时候是这样的
![qq 20180513215924](https://user-images.githubusercontent.com/25074750/39968027-017d7d2e-56f9-11e8-9c3f-f1cf5c86ab7a.jpg)
点击之后是这样的
![qq 20180513215931](https://user-images.githubusercontent.com/25074750/39968028-091b778e-56f9-11e8-88f5-e186723449a2.jpg)

下载的版本应该是`Vtrois-Kratos-v2.6.1-0-gfd767a4`

**Comment by laimrz** [comment]
这个修改应该不难

**Comment by ghost** [comment]
已经修复了，使用最新版试一下
