### ISSUE TITLE
手机端显示正文内容中，Bulletpoint的文字比正文要大

### ISSUE THREAD

**Issue by angeljie** [seatonjiang/kratos#591]
如题，看上去字体大小不一致，能否进行修改？或者能否告知，在哪个位置修改这部分的字体设置？多谢！

**Comment by seatonjiang** [comment]
问题已经修复，等新版本推送即可，当前为小屏幕状态下都是 15 像素

![image](https://github.com/seatonjiang/kratos/assets/57834639/bebdadd7-9abe-4710-9132-1ac16980950d)
