### ISSUE TITLE
网易云音乐失效

### ISSUE THREAD

**Issue by hiSevencc** [seatonjiang/kratos#66]
**问题描述**

网易云音乐失效

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2.

**Comment by ghost** [comment]
具体有什么报错？是不是播放需要版权的音乐了？

**Comment by hiSevencc** [comment]
没有任何报错，把音乐的ID输进去之后，页面还显示音乐的相关信息，但是点击播放键 无反应

**Comment by yuki-node** [comment]
这个问题好像……还在

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/16502508/50219521-7607a380-03ca-11e9-8c04-34db6ea371b7.png)

 检测一下音乐是不是「由于版权保护，无法生成外链」的这种，非版权的音乐测试正常。
