### ISSUE TITLE
 主题上传函数和Wordpress媒体库函数相互冲突

### ISSUE THREAD

**Issue by Bugwithme** [seatonjiang/kratos#69]
**问题描述**
 主题上传函数和Wordpress媒体库函数相互冲突，到导致在该主题下无法正常显示媒体库，并且显示图片上传失败提示，其实图片已经上传成功了。换一个主题之后媒体就能正常显示之前显示上传失败的图片。希望在新版本中能够解决。

**产生环境**
windows 
![qq 20181128094349](https://user-images.githubusercontent.com/26682456/49123064-2d405b80-f2f2-11e8-90d1-fcced91fbd0b.jpg)

- 设备：（手机、平板等移动设备时填写此项）
PC
- 浏览器及版本：
最新版Chrome

**Comment by ghost** [comment]
等wp5.x版本一起看

**Comment by sunsea1989** [comment]
我也出现了相同的问题，word press版本是4.9.8
