### ISSUE TITLE
Kratos v2.7.0导致robots.txt错误

### ISSUE THREAD

**Issue by sunsea1989** [seatonjiang/kratos#72]
**问题描述**

启用Kratos v2.7.0版本主题后robots.txt错误。

**产生环境**
- wordpress版本：4.9.8
- 设备：PC
- 浏览器及版本：Chrome

**复现步奏**
访问以上地址后，显示以下内容：

> <script> 
>         const xianjian_title_font=".paradigm-article-title {font-weight:320 !important;}"
>         const $xianjian_title_font_style = document.createElement("style");
>         $xianjian_title_font_style.type = "text/css";
>         document
>           .getElementsByTagName("HEAD")
>           .item(0)
>           .appendChild($xianjian_title_font_style);
>         $xianjian_title_font_style.innerHTML =xianjian_title_font;</script>User-agent: *
> Disallow: /wp-admin/
> Allow: /wp-admin/admin-ajax.php

百度统计Robots提示有11处错误。
![image](https://user-images.githubusercontent.com/35765887/49328750-7a515580-f5b0-11e8-8368-dfb9deb15526.png)

目前通过人工修robots的方式以通过百度的抓取检测。

**Comment by ghost** [comment]
更新版本试一下是否正常了
