### ISSUE TITLE
轮播图插入图片报错

### ISSUE THREAD

**Issue by matrix-1992** [seatonjiang/kratos#73]
**问题描述**

今天刚刚下载您的主题，插入自己的图片报错， 图片格式jpg, 大小50K，600*586像素，72dpi

**产生环境**

- 设备：台式机
- 浏览器及版本：谷歌
- 演示地址：
自己在本地搭建的服务器了

不知道是不是我的图片大小样式不对

**Comment by ghost** [comment]
报错内容是啥？
