### ISSUE TITLE
我装到博客，内容页内容下面出现猜你喜欢，包括侧边栏

### ISSUE THREAD

**Issue by hotmop** [seatonjiang/kratos#74]
**问题描述**
我装到博客，内容页内容下面出现猜你喜欢，包括侧边栏
我想问下如何取消内容页下和侧边栏的猜你喜欢

**产生环境**

- 设备：电脑
- 浏览器及版本：

**复现步奏**

1. 
2.

**Comment by yasee1994** [comment]
刚刚看了你的blog，你是怎么去掉的？能请教下吗

**Comment by hotmop** [comment]
我用的kratos 修改版 原版都带猜你喜欢 很烦
|

签名由 网易邮箱大师 定制

在2018年12月07日 21:47，yasee1994 写道：

刚刚看了你的blog，你是怎么去掉的？能请教下吗

**Comment by yasee1994** [comment]
> 我用的kratos 修改版 原版都带猜你喜欢 很烦 | | 宝贝 | | 邮箱：hemake@163.com | 签名由 网易邮箱大师 定制 在2018年12月07日 21:47，yasee1994 写道： 刚刚看了你的blog，你是怎么去掉的？能请教下吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

可以分享下资源吗，还有主题的下载链接吗

**Comment by ghost** [comment]
大家不喜欢这个功能吗？

**Comment by yasee1994** [comment]
> 大家不喜欢这个功能吗？

不是啦，我是觉得这个功能很赞的，可是就是那一块的样式有点影响阅读（特别是在文章页里的标题和内容混在一起十分不明显）自己的前段水平实在有限。。。不知道怎么修改，所以就很想把他去掉

**Comment by sunsea1989** [comment]
> 大家不喜欢这个功能吗？

喜欢这个功能，我的博客sunsea.im目前在文档下方显示不出来，侧边栏是可以显示的。目前可能还是这个推荐的位置，每个人的需求不太一样，更多的是想自定义下位置吧？

**Comment by hotmop** [comment]
> > 我用的kratos修改版原版都带猜你喜欢很烦| yasee1994写道：刚刚看了你的博客，你是怎么去掉的？能请教下吗 - 你收到了这个，因为你写了这个帖子。直接回复此电子邮件，在GitHub上查看，或将线程静音。
> 
> 可以分享下资源吗，还有主题的下载链接吗

主题你按F12 可以查看修改版地址。我用的修改版。

**Comment by ghost** [comment]
测试一下是否正常了，首页默认已经去掉了，其他位置如果想关闭，在后台找到「推荐设置」，然后删除相应的位置即可。

![image](https://user-images.githubusercontent.com/16502508/50219668-e9a9b080-03ca-11e9-869b-049bf9d0696f.png)
