### ISSUE TITLE
一些新功能的提议

### ISSUE THREAD

**Issue by Jestom** [seatonjiang/kratos#76]
布局列表加回一个传统的布局（官方默认主题就有的布局）
特色图片增加支持url
然后又可以加一个新编辑器的禁用开关（针对5.0）
添加文章作者显示的开关（习惯官方主题的人）
感觉还是有需要的，毕竟这样就免去每次更新都要去改回来了，而且都是增加开关的话，这样就可以满足两边的人了

**Comment by Jestom** [comment]
站点LOGO请求支持SVG

**Comment by ghost** [comment]
新增了SVG图片的支持 9ececcf
