### ISSUE TITLE
404报错 xianjian_title_adapter.css?ver=1.1.0 

### ISSUE THREAD

**Issue by ccinoo** [seatonjiang/kratos#81]
**问题描述**

老大：

更新到2.7.2版本后，看到很多404报错，提示：

https://www.***.***/wp-content/plugins/***/wwwroot/****/wp-content/themes/Kratos-2.5.7/inc/xianjian/xianjian_title_adapter.css?ver=1.1.0

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 浏览器及版本：
chrome71.0.3578.80
- 演示地址：

**复现步奏**

1. 
2.

**Comment by ghost** [comment]
这个怎么样复现呢？

**Comment by ccinoo** [comment]
> 这个怎么样复现呢？

这确实是个问题，我是每次访问首页就会有这个404报错。不知道其他环境是否能复现。

**Comment by Vtrois** [comment]
@ccinoo 你把地址发到邮箱，我去看一下 seaton@vtrois.com

**Comment by ccinoo** [comment]
网址已发邮件，麻烦了。

**Comment by ghost** [comment]
这个已经修复了，下个版本推
