### ISSUE TITLE
有没有办法弄一个无边栏的页面面板

### ISSUE THREAD

**Issue by SWAHZX** [seatonjiang/kratos#85]
**问题描述**

希望有一个无边栏的页面模板。
PHP小白，自己试了一下删掉代码里 sidebar 部分，但是只删掉了边栏，内容宽度并没有变，导致右侧空一大片。

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2.

**Comment by ghost** [comment]
`<section id="main" class="col-md-12">` 这里改成12就可以了
