### ISSUE TITLE
希望摘要保留格式？？

### ISSUE THREAD

**Issue by cytsyl** [seatonjiang/kratos#86]
在设置的时候没有看到有能够保留摘要格式的选项，试过了插件cn expert好像没有反应，如果想要直接修改代码的话应该从哪里入手呢？
第一次使用github，如果提问有不妥之处请指出，谢谢啦。

**Comment by ghost** [comment]
举个例子看看？具体保留格式是指的什么？

**Comment by seatonjiang** [comment]
摘要信息，仅保留正常的文本格式，保证前端页面正确的输出，3.0.0 版本已经推送，请升级测试。
