### ISSUE TITLE
无法实现页面内跳转

### ISSUE THREAD

**Issue by dayudaoren** [seatonjiang/kratos#87]
无论是链接到锚点还是网址，都会在新标签页打开，无法实现页面内跳转。请问能解决吗？我目前使用的版本是2.6.4

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/16502508/51434710-3e7a6880-1ca2-11e9-8774-f6cc789c6da3.png)
这个在添加链接的时候勾选一下就是新页面了，不勾选就是页内跳转

**Comment by dayudaoren** [comment]
非常感谢，我使用的版本是2.6.4，在提问前我已经试过您说的这种方法了，但是无效。后来我通过打开functions.php，定位到603行，将这两行注释掉就可以了。感谢您的帮助。
if( count($match) < 1 )
                    $noFollow .= ' target="_blank" ';
