### ISSUE TITLE
简介缩略问题以及右侧两个滚动条

### ISSUE THREAD

**Issue by lmh555168** [seatonjiang/kratos#89]
**问题描述**
之前用的是2.63版，安装最新版本后遇到首页简介缩略超出边界，显示了文章的所有内容并且内容有重叠，以及右侧两个滚动条，手机上会把文章的所有内容都显示出来。把主题里面的简介缩略改成1后右侧变成一个滚动条，简介缩略有些文章会显示比较多的字，不知道是我哪里设置问题。

在主题管理器里面删除此主题提示，刪除失敗：該佈景主題不存在。

（简明扼要的描述一下问题）
**产生环境**

- 设备：PC
- 浏览器及版本：chrome 71
- 演示地址：www.issac.tk
https://i.loli.net/2019/01/25/5c4a6c859f570.png
wordpress 5.03

**复现步奏**
切换到本主题就会出现
现在安装旧版的这个主题也会变成这样

**Comment by lmh555168** [comment]
wordpress后台语言由之前的繁体改成简体，并且重新升级简体wordpress后问题解决，把后台语言改成英文后，无升级英文版wordpress问题会再复现。

**Comment by seatonjiang** [comment]
3.0.0 版本中，英文版中的问题已修复，请升级测试。
