### ISSUE TITLE
建议：随机化特色图片

### ISSUE THREAD

**Issue by yudshj** [seatonjiang/kratos#9]
KRATOS的作者，您好：

最近发现的这款优秀的免费主题 真的是超级赞啊！

现在的特色图片是固定的，如果加入在制定目录下寻找特色图片（像恋月theme）那样，感觉更好看啦！

都用一张有些小单调。

实在是太喜欢这个主题辣！
Thanks XD~

**Comment by Vtrois** [comment]
这个可以增加

**Comment by ghost** [comment]
关于这个随机化特色图片如果硬要增加的话，我建议做成一个开关功能选项。
例如开启该功能的情况下，当文章没有特色图片的情况下，主题会根据预设目录的图片随机展示。
如果关闭该功能则默认该文章有特色图片才显示，否则则没有。

**Comment by ghost** [comment]
这个主题为了做博文的展示，特色图建议是每一篇文章都单独对待，所以这个小众需求建议自己实现
