### ISSUE TITLE
顶部菜单在未登录的时候与主页顶部图片部分重叠

### ISSUE THREAD

**Issue by dickybora** [seatonjiang/kratos#91]
顶部菜单在未登录的时候与主页顶部图片部分重叠

- 浏览器及版本：explorer11，猎豹6.5
- 演示地址： http://www.dbdvapor.com

**Comment by ghost** [comment]
admin bar 的原因，在写样式的时候是按照去掉之后写的，所以会有冲突，建议是把 admin bar 去掉。
