### ISSUE TITLE
问一下先荐 插件是KRATOS主题自带的么？

### ISSUE THREAD

**Issue by StarryVoid** [seatonjiang/kratos#92]
你好，先荐 插件是KRATOS主题自带的么？
这个插件有没有开关关闭？

**Comment by StarryVoid** [comment]
https://github.com/Vtrois/Kratos/commit/71bb2694f6f274ca9305c67c0e0d23738660a568
https://github.com/Vtrois/Kratos/commit/ba89b1ebfc9f5bb51684389fdef36598ffd461c7
我找到了这两个页面，如果完全撤回这些操作是否可以干净的在之后版本清理掉"先荐"

**Comment by ghost** [comment]
V3版本已经移除
