### ISSUE TITLE
本地安装文章点赞报错

### ISSUE THREAD

**Issue by angping** [seatonjiang/kratos#94]
**问题描述**

本地安装文章点赞报错

**产生环境**

- 设备：win10 
- 浏览器及版本：Google Chrome 已是最新版本 版本 72.0.3626.121（正式版本） （64 位）
- 演示地址：

![~W{%ZOBKSI$}V 22DB)KH{7](https://user-images.githubusercontent.com/33945275/54208755-791cb680-4517-11e9-8643-ab0c9512b541.png)

![_`D9KDXLX(T 1)Q6H _{UVG](https://user-images.githubusercontent.com/33945275/54208770-8174f180-4517-11e9-9c28-07264ac5c03c.png)

**复现步奏**

1. 
2.

**Comment by ghost** [comment]
在V3版本中修复了这个问题
