### ISSUE TITLE
Button按钮如何自定义修改

### ISSUE THREAD

**Issue by yc-maltazard** [seatonjiang/kratos#96]
**希望能够自定义编辑添加按钮的图标颜色及内容**

现有的[ypbtn] [/ypbtn]标签确实非常非常方便，想希望能够实现一个可以自定义的按钮功能，比如希望是红色的按钮，里面的titles可以自定义文字，不知道是否可能增加上这个功能。

**Comment by seatonjiang** [comment]
可以参考 /inc/theme-shortcode.php 以及/assets/js/buttons/more.js 中的代码，自己新增想要的样式，并且在 custom 中新增相关 js css php 代码
