### ISSUE TITLE
与a3 lazy load、bj lazy load 插件不兼容

### ISSUE THREAD

**Issue by lt-xu** [seatonjiang/kratos#98]
**问题描述**

启用a3 lazy load、bj lazy load插件时，文章中的图片在文章中能正常显示，但点开后是一个像素点

**产生环境**
chrome、手机浏览器、 qq内置浏览器都会出现此问题 WordPress版本是5.0.3
- 设备：（手机、平板等移动设备时填写此项）
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 启用a3 lazy load或bj lazy load插件
2. 打开一篇有图片的文章
3.点击图片

**Comment by 907739769** [comment]
我也遇到了  有解决办法了吗？

**Comment by lt-xu** [comment]
换 Lazy Load Optimizer插件

**Comment by ccinoo** [comment]
我遇到的是二级菜单出现错位，大家有遇到吗？
![image](https://user-images.githubusercontent.com/30647119/56344095-2b1e6100-61ef-11e9-8e28-f127859923f7.png)

**Comment by 907739769** [comment]
> 我遇到的是二级菜单出现错位，大家有遇到吗？
> ![image](https://user-images.githubusercontent.com/30647119/56344095-2b1e6100-61ef-11e9-8e28-f127859923f7.png)
估计是不支持

**Comment by ccinoo** [comment]
> > 我遇到的是二级菜单出现错位，大家有遇到吗？
> > ![image](https://user-images.githubusercontent.com/30647119/56344095-2b1e6100-61ef-11e9-8e28-f127859923f7.png)
> > 估计是不支持

可以原来支持的，升级后才出现这问题的。

**Comment by seatonjiang** [comment]
尝试使用  Lazy Load Optimizer 是否正常，目前 3.0.0 版本已经推送，欢迎升级测试
